(()=>{'use strict';
const API='http://127.0.0.1:8000';
const $=id=>document.getElementById(id);
const state={catalog:[],times:[],i:0,active:'temperature',geo:null,arrows:[],field:null,busy:false,token:0,currentAnim:null};
const order=['temperature','temperature_anomaly','salinity','currents','sea_level','abnormal','chlorophyll'];
const labels={temperature:'Temperature',temperature_anomaly:'Sea surface temperature anomaly',salinity:'Salinity',currents:'Currents',sea_level:'Sea level',abnormal:'Abnormal / disaster data',chlorophyll:'Chlorophyll'};
const descriptions={temperature:'3D water temperature',temperature_anomaly:'SST anomaly',salinity:'Salinity / PSU',currents:'Direction and speed',sea_level:'Sea-surface height',abnormal:'Cyclone / warning information',chlorophyll:'Chlorophyll-a'};
async function get(path){const r=await fetch(API+path,{cache:'no-store'});if(!r.ok){let t='';try{t=await r.text()}catch{}throw Error(r.status+' '+t)}return r.json()}
function date(v){if(v==null||v==='')return null;if(typeof v==='number'||/^\\d{16,}$/.test(String(v))){let n=Number(v);if(Math.abs(n)>=1e17)n/=1e6;else if(Math.abs(n)>=1e14)n/=1e3;else if(Math.abs(n)>=1e11)n/=1e3;const d=new Date(n);if(!isNaN(d))return d}const d=new Date(v);return isNaN(d)?null:d}
const apiTime=v=>{const d=date(v);return d?d.toISOString():String(v??'')};
const fmt=v=>{const d=date(v);return d?d.toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'}):String(v??'')};
function bounds(){return state.geo?.bounds||[84.104975983510294,92.99298840579259,16.070728135396756,23.524363913510872]}
function esc(s){return String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function info(id){return state.catalog.find(v=>v.id===id)||null}
function abnormal(){for(const d of state.datasets||[])for(const v of d.variables||[])if(/cyclone|storm|disaster|warning|alert|tropical/i.test(`${v.name} ${v.long_name||''} ${v.standard_name||''}`))return {...v,file:d.file};return null}
function buildVars(){const box=$('vars');if(!box)return;const a=abnormal();const arr=order.map(id=>id==='abnormal'?{id,label:labels[id],available:!!a,file:a?.file,variable:a?.name,units:a?.units}:info(id)||{id,label:labels[id],available:false});box.innerHTML=arr.map((v,i)=>`<button class="var ${v.id===state.active?'active':''} ${v.available===false?'off':''}" data-var="${v.id}" ${v.available===false?'disabled':''}><span class="ico">${i+1}</span><span><strong>${esc(v.label)}</strong><span>${esc(v.available===false?'No backend dataset detected':descriptions[v.id])}</span></span><i class="dot ${v.available===false?'off':''}"></i></button>`).join('');box.querySelectorAll('.var').forEach(b=>b.onclick=()=>selectVar(b.dataset.var));}
function finite(a){const out=[];(function walk(x){if(Array.isArray(x))x.forEach(walk);else if(typeof x==='number'&&Number.isFinite(x))out.push(x)})(a);return out}
function quantile(a,p){if(!a.length)return null;const x=(a.length-1)*p,i=Math.floor(x),j=Math.ceil(x);return a[i]+(a[j]-a[i])*(x-i)}
function stats(a){const s=finite(a).sort((x,y)=>x-y);return{s,min:s[0]??null,max:s[s.length-1]??null,p01:quantile(s,.01),p05:quantile(s,.05),p50:quantile(s,.50),p95:quantile(s,.95),p99:quantile(s,.99)}}
function rankIndex(s,x){if(!s.length||!Number.isFinite(x))return .5;let lo=0,hi=s.length;while(lo<hi){const m=(lo+hi)>>1;if(s[m]<=x)lo=m+1;else hi=m}return Math.max(0,Math.min(1,(lo-.5)/s.length))}
function perceptual(id,q){q=Math.max(0,Math.min(1,q));const stops={
 temperature:[[0.00,.05,.55],[.13,.32,.95],[.15,.78,1],[.95,.95,.55],[1,.42,.04],[.72,.02,.02]],
 temperature_anomaly:[[.02,.22,.70],[.16,.48,.95],[.82,.90,1],[1,.92,.86],[.98,.42,.16],[.62,.01,.03]],
 salinity:[[.01,.10,.55],[.02,.48,.90],[.12,.82,.73],[.55,.93,.32],[.96,.96,.18]],
 chlorophyll:[[.96,1,.86],[.72,.95,.55],[.26,.78,.30],[.02,.48,.15],[.00,.20,.06]],
 sea_level:[[.10,.18,.55],[.20,.45,.82],[.50,.78,.95],[.96,.88,.55],[.85,.28,.16]],
 default:[[.04,.10,.30],[.10,.45,.75],[.70,.85,.92],[.96,.65,.30],[.60,.05,.03]]}[id]||stops.default;const x=q*(stops.length-1),i=Math.min(stops.length-2,Math.floor(x)),t=x-i,a=stops[i],b=stops[i+1];return[a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t,a[2]+(b[2]-a[2])*t]}
function diverging(id,q){if(id==='temperature_anomaly'){const p=.5;const d=Math.min(1,Math.abs(q-p)*2);const c=d<=.5?[0.96,0.97,1]:[1,0.60,0.50];const base=d<=.5?[0.14,0.45,0.92]:[0.86,0.08,0.05];const u=d*2;return[c[0]*(1-u)+base[0]*u,c[1]*(1-u)+base[1]*u,c[2]*(1-u)+base[2]*u]}return perceptual(id,q)}
function color(id,q){return id==='temperature_anomaly'?diverging(id,q):perceptual(id,q)}
function updateLegend(){const v=info(state.active),l=$('legend'),t=$('legendTitle');if(!l)return;if(state.active==='currents'){l.style.display='block';l.className='legend currents';t.textContent='Currents · direction + speed';l.style.background='linear-gradient(90deg,#2458c5,#56b6d9,#f4f4f4,#f28b55,#b52224)';$('legendLo').textContent='slow';$('legendHi').textContent='fast';return}if(state.active==='abnormal'){l.style.display='none';t.textContent='Abnormal / disaster information';$('legendLo').textContent='';$('legendHi').textContent='';return}l.style.display='block';l.className='legend '+({temperature:'temp',temperature_anomaly:'anomaly',salinity:'sal',chlorophyll:'chl',sea_level:'neutral'}[state.active]||'neutral');t.textContent=(v?.label||labels[state.active])+' · adaptive percentile scale';$('legendLo').textContent=state.field?.lo!=null?`${Number(state.field.lo).toFixed(3)} ${v?.units||''}`:'low';$('legendHi').textContent=state.field?.hi!=null?`${Number(state.field.hi).toFixed(3)} ${v?.units||''}`:'high'}
function scene(){return BABYLON.Engine.LastCreatedEngine?.scenes?.[0]||null}
function removeArrows(){if(state.currentAnim){cancelAnimationFrame(state.currentAnim);state.currentAnim=null}state.arrows.forEach(m=>m.dispose());state.arrows=[]}
function nearest(a,x){if(!a?.length)return 0;let lo=0,hi=a.length-1,asc=a[0]<=a[hi];while(lo<hi){const m=(lo+hi)>>1;if(asc?a[m]<x:a[m]>x)lo=m+1;else hi=m}if(lo>0&&lo<a.length&&Math.abs(a[lo]-x)>=Math.abs(a[lo-1]-x))return lo-1;return lo}
function flatIndex(shape,ix){let q=0,s=1;for(let k=shape.length-1;k>=0;k--){q+=Math.max(0,Math.min(shape[k]-1,ix[k]??0))*s;s*=shape[k]}return q}
function fieldValue(arr,shape,ix){return arr[flatIndex(shape,ix)]}
function targetMeshes(){const s=scene();return s?s.meshes.filter(m=>m.metadata?.waterLayer||m.metadata?.solvxWaterSurface):[]}
function apply(field){const s=scene();if(!s)return;const lat=field.coordinates?.latitude||field.coordinates?.lat,lon=field.coordinates?.longitude||field.coordinates?.lon,dep=field.coordinates?.depth,dims=field.dimensions||[],shape=field.shape||[],raw=[];(function walk(x){if(Array.isArray(x))x.forEach(walk);else raw.push(typeof x==='number'&&Number.isFinite(x)?x:NaN)})(field.data);if(!Array.isArray(lat)||!Array.isArray(lon)||!shape.length)return;const st=stats(field.data);if(st.min==null||st.max==null)return;let lo=st.p01,hi=st.p99;if(!Number.isFinite(lo)||!Number.isFinite(hi)||lo===hi){lo=st.min;hi=st.max}if(lo===hi){const pad=Math.max(Math.abs(lo)*.005,1e-6);lo-=pad;hi+=pad}state.field={...field,...st,lo,hi};updateLegend();const b=bounds(),klat=111.32,klon=111.32*Math.cos((b[2]+b[3])/2*Math.PI/180),lon0=(b[0]+b[1])/2,lat0=(b[2]+b[3])/2;for(const mesh of targetMeshes()){const p=mesh.getVerticesData(BABYLON.VertexBuffer.PositionKind);if(!p)continue;const out=new Float32Array((p.length/3)*4),di=Array.isArray(dep)&&mesh.metadata?.depth!=null?nearest(dep,mesh.metadata.depth):0;for(let k=0,o=0;k<p.length;k+=3,o+=4){const yi=nearest(lat,lat0+p[k+2]/klat),xi=nearest(lon,lon0+p[k]/klon),ix=dims.map(d=>d==='time'?0:d==='depth'?di:(d==='latitude'||d==='lat'?yi:(d==='longitude'||d==='lon'?xi:0))),v=fieldValue(raw,shape,ix);let q=Number.isFinite(v)?(v-lo)/(hi-lo):.5;q=Math.max(0,Math.min(1,q));if(state.active==='temperature_anomaly'){q=Math.max(0,Math.min(1,(v-st.p05)/(st.p95-st.p05||1)))}const c=color(state.active,q);out[o]=c[0];out[o+1]=c[1];out[o+2]=c[2];out[o+3]=1}mesh.useVertexColors=true;mesh.setVerticesData(BABYLON.VertexBuffer.ColorKind,out,true)}$('status').textContent=`${labels[state.active]} · ${Number(lo).toFixed(3)} → ${Number(hi).toFixed(3)} · adaptive to current data · ${fmt(state.times[state.i])}`}
function vectorGeometry(s,p,q){const dx=q.x-p.x,dz=q.z-p.z,len=Math.hypot(dx,dz);if(len<.01)return[];const ux=dx/len,uz=dz/len,nx=-uz,nz=ux,head=Math.min(3.5,Math.max(1.0,len*.28)),wide=head*.55;const h1=new BABYLON.Vector3(q.x-ux*head+nx*wide,q.y,q.z-uz*head+nz*wide),h2=new BABYLON.Vector3(q.x-ux*head-nx*wide,q.y,q.z-uz*head-nz*wide),shaft=BABYLON.MeshBuilder.CreateLines('solvx-current',{points:[p,q],updatable:false},s),ah=BABYLON.MeshBuilder.CreateLines('solvx-current-head',{points:[h1,q,h2],updatable:false},s);return[shaft,ah]}
async function renderCurrents(){removeArrows();const s=scene();if(!s)throw Error('3D scene is not ready');const t=apiTime(state.times[state.i]);const r=await get('/ocean/current-grid?time='+encodeURIComponent(t)+'&depth=0&stride=3');const b=bounds(),klat=111.32,klon=111.32*Math.cos((b[2]+b[3])/2*Math.PI/180),lon0=(b[0]+b[1])/2,lat0=(b[2]+b[3])/2;const speeds=[];for(let j=0;j<r.latitude.length;j++)for(let i=0;i<r.longitude.length;i++){const u=Number(r.u?.[j]?.[i]),v=Number(r.v?.[j]?.[i]);if(Number.isFinite(u)&&Number.isFinite(v))speeds.push(Math.hypot(u,v))}speeds.sort((a,b)=>a-b);const p95=quantile(speeds,.95)||Math.max(...speeds,1);let count=0;for(let j=0;j<r.latitude.length;j++)for(let i=0;i<r.longitude.length;i++){const u=Number(r.u?.[j]?.[i]),v=Number(r.v?.[j]?.[i]);if(!Number.isFinite(u)||!Number.isFinite(v))continue;const mag=Math.hypot(u,v);if(mag<1e-5)continue;const x=(r.longitude[i]-lon0)*klon,z=(r.latitude[j]-lat0)*klat,base=10+Math.min(24,(mag/(p95||1))*24),p=new BABYLON.Vector3(x,.95,z),q=new BABYLON.Vector3(x+(u/mag)*base,.95,z+(v/mag)*base),ms=vectorGeometry(s,p,q);for(const m of ms){m.color=new BABYLON.Color3(.92,.98,1);m.isPickable=false;m.renderingGroupId=6;m.metadata={solvxCurrent:true};state.arrows.push(m)}count++}$('status').textContent=`Currents · ${count} animated vectors · speed max ${Number(p95).toFixed(3)} m/s · ${fmt(state.times[state.i])}`;updateLegend();animateCurrents()}
function animateCurrents(){let start=null;const animate=t=>{if(!state.arrows.length)return;start??=t;const phase=(t-start)/900;for(let k=0;k<state.arrows.length;k+=2){const shaft=state.arrows[k],head=state.arrows[k+1];if(!shaft||!head)continue;const pulse=.72+.28*(.5+.5*Math.sin(phase*2+Math.floor(k/2)*.7));shaft.alpha=pulse;head.alpha=pulse}state.currentAnim=requestAnimationFrame(animate)};state.currentAnim=requestAnimationFrame(animate)}
async function load(){const token=++state.token;if(state.active==='currents'){await renderCurrents();return}const v=state.active==='abnormal'?abnormal():info(state.active);if(!v?.available||!v.file||!v.variable){$('status').textContent=labels[state.active]+': no backend dataset detected';return}state.busy=true;try{const p=new URLSearchParams({file:v.file,variable:v.variable,lat_min:String(bounds()[2]),lat_max:String(bounds()[3]),lon_min:String(bounds()[0]),lon_max:String(bounds()[1]),time_start:apiTime(state.times[state.i]),time_end:apiTime(state.times[state.i]),stride:'5'});if(state.meta?.[v.file]?.depth){p.set('depth_min',state.meta[v.file].depth.min);p.set('depth_max',state.meta[v.file].depth.max)}const f=await get('/data/region/array?'+p);if(token!==state.token)return;apply(f)}catch(e){if(token===state.token)$('status').textContent=labels[state.active]+' unavailable: '+e.message}finally{state.busy=false}}
async function selectVar(id){if(!order.includes(id))return;state.active=id;document.querySelectorAll('.var').forEach(b=>b.classList.toggle('active',b.dataset.var===id));if(id!=='currents')removeArrows();updateLegend();await load()}
function setTime(i){state.i=Math.max(0,Math.min(state.times.length-1,+i||0));const x=$('timeSlider');if(x)x.value=state.i;const v=state.times[state.i];$('timeValue').textContent=fmt(v);$('timeRaw').textContent=apiTime(v);load()}
function installTimeline(){const x=$('timeSlider');if(!x)return;x.max=Math.max(0,state.times.length-1);x.oninput=()=>setTime(x.value);$('play').onclick=()=>{if(x.dataset.playing==='1'){x.dataset.playing='0';$('play').textContent='PLAY';return}x.dataset.playing='1';$('play').textContent='PAUSE';const tick=()=>{if(x.dataset.playing!=='1')return;setTime((state.i+1)%state.times.length);setTimeout(tick,1200)};tick()}}
function scalar(v){if(v==null)return'—';if(typeof v==='number')return Number.isFinite(v)?v.toFixed(3):'—';if(typeof v==='object')return Object.entries(v).map(([k,x])=>esc(k)+': '+scalar(x)).join(' · ');return esc(v)}
async function point(point,mesh){const b=bounds(),klat=111.32,klon=111.32*Math.cos((b[2]+b[3])/2*Math.PI/180),lon0=(b[0]+b[1])/2,lat0=(b[2]+b[3])/2,lat=lat0+point.z/klat,lon=lon0+point.x/klon,depth=mesh?.metadata?.depth??null,t=apiTime(state.times[state.i]);$('coords').textContent=`${lat.toFixed(4)}°N · ${lon.toFixed(4)}°E`;$('readout').style.display='block';$('readoutGrid').innerHTML='<div class="rval">Loading variables…</div>';const vals=await Promise.all(order.map(async id=>{if(id==='abnormal'){const a=abnormal();if(!a)return{id,label:labels[id],value:null,units:''};try{const p=new URLSearchParams({file:a.file,variable:a.name,latitude:String(lat),longitude:String(lon),time:t});if(depth!=null)p.set('depth',String(depth));const z=await get('/data/point?'+p);return{id,label:labels[id],value:z.value,units:a.units||''}}catch{return{id,label:labels[id],value:null,units:a.units||''}}}const v=info(id);if(!v?.available)return{id,label:labels[id],value:null,units:v?.units||''};if(id==='currents'){try{const r=await get('/ocean/current-grid?time='+encodeURIComponent(t)+'&depth='+(depth??0)+'&stride=10');const yi=nearest(r.latitude,lat),xi=nearest(r.longitude,lon),u=r.u[yi]?.[xi],vv=r.v[yi]?.[xi];return{id,label:labels[id],value:{u,v:s=>s,speed:Math.hypot(u||0,vv||0)},units:r.units||'m/s'}}catch{return{id,label:labels[id],value:null,units:'m/s'}}}try{const p=new URLSearchParams({file:v.file,variable:v.variable,latitude:String(lat),longitude:String(lon),time:t});if(depth!=null)p.set('depth',String(depth));const z=await get('/data/point?'+p);return{id,label:labels[id],value:z.value,units:v.units||''}}catch{return{id,label:labels[id],value:null,units:v.units||''}}}));$('readoutGrid').innerHTML=vals.map(v=>`<div class="rval"><b>${esc(v.label)}</b><span>${scalar(v.value)} ${esc(v.units||'')}</span></div>`).join('');$('readoutTime').textContent=`${fmt(state.times[state.i])} · depth ${depth==null?'surface':Number(depth).toFixed(1)+' m'}`}
async function init(){try{state.geo=await fetch('geometry.json?'+Date.now()).then(r=>r.json());const[c,t,d]=await Promise.all([get('/ocean/catalog'),get('/ocean/time'),get('/datasets')]);state.catalog=c.variables||[];state.times=t.values||[];state.datasets=d.datasets||[];for(const v of state.catalog.filter(x=>x.available)){try{const m=await get('/metadata/'+encodeURIComponent(v.file));state.meta[v.file]={depth:m.coordinates?.depth}}catch{}}buildVars();installTimeline();updateLegend();const s=scene();if(s)s.onPointerObservable.add(async e=>{if(e.type!==BABYLON.PointerEventTypes.POINTERDOWN||e.event.button!==0)return;const p=s.pick(s.pointerX,s.pointerY,m=>m.metadata?.waterLayer||m.name==='GEBCO SOIL SEABED');if(p?.hit&&p.pickedPoint)await point(p.pickedPoint,p.pickedMesh)});await load()}catch(e){console.error('Adaptive fields',e);$('status').textContent='Adaptive field error: '+e.message)}}setTimeout(init,1400);
})();