import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';

const API=`${location.protocol}//${location.hostname}:8000`,$=id=>document.getElementById(id);
let geo,catalog=[],current=null,times=[],depths=[],depthEx=55,playing=false,lastPlay=0,token=0,fit={cx:0,cy:0,size:1000},currentAnim=null,currentItems=[];
const cache=new Map();
const palettes={
 temperature:{cls:'temp',c:[[0x071b8f,0],[0x075cff,.18],[0x00c6ff,.36],[0xfff000,.58],[0xff6b00,.78],[0xb40000,1]]},
 temperature_anomaly:{cls:'anomaly',c:[[0x083b9c,0],[0x3fa7ff,.25],[0xf7f7f7,.5],[0xff9a62,.75],[0xb40018,1]]},
 salinity:{cls:'sal',c:[[0x071d9b,0],[0x00a6ff,.22],[0x00d49a,.48],[0xb8e52e,.72],[0xffe600,1]]},
 chlorophyll:{cls:'chl',c:[[0xf7fff0,0],[0xb7ef59,.2],[0x42c83e,.45],[0x078d38,.72],[0x003d20,1]]},
 neutral:{cls:'neutral',c:[[0x102caa,0],[0x00a9ff,.25],[0x26d08b,.5],[0xffd21a,.75],[0xd40000,1]]}
};
const defs=[['temperature','Temperature','°C','♨'],['temperature_anomaly','Sea surface temp anomaly','°C','△'],['salinity','Salinity','PSU','≈'],['currents','Currents','m/s','↝'],['sea_level','Sea level','dataset unit','≋'],['hazard','Abnormal / hazard','warnings','!'],['chlorophyll','Chlorophyll','dataset unit','●']];
const get=async u=>{const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error(`${r.status} ${r.statusText}`);return r.json()};
const finite=x=>typeof x==='number'&&Number.isFinite(x),flat=(v,o=[])=>{Array.isArray(v)?v.forEach(x=>flat(x,o)):o.push(v);return o};
function clear(g){while(g.children.length){const o=g.children.pop();o.traverse(q=>{q.geometry?.dispose();q.material?.dispose?.()})}}
function td(v){if(v==null)return null;const n=Number(v);if(Number.isFinite(n)&&Math.abs(n)>1e17)return new Date(n/1e6);if(Number.isFinite(n)&&Math.abs(n)>1e11)return new Date(n);const d=new Date(v);return isNaN(d)?null:d}
const date=v=>{const d=td(v);return d?d.toISOString().slice(0,10):String(v??'—')},iso=v=>{const d=td(v);return d?d.toISOString():String(v)},fmt=v=>{if(!finite(v))return'—';const a=Math.abs(v);return a>=100?v.toFixed(1):a>=10?v.toFixed(2):v.toFixed(3)};
function quantile(a,p){if(!a.length)return null;const x=(a.length-1)*p,i=Math.floor(x),j=Math.ceil(x);return a[i]+(a[j]-a[i])*(x-i)}
function stats(v){const a=flat(v).map(Number).filter(finite).sort((x,y)=>x-y);return{a,min:a[0],max:a.at(-1),p01:quantile(a,.01),p05:quantile(a,.05),p95:quantile(a,.95),p99:quantile(a,.99)}}
function col(kind,t){const p=palettes[kind]||palettes.neutral;t=Math.max(0,Math.min(1,t));for(let i=0;i<p.c.length-1;i++){const a=p.c[i],b=p.c[i+1];if(t<=b[1])return new THREE.Color(a[0]).lerp(new THREE.Color(b[0]),(t-a[1])/(b[1]-a[1]))}return new THREE.Color(p.c.at(-1)[0])}
function xy(lon,lat,z=0){const b=geo.bounds,lon0=(b[0]+b[1])/2,lat0=(b[2]+b[3])/2;return[(lon-lon0)*111.32*Math.cos(lat0*Math.PI/180),(lat-lat0)*111.32,z]}
const scene=new THREE.Scene();scene.background=new THREE.Color(0xdfeaf1);const camera=new THREE.PerspectiveCamera(45,innerWidth/innerHeight,.1,20000);const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;$('app').appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.075;controls.screenSpacePanning=true;controls.minDistance=30;controls.maxDistance=12000;controls.mouseButtons.LEFT=THREE.MOUSE.ROTATE;controls.mouseButtons.RIGHT=THREE.MOUSE.PAN;controls.mouseButtons.MIDDLE=THREE.MOUSE.DOLLY;
scene.add(new THREE.HemisphereLight(0xffffff,0x78918c,2.1));const sun=new THREE.DirectionalLight(0xffffff,2.4);sun.position.set(-500,-500,1200);scene.add(sun);const root=new THREE.Group();scene.add(root);const terrainG=new THREE.Group(),landG=new THREE.Group(),coastG=new THREE.Group(),eezG=new THREE.Group(),waterG=new THREE.Group(),fieldG=new THREE.Group(),currentG=new THREE.Group();[terrainG,landG,coastG,eezG,waterG,fieldG,currentG].forEach(g=>root.add(g));
function fitCamera(){const d=Math.max(650,fit.size*1.65);camera.position.set(fit.cx+d*.72,fit.cy-d*.82,d*.62);controls.target.set(fit.cx,fit.cy,-Math.min(100,fit.size*.05));controls.update();camera.far=Math.max(20000,d*8);camera.updateProjectionMatrix()}
function buildOcean(){clear(terrainG);clear(landG);clear(coastG);clear(eezG);clear(waterG);clear(fieldG);clear(currentG);const t=geo.terrain,x=t.x,y=t.y,r=t.rawDepthKm,nx=x.length,ny=y.length;const minX=Math.min(...x),maxX=Math.max(...x),minY=Math.min(...y),maxY=Math.max(...y);fit={cx:(minX+maxX)/2,cy:(minY+maxY)/2,size:Math.max(maxX-minX,maxY-minY)};const p=new Float32Array(nx*ny*3),ind=[];for(let j=0;j<ny;j++)for(let i=0;i<nx;i++){const k=j*nx+i;p[3*k]=x[i];p[3*k+1]=y[j];p[3*k+2]=finite(r[j][i])?-r[j][i]*depthEx:-2}for(let j=0;j<ny-1;j++)for(let i=0;i<nx-1;i++){const q=[r[j][i],r[j][i+1],r[j+1][i],r[j+1][i+1]];if(q.every(finite)){const a=j*nx+i,b=a+1,c=a+nx,d=c+1;ind.push(a,c,b,b,c,d)}}const tg=new THREE.BufferGeometry();tg.setAttribute('position',new THREE.BufferAttribute(p,3));tg.setIndex(ind);tg.computeVertexNormals();terrainG.add(new THREE.Mesh(tg,new THREE.MeshStandardMaterial({color:0x8a6848,roughness:.98,side:THREE.DoubleSide})));const w=new THREE.Mesh(new THREE.PlaneGeometry(maxX-minX,maxY-minY),new THREE.MeshBasicMaterial({color:0x168bd1,transparent:true,opacity:.25,side:THREE.DoubleSide,depthWrite:false}));w.position.set(fit.cx,fit.cy,.5);w.renderOrder=2;waterG.add(w);const lm=new THREE.MeshStandardMaterial({color:0x3f9a55,roughness:.95,side:THREE.DoubleSide});for(const p of[...(geo.land?.polygons||[]),...(geo.islands?.polygons||[])]){if(!p.vertices?.length||!p.triangles?.length)continue;const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p.vertices.flatMap(q=>[q[0],q[1],9]),3));g.setIndex(p.triangles.flat());g.computeVertexNormals();const m=new THREE.Mesh(g,lm);m.renderOrder=50;landG.add(m)}const cm=new THREE.LineBasicMaterial({color:0x193f46,depthTest:false}),em=new THREE.LineBasicMaterial({color:0xb47f18,depthTest:false});for(const a of geo.coast||[])coastG.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(a.map(q=>new THREE.Vector3(q[0],q[1],11))),cm));for(const a of geo.eez||[])eezG.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(a.map(q=>new THREE.Vector3(q[0],q[1],10))),em));fitCamera()}
function scaleDepth(){depthEx=+$('exaggeration').value;$('exagValue').textContent=`${depthEx}×`;const a=terrainG.children[0]?.geometry.attributes.position;if(!a)return;const r=geo.terrain.rawDepthKm,nx=geo.terrain.x.length,ny=geo.terrain.y.length;for(let j=0;j<ny;j++)for(let i=0;i<nx;i++)a.setZ(j*nx+i,finite(r[j][i])?-r[j][i]*depthEx:-2);a.needsUpdate=true;terrainG.children[0].geometry.computeVertexNormals();renderCached();if(current?.id==='currents')currents()}
function vars(){const box=$('vars');box.innerHTML='';for(const [id,label,u,ico] of defs){const c=id==='hazard'?null:catalog.find(x=>x.id===id),b=document.createElement('button');b.className=`var ${c?.available?'':'off'} ${current?.id===id?'active':''}`;b.innerHTML=`<i class="ico">${ico}</i><span><strong>${label}</strong><span>${c?.available?(c.units||u):'No matching dataset'}</span></span><i class="dot ${c?.available?'':'off'}"></i>`;if(c?.available)b.onclick=()=>select(c);box.appendChild(b)}}
function status(s,type='ok'){$('status').textContent=s;$('statusDot').className=`statusdot ${type==='error'?'error':type==='busy'?'busy':''}`}
async function meta(c){depths=[];$('depth').max=0;$('depth').value=0;if(!c?.available)return;try{const m=await get(`${API}/metadata/${encodeURIComponent(c.file)}`);depths=(m.coordinates?.depth?.values||[]).filter(finite);$('depth').max=Math.max(0,depths.length-1);$('depthInfo').textContent=depths.length?`${depths.length} measured layers · 5 layers visible around selected depth.`:'Surface variable — no depth coordinate.'}catch(e){status(`Metadata unavailable: ${e.message}`,'error')}}
function selectedDepth(){return depths.length?depths[+$('depth').value||0]:null}function layerIndices(){if(!depths.length)return[0];const c=+$('depth').value||0,n=Math.min(5,depths.length),start=Math.max(0,Math.min(depths.length-n,c-Math.floor(n/2)));return Array.from({length:n},(_,i)=>start+i)}
function key(d){return `${current?.id}|${+$('time').value||0}|${d??'surface'}`}
async function fetchLayer(d){const k=key(d);if(cache.has(k))return cache.get(k);const q=new URLSearchParams({file:current.file,variable:current.variable,stride:'3'}),ti=+$('time').value||0;if(times.length){q.set('time_start',iso(times[ti]));q.set('time_end',iso(times[ti]))}if(d!=null){q.set('depth_min',d);q.set('depth_max',d)}const data=await get(`${API}/data/region/array?${q}`);cache.set(k,data);return data}
async function select(c){current=c;cache.clear();vars();clear(fieldG);stopCurrentAnimation();clear(currentG);if(waterG.children[0])waterG.children[0].visible=true;await meta(c);if(c.id==='currents'){await currents();return}const p=palettes[c.id]||palettes.neutral;$('legend').className=`legend ${p.cls}`;$('units').textContent=`${c.label}${c.units?' · '+c.units:''}`;await loadLayers()}
async function loadLayers(){if(!current?.available||current.id==='currents')return;const t=++token;status('Loading measured layers…','busy');try{const inds=layerIndices(),ds=await Promise.all(inds.map(i=>fetchLayer(depths.length?depths[i]:null)));if(t!==token)return;drawLayers(ds,inds);status(`${ds.length} adaptive measured layer${ds.length>1?'s':''} · ${date(times[+$('time').value||0])}`)}catch(e){if(t===token)status(`Field unavailable: ${e.message}`,'error')}}
function drawLayers(ds,inds){clear(fieldG);let all=[];for(const d of ds){const s=stats(d.data||[]);if(s.a.length)all.push(...s.a)}all.sort((a,b)=>a-b);if(!all.length){status('Field contains no finite numeric values','error');return}let lo=quantile(all,.01),hi=quantile(all,.99);if(!finite(lo)||!finite(hi)||lo===hi){lo=all[0];hi=all.at(-1)||lo+1}if(current.id==='temperature_anomaly'){const a=Math.max(Math.abs(lo),Math.abs(hi));lo=-a;hi=a}for(let n=0;n<ds.length;n++)drawField(ds[n],inds[n],lo,hi,n);$('legendMin').textContent=fmt(lo);$('legendMax').textContent=fmt(hi);if(waterG.children[0])waterG.children[0].visible=false}
function drawField(d,di,lo,hi,n){const lat=d.coordinates?.latitude||d.coordinates?.lat||[],lon=d.coordinates?.longitude||d.coordinates?.lon||[];if(lat.length<2||lon.length<2)return;const vals=flat(d.data||[]).map(Number),nx=lon.length,ny=lat.length;if(vals.length<nx*ny){status(`Field shape mismatch: ${vals.length} values for ${nx}×${ny}`,'error');return}const z=-(+(depths[di]??0))*depthEx/1000+4,p=[],c=[],ix=[];let vi=0;for(let j=0;j<ny-1;j++)for(let i=0;i<nx-1;i++){const a=vals[j*nx+i],b=vals[j*nx+i+1],cc=vals[(j+1)*nx+i],dd=vals[(j+1)*nx+i+1];if(![a,b,cc,dd].every(finite))continue;const base=vi;p.push(...xy(lon[i],lat[j],z),...xy(lon[i+1],lat[j],z),...xy(lon[i],lat[j+1],z),...xy(lon[i+1],lat[j+1],z));for(const q of[a,b,cc,dd]){const co=col(current.id,(q-lo)/(hi-lo||1));c.push(co.r,co.g,co.b)}ix.push(base,base+2,base+1,base+1,base+2,base+3);vi+=4}if(!p.length)return;const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setAttribute('color',new THREE.Float32BufferAttribute(c,3));g.setIndex(ix);const m=new THREE.MeshBasicMaterial({vertexColors:true,transparent:true,opacity:n===0?.97:.82,side:THREE.DoubleSide,depthTest:false,depthWrite:false});const mesh=new THREE.Mesh(g,m);mesh.renderOrder=20+n;fieldG.add(mesh)}
function renderCached(){if(!current||current.id==='currents')return;const inds=layerIndices(),ds=inds.map(i=>cache.get(key(depths.length?depths[i]:null))).filter(Boolean);if(ds.length)drawLayers(ds,inds)}
function stopCurrentAnimation(){if(currentAnim){cancelAnimationFrame(currentAnim);currentAnim=null}currentItems=[]}
function makeArrow(x,y,z,dx,dy,len,speed){const dir=new THREE.Vector3(dx,dy,0).normalize(),tip=new THREE.Vector3(x+dir.x*len,y+dir.y*len,z),base=new THREE.Vector3(x,y,z);const shaftMat=new THREE.LineBasicMaterial({color:0x003bff,depthTest:false,depthWrite:false});const shaft=new THREE.Line(new THREE.BufferGeometry().setFromPoints([base,tip]),shaftMat);shaft.renderOrder=200;currentG.add(shaft);const cone=new THREE.Mesh(new THREE.ConeGeometry(Math.max(1.8,Math.min(4,len*.18)),Math.max(5,len*.32),6),new THREE.MeshBasicMaterial({color:0x00eaff,depthTest:false,depthWrite:false}));cone.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),dir);cone.position.copy(tip);cone.renderOrder=201;currentG.add(cone);currentItems.push({shaft,cone,x,y,z,dir,len,phase:Math.random(),speed});}
async function currents(){clear(currentG);stopCurrentAnimation();status('Loading current vectors…','busy');const q=new URLSearchParams({stride:'5'});if(times.length)q.set('time',iso(times[+$('time').value||0]));if(selectedDepth()!=null)q.set('depth',selectedDepth());try{const d=await get(`${API}/ocean/current-grid?${q}`),la=d.latitude||[],lo=d.longitude||[],u=d.u||[],v=d.v||[];const mags=[];for(let j=0;j<la.length;j++)for(let i=0;i<lo.length;i++){const a=+u[j]?.[i],b=+v[j]?.[i];if(finite(a)&&finite(b))mags.push(Math.hypot(a,b))}mags.sort((a,b)=>a-b);const p95=quantile(mags,.95)||Math.max(...mags,1),z=-(+(selectedDepth()||0))*depthEx/1000+8;for(let j=0;j<la.length;j++)for(let i=0;i<lo.length;i++){const a=+u[j]?.[i],b=+v[j]?.[i];if(!finite(a)||!finite(b))continue;const m=Math.hypot(a,b);if(m<Math.max(1e-7,p95*.01))continue;const dir=Math.atan2(b,a),[x,y]=xy(lo[i],la[j],z),len=18+Math.min(70,(m/(p95||1))*70);makeArrow(x,y,z,Math.cos(dir),Math.sin(dir),len,m)}if(waterG.children[0])waterG.children[0].visible=false;$('legendMin').textContent='0';$('legendMax').textContent=fmt(p95);$('units').textContent='Current vectors · moving arrowheads · direction + speed';status(`Current flow · ${currentItems.length} vectors · adaptive speed scale · ${date(times[+$('time').value||0])}`);animateCurrents(performance.now())}catch(e){status(`Current data unavailable: ${e.message}`,'error')}}
function animateCurrents(now){if(!currentItems.length)return;for(const a of currentItems){const f=(now/1300*a.speed/(Math.max(a.speed,.0001))+a.phase)%1;const d=f*a.len;a.cone.position.set(a.x+a.dir.x*d,a.y+a.dir.y*d,a.z);a.cone.material.opacity=.65+.35*Math.sin(f*Math.PI);a.cone.material.transparent=true}currentAnim=requestAnimationFrame(animateCurrents)}
function timeline(){const t=$('time');t.max=Math.max(0,times.length-1);t.value=0;$('timeStart').textContent=date(times[0]);$('timeEnd').textContent=date(times.at(-1));timeUI();const s=$('timelineScale');s.innerHTML='';const n=Math.min(8,times.length);for(let i=0;i<n;i++){const k=n===1?0:Math.round(i*(times.length-1)/(n-1)),e=document.createElement('span');e.className='tick';e.style.left=`${n===1?0:k/(times.length-1)*100}%`;e.textContent=date(times[k]);s.appendChild(e)}}
function timeUI(){$('timeCurrent').textContent=date(times[+$('time').value||0]);$('timeIndex').textContent=times.length?`${+$('time').value+1}/${times.length}`:'—'}
async function timeChange(){timeUI();cache.clear();token++;if(current?.id==='currents')await currents();else if(current?.available)await loadLayers()}
async function depthChange(){const d=selectedDepth();$('depthValue').textContent=d==null?'Surface':`${fmt(d)} m`;$('depthBadge').textContent=d==null?'Surface':`Depth ${fmt(d)} m`;token++;if(current?.id==='currents')await currents();else if(current?.available)await loadLayers()}
function view(v){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));const d=Math.max(600,fit.size*1.6);if(v==='top')camera.position.set(fit.cx,fit.cy,d);else if(v==='profile')camera.position.set(fit.cx,fit.cy-d*.95,80);else if(v==='under')camera.position.set(fit.cx,fit.cy,-d*.62);else fitCamera();controls.target.set(fit.cx,fit.cy,v==='under'?-80:-Math.min(100,fit.size*.05));controls.update()}
async function point(e){if(e.target!==renderer.domElement)return;const r=renderer.domElement.getBoundingClientRect(),m=new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(m,camera);const hit=ray.intersectObjects([fieldG,currentG,waterG],true)[0];if(!hit)return;const b=geo.bounds,lat0=(b[2]+b[3])/2,lon0=(b[0]+b[1])/2,p=hit.point,lat=lat0+(p.y-fit.cy)/111.32,lon=lon0+(p.x-fit.cx)/(111.32*Math.cos(lat0*Math.PI/180));try{const q=new URLSearchParams({latitude:lat,longitude:lon});if(times.length)q.set('time',iso(times[+$('time').value||0]));if(selectedDepth()!=null)q.set('depth',selectedDepth());const d=await get(`${API}/ocean/point?${q}`);$('coords').textContent=`${lat.toFixed(3)}°, ${lon.toFixed(3)}°`;$('readoutGrid').innerHTML='';for(const x of d.values||[]){if(!x.available)continue;let v=x.value;if(v&&typeof v==='object')v=Object.entries(v).map(([k,z])=>`${k}: ${fmt(+z)}`).join(' · ');else v=fmt(+v);const el=document.createElement('div');el.className='rval';el.innerHTML=`<b>${x.label}</b><span>${v}${x.units?' '+x.units:''}</span>`;$('readoutGrid').appendChild(el)}$('readoutTime').textContent=`${date(times[+$('time').value||0])} · nearest measured point · depth ${selectedDepth()==null?'surface':fmt(selectedDepth())+' m'}`;$('readout').style.display='block'}catch(e){status(`Point lookup failed: ${e.message}`,'error')}}
$('closeReadout').onclick=()=>$('readout').style.display='none';$('time').oninput=timeChange;$('depth').oninput=depthChange;$('exaggeration').oninput=scaleDepth;$('reset').onclick=()=>view('3d');$('fullscreen').onclick=()=>document.documentElement.requestFullscreen?.();document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));renderer.domElement.addEventListener('click',point);$('play').onclick=()=>{playing=!playing;$('play').textContent=playing?'PAUSE':'PLAY';lastPlay=performance.now()};
async function init(){try{geo=await get('/geometry.json');buildOcean();const c=await get(`${API}/ocean/catalog`);catalog=c.variables||[];vars();const t=await get(`${API}/ocean/time`);times=t.values||[];timeline();$('loading').style.display='none';status(`${catalog.filter(x=>x.available).length} datasets available`);const first=catalog.find(x=>x.available&&x.id==='temperature')||catalog.find(x=>x.available);if(first)await select(first);view('3d')}catch(e){$('loading').innerHTML=`<div class="load"><b>SOLVX</b><div>Unable to initialise: ${e.message}</div></div>`;status(e.message,'error')}}
function animate(now){requestAnimationFrame(animate);if(playing&&times.length&&now-lastPlay>900){$('time').value=(+$('time').value+1)%times.length;timeChange();lastPlay=now}controls.update();renderer.render(scene,camera)}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});init();animate(performance.now());