(()=>{
'use strict';
const $=id=>document.getElementById(id),finite=v=>Number.isFinite(Number(v));
const API=`${location.protocol==='file:'?'http:':location.protocol}//${location.hostname||'127.0.0.1'}:8000`;
const LABEL={temperature:'Temperature',temperature_anomaly:'SST anomaly',salinity:'Salinity',currents:'Currents',sea_level:'Sea level',chlorophyll:'Chlorophyll'};
const PAL={temperature:[[0x071b8f,0],[0x075cff,.15],[0x00c6ff,.32],[0x00e79a,.48],[0xfff000,.62],[0xff6b00,.80],[0xb40000,1]],temperature_anomaly:[[0x06349e,0],[0x4b9fe8,.25],[0xffffff,.5],[0xffa060,.75],[0xb60018,1]],salinity:[[0x071d9b,0],[0x00a6ff,.20],[0x00d49a,.42],[0xb8e52e,.68],[0xffe600,1]],sea_level:[[0x102caa,0],[0x00a9ff,.25],[0x26d08b,.50],[0xffd21a,.75],[0xd40000,1]],chlorophyll:[[0xf7fff0,0],[0xb7ef59,.20],[0x42c83e,.45],[0x078d38,.72],[0x003d20,1]],fallback:[[0x071b8f,0],[0x00cfff,.25],[0xfff000,.5],[0xff6a00,.75],[0xb40000,1]]};
const S={engine:null,scene:null,camera:null,geo:null,terrain:null,seabed:null,surface:null,land:[],field:null,volume:null,volumeMat:null,volumeTex:null,bathyTex:null,paletteTex:null,currentLines:[],catalog:[],times:[],ti:0,active:'temperature',request:0,depthMode:'volume',sliceDepth:0,sliceIndex:0,depthEx:10,range:null,descriptor:null,bathyMaxM:1000};
const get=async path=>{const r=await fetch(API+path,{cache:'no-store'});if(!r.ok){let t='';try{t=await r.text()}catch{}throw Error(`${r.status} ${t||r.statusText}`)}return r.json()};
const local=async path=>{const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw Error(`${r.status} ${r.statusText}`);return r.json()};
const flat=v=>{const o=[];(function f(x){Array.isArray(x)?x.forEach(f):o.push(x)})(v);return o};
const nums=v=>flat(v).map(Number).filter(Number.isFinite),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const quantile=(a,p)=>{if(!a.length)return null;const x=(a.length-1)*p,i=Math.floor(x),j=Math.ceil(x);return a[i]+(a[j]-a[i])*(x-i)};
const iso=v=>{const d=new Date(v);return isNaN(d)?String(v||''):d.toISOString()},date=v=>{const d=new Date(v);return isNaN(d)?String(v||'—'):d.toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'})};
function status(t,type='ok'){$('status').textContent=t;$('statusDot').className=type==='error'?'error':type==='busy'?'busy':''}
function fail(e){console.error(e);$('loading').classList.add('hidden');$('fatalText').textContent=e?.message||String(e);$('fatal').classList.add('show');status(`Viewer failed · ${e?.message||e}`,'error')}
function bounds(){return [S.terrain.x[0],S.terrain.x.at(-1),S.terrain.y[0],S.terrain.y.at(-1)]}
function depthY(m){return -(Number(m)||0)*S.depthEx*8/1000}
function mesh(name,pos,ind,mat,meta={}){const m=new BABYLON.Mesh(name,S.scene),v=new BABYLON.VertexData();v.positions=pos;v.indices=ind;v.applyToMesh(m,true);m.material=mat;m.metadata={solvx:true,...meta};return m}
function mat(name,r,g,b,em=0){const m=new BABYLON.StandardMaterial(name,S.scene);m.diffuseColor=new BABYLON.Color3(r,g,b);m.emissiveColor=new BABYLON.Color3(r*em,g*em,b*em);m.specularColor=BABYLON.Color3.Black();m.backFaceCulling=false;return m}
function buildBase(){
 const t=S.terrain,x=t.x,z=t.y,d=t.rawDepthKm,nx=x.length,nz=z.length,p=[],ind=[];
 for(let j=0;j<nz;j++)for(let i=0;i<nx;i++){const v=d[j]?.[i];p.push(x[i],finite(v)?-v*S.depthEx*8:-3,z[j])}
 for(let j=0;j<nz-1;j++)for(let i=0;i<nx-1;i++){const q=[d[j]?.[i],d[j]?.[i+1],d[j+1]?.[i],d[j+1]?.[i+1]];if(q.every(finite)){const a=j*nx+i,b=a+1,c=a+nx,e=c+1;ind.push(a,c,b,b,c,e)}}
 S.seabed=mesh('GEBCO seabed',p,ind,mat('seabed',.28,.16,.07,.03),{seabed:true});
 const sp=[],si=[],map=new Map();for(let j=0;j<nz;j++)for(let i=0;i<nx;i++)if(finite(d[j]?.[i])){map.set(`${j}:${i}`,sp.length/3);sp.push(x[i],0,z[j])}for(let j=0;j<nz-1;j++)for(let i=0;i<nx-1;i++){const a=map.get(`${j}:${i}`),b=map.get(`${j}:${i+1}`),c=map.get(`${j+1}:${i}`),e=map.get(`${j+1}:${i+1}`);if([a,b,c,e].every(v=>v!==undefined))si.push(a,c,b,b,c,e)}const sm=mat('surface',.01,.09,.34,.02);sm.useVertexColors=true;sm.alpha=.88;S.surface=mesh('Ocean surface',sp,si,sm,{waterSurface:true});
 const lm=mat('land',.045,.20,.055,.01);let n=0;for(const group of [t.land||[],t.islands||[]])for(const poly of group){if(!poly?.vertices?.length||!poly?.triangles?.length)continue;const q=poly.vertices,L=q.length,pp=[];for(const a of q)pp.push(+a[0],3,+a[1]);for(const a of q)pp.push(+a[0],-3,+a[1]);const ii=[];for(const a of poly.triangles)if(a.length>=3){const A=+a[0],B=+a[1],C=+a[2];ii.push(A,C,B,A+L,B+L,C+L)}const ring=poly.top||[];for(let i=0;i<ring.length-1;i++){let A=-1,B=-1,da=1e9,db=1e9;for(let k=0;k<L;k++){const aa=Math.hypot(q[k][0]-ring[i][0],q[k][1]-ring[i][1]),bb=Math.hypot(q[k][0]-ring[i+1][0],q[k][1]-ring[i+1][1]);if(aa<da){da=aa;A=k}if(bb<db){db=bb;B=k}}if(A>=0&&B>=0)ii.push(A,B,A+L,B,B+L,A+L)}if(ii.length)S.land.push(mesh(`Land ${n++}`,pp,ii,lm,{land:true}))}
 for(const [name,parts,y,c] of [['coast',t.coast,3.35,new BABYLON.Color3(.02,.08,.02)],['eez',t.eez,3.2,new BABYLON.Color3(.95,.55,.04)]])for(let i=0;i<(parts||[]).length;i++){const a=parts[i];if(!a?.length)continue;const l=BABYLON.MeshBuilder.CreateLines(`${name}-${i}`,{points:a.map(v=>new BABYLON.Vector3(+v[0],y,+v[1]))},S.scene);l.color=c;l.metadata={solvx:true,overlay:true}}
 buildBathyTexture();
}
function buildBathyTexture(){const d=S.terrain.rawDepthKm,nx=S.terrain.x.length,nz=S.terrain.y.length,vals=nums(d);S.bathyMaxM=Math.max(...vals,1)*1000;const a=new Uint8Array(nx*nz*4),max=S.bathyMaxM/1000;for(let j=0;j<nz;j++)for(let i=0;i<nx;i++){const v=d[j]?.[i],k=(j*nx+i)*4,q=finite(v)?clamp(v/max,0,1):0;a[k]=a[k+1]=a[k+2]=Math.round(q*255);a[k+3]=finite(v)?255:0}S.bathyTex=new BABYLON.RawTexture(a,nx,nz,BABYLON.Engine.TEXTUREFORMAT_RGBA,S.scene,false,false,BABYLON.Texture.BILINEAR_SAMPLINGMODE);S.bathyTex.wrapU=S.bathyTex.wrapV=BABYLON.Texture.CLAMP_ADDRESSMODE}
function descriptor(f){const dims=f.dimensions||[],shape=f.shape||[],c=f.coordinates||{},latName=dims.find(x=>x==='latitude'||x==='lat'),lonName=dims.find(x=>x==='longitude'||x==='lon'),depthName=dims.find(x=>['depth','deptht','depthu','depthv','depthw','lev','level','z'].includes(x));if(!latName||!lonName)throw Error('Backend field has no latitude/longitude dimensions');const coord=n=>Array.from(c[n]||[]).map(Number);return{dims,shape,latName,lonName,depthName,lat:coord(latName),lon:coord(lonName),depth:depthName?coord(depthName):[]}}
function strides(s){const r=new Array(s.length),v={n:1};for(let i=s.length-1;i>=0;i--){r[i]=v.n;v.n*=s[i]}return r}
function normalize(f){const d=descriptor(f),st=strides(d.shape),raw=flat(f.data||[]).map(Number),la=[...d.lat].sort((a,b)=>a-b),lo=[...d.lon].sort((a,b)=>a-b),de=[...d.depth].sort((a,b)=>a-b),w=lo.length,h=la.length,z=Math.max(1,de.length),out=new Float32Array(w*h*z),valid=[];const index=(xi,yi,zi)=>{const ix=new Array(d.shape.length).fill(0);for(let k=0;k<d.dims.length;k++){const n=d.dims[k];if(n===d.lonName)ix[k]=xi;if(n===d.latName)ix[k]=yi;if(d.depthName&&n===d.depthName)ix[k]=zi}let p=0;for(let k=0;k<ix.length;k++)p+=ix[k]*st[k];return Number(raw[p])};let p=0;for(let zi=0;zi<z;zi++)for(let yi=0;yi<h;yi++)for(let xi=0;xi<w;xi++){const v=index(d.lon.indexOf(lo[xi]),d.lat.indexOf(la[yi]),z>1?d.depth.indexOf(de[zi]):0);out[p++]=finite(v)?v:NaN;if(finite(v))valid.push(v)}return{width:w,height:h,depth:z,lat:la,lon:lo,levels:de,values:out,valid,depthDependent:z>1}}
function range(values,id){const a=values.filter(finite).sort((a,b)=>a-b);if(!a.length)throw Error('No finite values returned');let lo=quantile(a,.01),hi=quantile(a,.99);if(id==='temperature_anomaly'){const m=Math.max(Math.abs(lo),Math.abs(hi));lo=-m;hi=m}if(!(hi>lo)){const p=Math.max(Math.abs(lo)*.02,1e-6);lo-=p;hi+=p}return{lo,hi}}
function paletteTexture(id){const stops=PAL[id]||PAL.fallback,a=new Uint8Array(256*4);for(let i=0;i<256;i++){const q=i/255;let A=stops[0],B=stops.at(-1);for(let j=0;j<stops.length-1;j++)if(q<=stops[j+1][1]){A=stops[j];B=stops[j+1];break}const t=(q-A[1])/(B[1]-A[1]||1),ca=A[0],cb=B[0],k=i*4;a[k]=((ca>>16)&255)+(((cb>>16)&255)-((ca>>16)&255))*t;a[k+1]=((ca>>8)&255)+(((cb>>8)&255)-((ca>>8)&255))*t;a[k+2]=(ca&255)+((cb&255)-(ca&255))*t;a[k+3]=255}S.paletteTex?.dispose();S.paletteTex=new BABYLON.RawTexture(a,256,1,BABYLON.Engine.TEXTUREFORMAT_RGBA,S.scene,false,false,BABYLON.Texture.BILINEAR_SAMPLINGMODE)}
function cpuColor(q){const s=PAL[S.active]||PAL.fallback;let A=s[0],B=s.at(-1);for(let i=0;i<s.length-1;i++)if(q<=s[i+1][1]){A=s[i];B=s[i+1];break}const t=(q-A[1])/(B[1]-A[1]||1),ca=A[0],cb=B[0];return[(((ca>>16)&255)+(((cb>>16)&255)-((ca>>16)&255))*t)/255,(((ca>>8)&255)+(((cb>>8)&255)-((ca>>8)&255))*t)/255,((ca&255)+((cb&255)-(ca&255))*t)/255]}
function fieldMesh(data,zi=0){const [minX,maxX,minZ,maxZ]=bounds(),loX=data.lon[0],hiX=data.lon.at(-1),loZ=data.lat[0],hiZ=data.lat.at(-1),p=[],c=[],ind=[],map=new Map(),w=data.width,h=data.height;for(let j=0;j<h;j++)for(let i=0;i<w;i++){const v=data.values[zi*w*h+j*w+i];if(!finite(v))continue;const id=p.length/3;map.set(`${j}:${i}`,id);p.push(minX+(data.lon[i]-loX)/(hiX-loX||1)*(maxX-minX),depthY(data.levels[zi]||0)+.8,minZ+(data.lat[j]-loZ)/(hiZ-loZ||1)*(maxZ-minZ));const q=clamp((v-S.range.lo)/(S.range.hi-S.range.lo),0,1);c.push(...cpuColor(q),1)}for(let j=0;j<h-1;j++)for(let i=0;i<w-1;i++){const a=map.get(`${j}:${i}`),b=map.get(`${j}:${i+1}`),d=map.get(`${j+1}:${i}`),e=map.get(`${j+1}:${i+1}`);if([a,b,d,e].every(v=>v!==undefined))ind.push(a,d,b,b,d,e)}const m=mesh('Measured depth slice',p,ind,mat('field',1,1,1,.12),{fieldSurface:true});m.material.useVertexColors=true;m.material.alpha=.94;m.setVerticesData(BABYLON.VertexBuffer.ColorKind,c,true);return m}
function shader(){BABYLON.Effect.ShadersStore.solvxVolVertex=`precision highp float;attribute vec3 position;uniform mat4 worldViewProjection;uniform mat4 world;varying vec3 vWorld;void main(){vWorld=(world*vec4(position,1.0)).xyz;gl_Position=worldViewProjection*vec4(position,1.0);}`;BABYLON.Effect.ShadersStore.solvxVolFragment=`precision highp float;varying vec3 vWorld;uniform vec3 cameraPosition;uniform mat4 invWorld;uniform sampler3D volumeTex;uniform sampler2D bathyTex;uniform sampler2D paletteTex;uniform vec2 fieldRange;uniform float opacity;uniform float sliceDepth;uniform float sliceThickness;uniform float sliceMode;uniform vec3 boxMin;uniform vec3 boxMax;vec2 boxHit(vec3 ro,vec3 rd){vec3 inv=1.0/rd;vec3 a=(boxMin-ro)*inv,b=(boxMax-ro)*inv,lo=min(a,b),hi=max(a,b);return vec2(max(max(lo.x,lo.y),lo.z),min(min(hi.x,hi.y),hi.z));}void main(){vec3 ro=(invWorld*vec4(cameraPosition,1.0)).xyz;vec3 rd=normalize((invWorld*vec4(vWorld,1.0)).xyz-ro);vec2 hit=boxHit(ro,rd);if(hit.y<=max(hit.x,0.0))discard;float t=max(hit.x,0.0),end=hit.y,stepLen=(end-t)/96.0;vec4 acc=vec4(0.0);for(int i=0;i<128;i++){if(t>end||acc.a>.97)break;vec3 p=ro+rd*t,uvw=p+.5;if(all(greaterThanEqual(uvw,vec3(0.0)))&&all(lessThanEqual(uvw,vec3(1.0)))){float depth=1.0-uvw.y,bottom=texture2D(bathyTex,uvw.xz).r;if(depth<=bottom+.015&&(sliceMode<.5||abs(depth-sliceDepth)<sliceThickness)){vec4 s=texture(volumeTex,vec3(uvw.x,uvw.z,depth));float q=clamp((s.r-fieldRange.x)/(fieldRange.y-fieldRange.x),0.0,1.0);vec3 col=texture2D(paletteTex,vec2(q,.5)).rgb;float a=s.a*opacity*(sliceMode>.5?3.0:1.0);acc.rgb+=(1.0-acc.a)*col*a;acc.a+=(1.0-acc.a)*a;}}t+=stepLen;}if(acc.a<.01)discard;gl_FragColor=acc;}`}
function createVolume(data){if(!BABYLON.RawTexture3D||!S.engine.getCaps().support3DTextures)return false;const w=data.width,h=data.height,z=data.depth,raw=new Uint8Array(w*h*z*4);for(let i=0;i<data.values.length;i++){const v=data.values[i],k=i*4,q=finite(v)?clamp((v-S.range.lo)/(S.range.hi-S.range.lo),0,1):0;raw[k]=Math.round(q*255);raw[k+1]=raw[k+2]=0;raw[k+3]=finite(v)?255:0}shader();S.volumeTex=new BABYLON.RawTexture3D(raw,w,h,z,BABYLON.Engine.TEXTUREFORMAT_RGBA,S.scene,false,false,BABYLON.Texture.TRILINEAR_SAMPLINGMODE);S.volumeTex.wrapU=S.volumeTex.wrapV=S.volumeTex.wrapR=BABYLON.Texture.CLAMP_ADDRESSMODE;const maxDepth=data.levels.at(-1)||S.bathyMaxM,bb=bounds(),box=BABYLON.MeshBuilder.CreateBox('Measured 3D volume',{width:bb[1]-bb[0],height:-depthY(maxDepth),depth:bb[3]-bb[2]},S.scene);box.position.set((bb[0]+bb[1])/2,depthY(maxDepth)/2,(bb[2]+bb[3])/2);const m=new BABYLON.ShaderMaterial('3D volume',S.scene,{vertex:'solvxVol',fragment:'solvxVol'},{attributes:['position'],uniforms:['world','worldViewProjection','cameraPosition','invWorld','fieldRange','opacity','sliceDepth','sliceThickness','sliceMode','boxMin','boxMax'],samplers:['volumeTex','bathyTex','paletteTex'],needAlphaBlending:true,needAlphaTesting:false});m.backFaceCulling=true;m.alphaMode=BABYLON.Engine.ALPHA_COMBINE;m.setTexture('volumeTex',S.volumeTex);m.setTexture('bathyTex',S.bathyTex);m.setTexture('paletteTex',S.paletteTex);m.setVector2('fieldRange',new BABYLON.Vector2(S.range.lo,S.range.hi));m.setFloat('opacity',.065);m.setFloat('sliceDepth',S.sliceDepth);m.setFloat('sliceThickness',.018);m.setFloat('sliceMode',S.depthMode==='slice'?1:0);m.setVector3('boxMin',new BABYLON.Vector3(-.5,-.5,-.5));m.setVector3('boxMax',new BABYLON.Vector3(.5,.5,.5));box.material=m;box.metadata={solvx:true,dataVolume:true};S.volume=box;S.volumeMat=m;return true}
function updateVolume(){if(!S.volumeMat)return;S.volumeMat.setMatrix('invWorld',S.volume.getWorldMatrix().clone().invert());S.volumeMat.setVector3('cameraPosition',S.camera.globalPosition);S.volumeMat.setVector2('fieldRange',new BABYLON.Vector2(S.range.lo,S.range.hi));S.volumeMat.setFloat('sliceDepth',S.descriptor.levels.length?S.sliceDepth/S.descriptor.levels.at(-1):0);S.volumeMat.setFloat('sliceMode',S.depthMode==='slice'?1:0)}
function disposeField(){if(S.field){S.field.dispose(false,true);S.field=null}if(S.volume){S.volume.dispose(false,true);S.volume=null}if(S.volumeTex){S.volumeTex.dispose();S.volumeTex=null}S.volumeMat=null;S.surface?.setEnabled(true)}
async function renderScalar(v){const my=++S.request;status(`Loading ${v.label}…`,'busy');const b=S.geo.bounds,p=new URLSearchParams({file:v.file,variable:v.variable,lat_min:b[2],lat_max:b[3],lon_min:b[0],lon_max:b[1],stride:'2'}),t=S.times[S.ti];if(t){p.set('time_start',iso(t));p.set('time_end',iso(t))}const f=await get(`/data/region/array?${p}`);if(my!==S.request)return;const d=normalize(f);S.descriptor=d;S.range=range(d.valid,S.active);paletteTexture(S.active);disposeField();clearCurrents();$('legend').className=`legend ${S.active==='temperature_anomaly'?'anomaly':S.active==='salinity'?'sal':S.active==='chlorophyll'?'chl':S.active==='sea_level'?'neutral':'temp'}`;$('legendLo').textContent=S.range.lo.toFixed(3);$('legendHi').textContent=S.range.hi.toFixed(3);if(d.depthDependent){$('depthSection').classList.remove('hidden');$('depthSlider').max=Math.max(0,d.levels.length-1);S.sliceIndex=0;S.sliceDepth=d.levels[0]||0;$('depthSlider').value=0;$('depthMax').textContent=`${d.levels.at(-1).toFixed(0)} m`;$('depthValue').textContent='Full water column';const ok=createVolume(d);if(!ok){S.depthMode='slice';document.querySelector('[data-depth-mode="slice"]').click();S.field=fieldMesh(d,0);S.surface.setEnabled(false);status('3D texture unavailable · using single measured depth slice','busy')}}else{$('depthSection').classList.add('hidden');S.field=fieldMesh(d,0);S.surface.setEnabled(false);$('depthBadge').textContent='Surface field'}if(d.depthDependent)$('depthBadge').textContent=`${S.depthMode==='slice'?'Slice':'Volume'} · ${S.sliceDepth.toFixed(1)} m`;status(`${v.label} · real backend data · adaptive 1–99% scaling`)}
async function renderCurrent(){disposeField();clearCurrents();const t=S.times[S.ti],depth=S.sliceDepth||0,r=await get(`/ocean/current-grid?time=${encodeURIComponent(iso(t))}&depth=${encodeURIComponent(depth)}&stride=4`),mags=[];for(let j=0;j<r.latitude.length;j++)for(let i=0;i<r.longitude.length;i++){const u=+r.u?.[j]?.[i],v=+r.v?.[j]?.[i];if(finite(u)&&finite(v))mags.push(Math.hypot(u,v))}mags.sort((a,b)=>a-b);const max=Math.max(quantile(mags,.99)||1e-6,1e-6),bb=bounds();for(let j=0;j<r.latitude.length;j++)for(let i=0;i<r.longitude.length;i++){const u=+r.u?.[j]?.[i],v=+r.v?.[j]?.[i];if(!finite(u)||!finite(v))continue;const mag=Math.hypot(u,v);if(mag<max*.02)continue;const x=bb[0]+(r.longitude[i]-bb[0])/(bb[1]-bb[0])*(bb[1]-bb[0]),z=bb[2]+(r.latitude[j]-bb[2])/(bb[3]-bb[2])*(bb[3]-bb[2]),len=5+Math.min(35,mag/max*35),a=BABYLON.MeshBuilder.CreateLines(`current-${j}-${i}`,{points:[new BABYLON.Vector3(x,4,z),new BABYLON.Vector3(x+u/mag*len,4,z+v/mag*len)]},S.scene);a.color=new BABYLON.Color3(.1,.75,1);a.metadata={solvx:true,current:true};a.isPickable=false;S.currentLines.push(a)}$('legend').className='legend neutral';$('legendLo').textContent='slow';$('legendHi').textContent='fast';$('legendNote').textContent='Arrow length = relative magnitude';$('depthBadge').textContent=`Current · ${depth.toFixed(1)} m`;status('Currents · real u/v vectors · direction + magnitude')}
function clearCurrents(){for(const m of S.currentLines)m.dispose(false,true);S.currentLines=[]}
function vars(){const box=$('vars');box.innerHTML='';for(const id of Object.keys(LABEL)){const v=S.catalog.find(x=>x.id===id),b=document.createElement('button');b.className=`var ${S.active===id?'active':''} ${v?.available?'':'off'}`;b.disabled=!v?.available;b.innerHTML=`<b>${LABEL[id]}</b><small>${v?.available?(v.units||'backend dataset'):'not available'}</small><i></i>`;b.onclick=()=>select(id);box.appendChild(b)}}
async function select(id){S.active=id;vars();const v=S.catalog.find(x=>x.id===id);if(!v?.available){status(`${LABEL[id]} is not available in backend`,'error');return}try{if(id==='currents')await renderCurrent();else await renderScalar(v)}catch(e){console.error(e);S.request++;disposeField();clearCurrents();status(`${LABEL[id]} failed · ${e.message}`,'error')}}
async function inspect(point){const [minX,maxX,minZ,maxZ]=bounds(),q=new URLSearchParams({latitude:String(clamp(point.z,minZ,maxZ)),longitude:String(clamp(point.x,minX,maxX))}),t=S.times[S.ti];if(t)q.set('time',iso(t));try{const d=await get(`/ocean/point?${q}`);$('coords').textContent=`${Number(d.latitude).toFixed(4)}° N · ${Number(d.longitude).toFixed(4)}° E`;$('readoutGrid').innerHTML='';for(const v of d.values||[]){const e=document.createElement('div');e.className='rval';let val='—';if(v.available&&v.value!=null)val=typeof v.value==='object'?Object.entries(v.value).map(([k,x])=>`${k}: ${Number(x).toFixed(3)}`).join('<br>'):typeof v.value==='number'?Number(v.value).toFixed(4):String(v.value);e.innerHTML=`<b>${v.label}</b><span>${val}${v.units?` <small>${v.units}</small>`:''}</span>`;$('readoutGrid').appendChild(e)}$('readoutTime').textContent=d.time?`Dataset time: ${d.time}`:'Dataset time: current selection';$('readout').classList.remove('hidden')}catch(e){status(`Point read failed · ${e.message}`,'error')}}
function setupUI(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');fit(b.dataset.view)});$('reset').onclick=()=>fit('3d');$('fullscreen').onclick=()=>document.documentElement.requestFullscreen?.();$('closeReadout').onclick=()=>$('readout').classList.add('hidden');$('exaggeration').oninput=e=>{$('exagValue').textContent=`${e.target.value}×`;rebuild()};$('timeSlider').oninput=e=>{S.ti=+e.target.value;syncTime();select(S.active)};$('play').onclick=()=>{if(S.timer){clearInterval(S.timer);S.timer=null;$('play').textContent='PLAY'}else{S.timer=setInterval(()=>{S.ti=(S.ti+1)%S.times.length;$('timeSlider').value=S.ti;syncTime();select(S.active)},1400);$('play').textContent='PAUSE'}};document.querySelectorAll('[data-depth-mode]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-depth-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.depthMode=b.dataset.depthMode;if(S.volumeMat)updateVolume();$('depthValue').textContent=S.depthMode==='slice'?`${S.sliceDepth.toFixed(1)} m`:'Full water column';$('depthBadge').textContent=`${S.depthMode==='slice'?'Slice':'Volume'} · ${S.sliceDepth.toFixed(1)} m`;});$('depthSlider').oninput=e=>{if(!S.descriptor?.depth?.length)return;S.sliceIndex=+e.target.value;S.sliceDepth=S.descriptor.levels[S.sliceIndex]||0;$('depthValue').textContent=`${S.sliceDepth.toFixed(1)} m`;if(S.volumeMat)updateVolume();else if(S.active!=='currents'){disposeField();S.field=fieldMesh(S.descriptor,S.sliceIndex);S.surface.setEnabled(false)}};$('renderCanvas').addEventListener('pointerup',e=>{if(e.button!==0)return;const pick=S.scene.pick(S.scene.pointerX,S.scene.pointerY,m=>m?.metadata?.solvx&&!m.metadata.land&&!m.metadata.seabed&&!m.metadata.overlay&&!m.metadata.current);if(pick?.hit&&pick.pickedPoint)inspect(pick.pickedPoint)})}
function fit(mode){const [a,b,c,d]=bounds(),cx=(a+b)/2,cz=(c+d)/2,size=Math.max(b-a,d-c),dep=depthY(S.bathyMaxM);if(mode==='top'){S.camera.target.set(cx,0,cz);S.camera.alpha=-Math.PI/2;S.camera.beta=.08;S.camera.radius=size*1.2}else if(mode==='profile'){S.camera.target.set(cx,dep*.45,cz);S.camera.alpha=0;S.camera.beta=1.25;S.camera.radius=size*1.15}else if(mode==='under'){S.camera.target.set(cx,dep*.55,cz);S.camera.alpha=.55;S.camera.beta=2.1;S.camera.radius=size}else{S.camera.target.set(cx,dep*.08,cz);S.camera.alpha=-.78;S.camera.beta=.88;S.camera.radius=size*1.15}}
function rebuild(){S.depthEx=+$('exaggeration').value;const old=S.active;S.scene.meshes.slice().filter(m=>m.metadata?.solvx).forEach(m=>m.dispose(false,true));S.seabed=S.surface=null;S.land=[];buildBase();fit('3d');if(old)select(old)}
function syncTime(){const t=S.times[S.ti];$('timeValue').textContent=date(t);$('timeRaw').textContent=iso(t);$('timeCount').textContent=`${S.ti+1}/${S.times.length}`;window.__SOLVX_TIME__=()=>iso(S.times[S.ti])}
async function init(){try{status('Starting unified WebGL renderer','busy');const canvas=$('renderCanvas');S.engine=new BABYLON.Engine(canvas,true,{stencil:true,preserveDrawingBuffer:false},true);if(!S.engine.getCaps().support3DTextures)console.warn('WebGL 3D textures unavailable; slice fallback enabled');S.scene=new BABYLON.Scene(S.engine);S.scene.clearColor=new BABYLON.Color4(.86,.91,.95,1);S.camera=new BABYLON.ArcRotateCamera('camera',-.78,.88,1500,BABYLON.Vector3.Zero(),S.scene);S.camera.attachControl(canvas,true);S.camera.lowerRadiusLimit=20;S.camera.upperRadiusLimit=15000;S.camera.wheelPrecision=2;S.camera.panningSensibility=90;const h=new BABYLON.HemisphericLight('hemi',new BABYLON.Vector3(0,1,0),S.scene);h.intensity=1.2;const sun=new BABYLON.DirectionalLight('sun',new BABYLON.Vector3(-.4,-1,-.3),S.scene);sun.intensity=1.5;S.geo=await local('geometry.json?'+Date.now());S.terrain=S.geo.terrain;if(!S.terrain?.x?.length)throw Error('Invalid geometry.json terrain');S.geo.bounds=[S.terrain.x[0],S.terrain.x.at(-1),S.terrain.y[0],S.terrain.y.at(-1)];buildBase();fit('3d');setupUI();const cat=await get('/ocean/catalog');S.catalog=cat.variables||[];vars();const tm=await get('/ocean/time');S.times=tm.values||[];if(S.times.length){$('timeSlider').max=S.times.length-1;syncTime()}const first=S.catalog.find(v=>v.id==='temperature'&&v.available)||S.catalog.find(v=>v.available);if(first)await select(first.id);else status('No backend datasets detected','error');S.engine.runRenderLoop(()=>{if(S.volumeMat)updateVolume();S.scene.render()});addEventListener('resize',()=>S.engine.resize());$('loading').classList.add('hidden')}catch(e){fail(e)}}
init();
})();
