import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

const $ = id => document.getElementById(id);
const finite = v => Number.isFinite(Number(v));
const clamp = (v,a,b) => Math.max(a, Math.min(b,v));
const flat = v => { const out=[]; (function walk(x){Array.isArray(x)?x.forEach(walk):out.push(x)})(v); return out; };
const API = `${location.protocol === 'file:' ? 'http:' : location.protocol}//${location.hostname || '127.0.0.1'}:8000`;
const LABEL = {temperature:'Temperature',temperature_anomaly:'SST anomaly',salinity:'Salinity',currents:'Currents',sea_level:'Sea level',chlorophyll:'Chlorophyll'};
const PALETTES = {
 temperature:[[0x071b8f,0],[0x075cff,.15],[0x00c6ff,.32],[0x00e79a,.48],[0xfff000,.62],[0xff6b00,.80],[0xb40000,1]],
 temperature_anomaly:[[0x06349e,0],[0x4b9fe8,.25],[0xffffff,.5],[0xffa060,.75],[0xb60018,1]],
 salinity:[[0x071d9b,0],[0x00a6ff,.20],[0x00d49a,.42],[0xb8e52e,.68],[0xffe600,1]],
 sea_level:[[0x102caa,0],[0x00a9ff,.25],[0x26d08b,.50],[0xffd21a,.75],[0xd40000,1]],
 chlorophyll:[[0xf7fff0,0],[0xb7ef59,.20],[0x42c83e,.45],[0x078d38,.72],[0x003d20,1]],
 fallback:[[0x071b8f,0],[0x00cfff,.25],[0xfff000,.5],[0xff6a00,.75],[0xb40000,1]]
};
const S={scene:null,camera:null,renderer:null,controls:null,root:null,water:null,seabed:null,land:null,coast:null,field:null,volume:null,volumeMat:null,volumeTex:null,bathy:null,bathyTex:null,bathyMax:1,currentGroup:null,catalog:[],times:[],ti:0,active:'temperature',descriptor:null,range:null,depthMode:'volume',sliceDepth:0,depthEx:10,request:0,playing:false,domain:null,bathyInfo:null};

async function get(path){const r=await fetch(API+path,{cache:'no-store'});if(!r.ok){let t='';try{t=await r.text()}catch{}throw Error(`${r.status} ${t||r.statusText}`)}return r.json()}
function status(t,type='ok'){$('status').textContent=t;$('statusDot').className=type==='error'?'error':type==='busy'?'busy':''}
function fail(e){console.error(e);$('loading').classList.add('hidden');$('fatalText').textContent=e?.message||String(e);$('fatal').classList.add('show');status(`Viewer failed · ${e?.message||e}`,'error')}
function quantile(a,p){if(!a.length)return null;const x=(a.length-1)*p,i=Math.floor(x),j=Math.ceil(x);return a[i]+(a[j]-a[i])*(x-i)}
function adaptiveRange(values){const a=values.filter(finite).sort((x,y)=>x-y);if(!a.length)throw Error('No finite values returned');let lo=quantile(a,.01),hi=quantile(a,.99);if(S.active==='temperature_anomaly'){const m=Math.max(Math.abs(lo),Math.abs(hi));lo=-m;hi=m}if(!(hi>lo)){const d=Math.max(Math.abs(lo)*.02,1e-6);lo-=d;hi+=d}return{lo,hi}}
function color(q){const s=PALETTES[S.active]||PALETTES.fallback;q=clamp(q,0,1);let a=s[0],b=s.at(-1);for(let i=0;i<s.length-1;i++)if(q<=s[i+1][1]){a=s[i];b=s[i+1];break}const t=(q-a[1])/(b[1]-a[1]||1),ca=a[0],cb=b[0];return new THREE.Color((((ca>>16)&255)+(((cb>>16)&255)-((ca>>16)&255))*t)/255,(((ca>>8)&255)+(((cb>>8)&255)-((ca>>8)&255))*t)/255,((ca&255)+((cb&255)-(ca&255))*t)/255)}
function colorTexture(){const a=new Uint8Array(256*4);for(let i=0;i<256;i++){const c=color(i/255),k=i*4;a[k]=c.r*255;a[k+1]=c.g*255;a[k+2]=c.b*255;a[k+3]=255}const t=new THREE.DataTexture(a,256,1,THREE.RGBAFormat);t.colorSpace=THREE.SRGBColorSpace;t.needsUpdate=true;return t}
function metaFile(file){return get(`/metadata/${encodeURIComponent(file)}`)}
function coordMeta(meta,names){for(const n of names)if(meta.coordinates?.[n])return{...meta.coordinates[n],name:n};return null}
function getDomain(meta){const lat=coordMeta(meta,['latitude','lat']),lon=coordMeta(meta,['longitude','lon']);if(!lat||!lon)throw Error(`Dataset ${meta.file} has no latitude/longitude coordinates`);return{lat:[Number(lat.min),Number(lat.max)],lon:[Number(lon.min),Number(lon.max)],latName:lat.name,lonName:lon.name}}
function findVariableMeta(meta,name){return meta.variables?.find(v=>v.name===name)||null}
function descriptorFromResponse(f){const dims=f.dimensions||[],shape=f.shape||[],coords=f.coordinates||{},depthName=dims.find(x=>['depth','deptht','depthu','depthv','depthw','lev','level','z'].includes(x)),latName=dims.find(x=>['latitude','lat'].includes(x)),lonName=dims.find(x=>['longitude','lon'].includes(x));if(!latName||!lonName)throw Error('Field response has no latitude/longitude dimensions');const lat=Array.from(coords[latName]||[]).map(Number),lon=Array.from(coords[lonName]||[]).map(Number),depth=depthName?Array.from(coords[depthName]||[]).map(Number):[0];const strides=new Array(shape.length);let n=1;for(let i=shape.length-1;i>=0;i--){strides[i]=n;n*=shape[i]}const li=dims.indexOf(latName),xi=dims.indexOf(lonName),zi=depthName?dims.indexOf(depthName):-1,raw=flat(f.data||[]).map(Number),zOrder=depth.map((v,i)=>[v,i]).sort((a,b)=>a[0]-b[0]),yOrder=lat.map((v,i)=>[v,i]).sort((a,b)=>a[0]-b[0]),xOrder=lon.map((v,i)=>[v,i]).sort((a,b)=>a[0]-b[0]),w=xOrder.length,h=yOrder.length,z=zOrder.length,out=new Float32Array(w*h*z);out.fill(NaN);const valid=[];const index=(x,y,d)=>{let p=0;for(let k=0;k<dims.length;k++){let q=0;if(k===xi)q=x;if(k===li)q=y;if(k===zi)q=d;p+=q*strides[k]}return Number(raw[p])};for(let k=0;k<z;k++)for(let j=0;j<h;j++)for(let i=0;i<w;i++){const v=index(xOrder[i][1],yOrder[j][1],zi<0?0:zOrder[k][1]),p=k*w*h+j*w+i;out[p]=finite(v)?v:NaN;if(finite(v))valid.push(v)}return{width:w,height:h,depth:z,lon:xOrder.map(x=>x[0]),lat:yOrder.map(x=>x[0]),levels:zOrder.map(x=>x[0]),values:out,valid,depthDependent:z>1}}
function chooseStride(meta,variable){const v=findVariableMeta(meta,variable),shape=v?.shape||[],dims=v?.dimensions||[],latI=dims.findIndex(x=>x==='latitude'||x==='lat'),lonI=dims.findIndex(x=>x==='longitude'||x==='lon'),depI=dims.findIndex(x=>['depth','deptht','depthu','depthv','depthw','lev','level','z'].includes(x));let n=1;if(latI>=0)n*=shape[latI];if(lonI>=0)n*=shape[lonI];if(depI>=0)n*=shape[depI];if(n>900000)return 5;if(n>500000)return 4;if(n>250000)return 3;if(n>120000)return 2;return 1}
function timeQuery(t){return t?`&time_start=${encodeURIComponent(t)}&time_end=${encodeURIComponent(t)}`:''}
async function fieldRequest(item,time){const meta=await metaFile(item.file),d=getDomain(meta);S.domain=d;const stride=chooseStride(meta,item.variable);return descriptorFromResponse(await get(`/data/region/array?file=${encodeURIComponent(item.file)}&variable=${encodeURIComponent(item.variable)}&lat_min=${d.lat[0]}&lat_max=${d.lat[1]}&lon_min=${d.lon[0]}&lon_max=${d.lon[1]}&stride=${stride}${timeQuery(time)}`))}
function remove(o){if(!o)return;o.traverse(x=>{if(x.geometry)x.geometry.dispose();if(x.material){if(Array.isArray(x.material))x.material.forEach(m=>m.dispose());else x.material.dispose()}});S.root.remove(o)}
function chunkSize(){const lat=S.domain?.lat||[-10,10],lon=S.domain?.lon||[-10,10],dx=Math.max(1,Math.abs(lon[1]-lon[0])),dy=Math.max(1,Math.abs(lat[1]-lat[0]));return{w:28,h:Math.max(18,28*dy/dx)}}
function project(lon,lat,depth=0){const d=S.domain,size=chunkSize();return new THREE.Vector3((lon-(d.lon[0]+d.lon[1])/2)/(Math.abs(d.lon[1]-d.lon[0])||1)*size.w,-depth*S.depthEx*.018,(lat-(d.lat[0]+d.lat[1])/2)/(Math.abs(d.lat[1]-d.lat[0])||1)*size.h)}
function bathyMesh(info){remove(S.seabed);remove(S.land);remove(S.coast);if(!info)return;const {width:w,height:h,lon,lat,values,valid}=info,d=S.domain,size=chunkSize(),geo=new THREE.BufferGeometry(),pos=[],idx=[];const positiveDepth=valid.length?Math.min(...valid)>=0:true,seaDepth=v=>positiveDepth?Math.max(0,v):Math.max(0,-v),ids=new Int32Array(w*h);ids.fill(-1);for(let j=0;j<h;j++)for(let i=0;i<w;i++){const v=values[j*w+i];if(finite(v)){ids[j*w+i]=pos.length/3;const x=(lon[i]-(d.lon[0]+d.lon[1])/2)/(d.lon[1]-d.lon[0]||1)*size.w,z=(lat[j]-(d.lat[0]+d.lat[1])/2)/(d.lat[1]-d.lat[0]||1)*size.h;pos.push(x,-seaDepth(v)*S.depthEx*.018,z)}}for(let j=0;j<h-1;j++)for(let i=0;i<w-1;i++){const a=ids[j*w+i],b=ids[j*w+i+1],c=ids[(j+1)*w+i],e=ids[(j+1)*w+i+1];if(a>=0&&b>=0&&c>=0&&e>=0)idx.push(a,c,b,b,c,e)}geo.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));geo.setIndex(idx);geo.computeVertexNormals();S.seabed=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:0x704b25,roughness:.96,metalness:0}));S.root.add(S.seabed);const landGeo=new THREE.BufferGeometry(),lp=[],li=[],cp=[];const landCell=(i,j)=>{const x=(lon[i]-(d.lon[0]+d.lon[1])/2)/(d.lon[1]-d.lon[0]||1)*size.w,z=(lat[j]-(d.lat[0]+d.lat[1])/2)/(d.lat[1]-d.lat[0]||1)*size.h;return[x,.08,z]},isLand=v=>positiveDepth?!finite(v):finite(v)&&v>=0;for(let j=0;j<h-1;j++)for(let i=0;i<w-1;i++){const q=[values[j*w+i],values[j*w+i+1],values[(j+1)*w+i],values[(j+1)*w+i+1]];if(!q.some(isLand))continue;const a=landCell(i,j),b=landCell(i+1,j),c=landCell(i+1,j+1),e=landCell(i,j+1),n=lp.length/3;lp.push(...a,...b,...c,...e);li.push(n,n+1,n+2,n,n+2,n+3);if(!isLand(q[0])||!isLand(q[1]))cp.push(a,b);if(!isLand(q[1])||!isLand(q[3]))cp.push(b,c);if(!isLand(q[3])||!isLand(q[2]))cp.push(c,e);if(!isLand(q[2])||!isLand(q[0]))cp.push(e,a)}landGeo.setAttribute('position',new THREE.Float32BufferAttribute(lp,3));landGeo.setIndex(li);S.land=new THREE.Mesh(landGeo,new THREE.MeshStandardMaterial({color:0x2f7d32,roughness:1,side:THREE.DoubleSide}));S.root.add(S.land);const cg=new THREE.BufferGeometry();cg.setAttribute('position',new THREE.Float32BufferAttribute(cp.flat(),3));S.coast=new THREE.LineSegments(cg,new THREE.LineBasicMaterial({color:0x123d18}));S.root.add(S.coast);const td=new Uint8Array(w*h*4),maxD=Math.max(1,...valid.map(v=>positiveDepth?Math.max(0,v):Math.max(0,-v)));for(let i=0;i<w*h;i++){const v=values[i],dpth=finite(v)?(positiveDepth?Math.max(0,v):Math.max(0,-v)):0,ok=finite(v)?1:0;td[i*4]=Math.round(clamp(dpth/maxD,0,1)*255);td[i*4+1]=td[i*4];td[i*4+2]=td[i*4];td[i*4+3]=ok*255}S.bathyTex?.dispose();S.bathyTex=new THREE.DataTexture(td,w,h,THREE.RGBAFormat);S.bathyTex.minFilter=THREE.LinearFilter;S.bathyTex.magFilter=THREE.LinearFilter;S.bathyTex.wrapS=S.bathyTex.wrapT=THREE.ClampToEdgeWrapping;S.bathyTex.needsUpdate=true;S.bathyMax=maxD;S.bathy=info}
async function loadBathymetry(){try{const ds=await get('/datasets'),cand=ds.datasets?.find(x=>/bathy|baymetry|gebco|seabed/i.test(x.file||''));if(!cand)return;const v=(cand.variables||[]).find(x=>{const n=(x.name+' '+(x.long_name||'')+' '+(x.standard_name||'')).toLowerCase();return (x.dimensions||[]).filter(d=>/lat|lon/i.test(d)).length>=2&&/depth|elev|bathym|altitude|topo/.test(n)})||(cand.variables||[]).find(x=>(x.dimensions||[]).filter(d=>/lat|lon/i.test(d)).length>=2);if(!v)return;const meta=await metaFile(cand.file),d=getDomain(meta);if(!S.domain)S.domain=d;const stride=chooseStride(meta,v.name),f=await get(`/data/region/array?file=${encodeURIComponent(cand.file)}&variable=${encodeURIComponent(v.name)}&lat_min=${d.lat[0]}&lat_max=${d.lat[1]}&lon_min=${d.lon[0]}&lon_max=${d.lon[1]}&stride=${Math.max(1,stride)}`),desc=descriptorFromResponse(f),vals=desc.values.slice(0,desc.width*desc.height);S.bathyInfo={...desc,values:vals,valid:vals.filter(finite).map(Number)};bathyMesh(S.bathyInfo)}catch(e){console.warn('Bathymetry unavailable:',e)}}
function makeSurface(){remove(S.water);const size=chunkSize(),g=new THREE.PlaneGeometry(size.w,size.h,1,1);g.rotateX(-Math.PI/2);S.water=new THREE.Mesh(g,new THREE.MeshPhysicalMaterial({color:0x0a63d8,transparent:true,opacity:.20,roughness:.12,metalness:.02,depthWrite:false,side:THREE.DoubleSide}));S.water.position.y=.18;S.root.add(S.water)}
function volumeTexture(desc){S.volumeTex?.dispose();const arr=new Uint8Array(desc.values.length),lo=S.range.lo,hi=S.range.hi;for(let i=0;i<arr.length;i++){const v=desc.values[i];arr[i]=finite(v)?Math.round(clamp((v-lo)/(hi-lo),0,1)*255):0}const t=new THREE.Data3DTexture(arr,desc.width,desc.height,desc.depth);t.format=THREE.RedFormat;t.type=THREE.UnsignedByteType;t.minFilter=THREE.LinearFilter;t.magFilter=THREE.LinearFilter;t.unpackAlignment=1;t.wrapS=t.wrapT=t.wrapR=THREE.ClampToEdgeWrapping;t.needsUpdate=true;S.volumeTex=t;return t}
function volumeMaterial(desc){const tex=volumeTexture(desc),pal=colorTexture(),size=chunkSize(),maxDepth=Math.max(1,desc.levels.at(-1)||1),height=maxDepth*S.depthEx*.018;const geo=new THREE.BoxGeometry(1,1,1),fallbackBathy=new THREE.DataTexture(new Uint8Array([255,255,255,255]),1,1,THREE.RGBAFormat);fallbackBathy.needsUpdate=true;const mat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.BackSide,uniforms:{uVolume:{value:tex},uPalette:{value:pal},uRange:{value:new THREE.Vector2(S.range.lo,S.range.hi)},uMaxDepth:{value:maxDepth},uSliceMode:{value:S.depthMode==='slice'?1:0},uSliceDepth:{value:S.sliceDepth},uDensity:{value:.075},uScale:{value:new THREE.Vector3(size.w,height,size.h)},uCenter:{value:new THREE.Vector3(0,.1,0)},uBathy:{value:S.bathyTex||fallbackBathy},uBathyMax:{value:S.bathyMax||1}},vertexShader:`varying vec3 vLocal;void main(){vLocal=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`,fragmentShader:`precision highp float;varying vec3 vLocal;uniform sampler3D uVolume;uniform sampler2D uPalette;uniform vec2 uRange;uniform float uMaxDepth;uniform float uSliceMode;uniform float uSliceDepth;uniform float uDensity;uniform vec3 uScale;uniform vec3 uCenter;uniform sampler2D uBathy;uniform float uBathyMax;vec2 hitBox(vec3 ro,vec3 rd){vec3 inv=1.0/rd;vec3 a=(-vec3(.5)-ro)*inv;vec3 b=(vec3(.5)-ro)*inv;vec3 mn=min(a,b),mx=max(a,b);return vec2(max(max(mn.x,mn.y),mn.z),min(min(mx.x,mx.y),mx.z));}void main(){vec3 ro=(cameraPosition-uCenter)/uScale;vec3 rd=normalize(vLocal-ro);vec2 hit=hitBox(ro,rd);if(hit.y<=max(hit.x,0.0))discard;float t=max(hit.x,0.0),end=hit.y;vec4 acc=vec4(0.0);for(int i=0;i<128;i++){float u=float(i)/127.0;float tt=mix(t,end,u);vec3 q=ro+rd*tt;vec2 uv=vec2(q.x+.5,q.z+.5);vec3 texel=vec3(uv,clamp(.5-q.y,0.0,1.0));float raw=texture(uVolume,texel).r;float valid=step(.002,raw);vec4 bv=texture2D(uBathy,uv);float bottom=bv.r*uBathyMax;float depth=clamp(.5-q.y,0.0,1.0)*uMaxDepth;valid*=step(depth,bottom+.5)*step(.5,bv.a);if(uSliceMode>.5){float band=max(uMaxDepth*.018,1.0);valid*=1.0-smoothstep(band,band*2.0,abs(depth-uSliceDepth));}vec4 c=texture2D(uPalette,vec2(raw,.5));float a=valid*uDensity;acc.rgb+=(1.0-acc.a)*c.rgb*a;acc.a+=(1.0-acc.a)*a;if(acc.a>.985)break;}if(acc.a<.01)discard;gl_FragColor=acc;}`});fallbackBathy.dispose();return{geo,mat,height,size}}
function makeVolume(desc){remove(S.volume);S.volumeTex?.dispose();if(!desc.depthDependent){makeFieldSurface(desc);return}const vm=volumeMaterial(desc);S.volumeMat=vm.mat;S.volume=new THREE.Mesh(vm.geo,vm.mat);S.volume.position.y=.1;S.volume.scale.copy(vm.size);S.root.add(S.volume);S.descriptor=desc}
function makeFieldSurface(desc){remove(S.field);const w=desc.width,h=desc.height,vals=desc.values.slice(0,w*h),d=S.domain,size=chunkSize(),pos=[],col=[];for(let j=0;j<h;j++)for(let i=0;i<w;i++){const x=(desc.lon[i]-(d.lon[0]+d.lon[1])/2)/(d.lon[1]-d.lon[0]||1)*size.w,z=(desc.lat[j]-(d.lat[0]+d.lat[1])/2)/(d.lat[1]-d.lat[0]||1)*size.h,v=vals[j*w+i];pos.push(x,.22,z);const c=finite(v)?color((v-S.range.lo)/(S.range.hi-S.range.lo)):new THREE.Color(0x0a63d8);col.push(c.r,c.g,c.b)}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));geo.setAttribute('color',new THREE.Float32BufferAttribute(col,3));S.field=new THREE.Points(geo,new THREE.PointsMaterial({size:.14,vertexColors:true,transparent:true,opacity:.95,sizeAttenuation:true}));S.root.add(S.field)}
function updateVolumeUniforms(){if(!S.volumeMat)return;S.volumeMat.uniforms.uRange.value.set(S.range.lo,S.range.hi);S.volumeMat.uniforms.uSliceMode.value=S.depthMode==='slice'?1:0;S.volumeMat.uniforms.uSliceDepth.value=S.sliceDepth;S.volumeMat.uniforms.uMaxDepth.value=Math.max(1,S.descriptor?.levels.at(-1)||1);S.volumeMat.uniforms.uPalette.value=colorTexture();if(S.bathyTex){S.volumeMat.uniforms.uBathy.value=S.bathyTex;S.volumeMat.uniforms.uBathyMax.value=S.bathyMax||1}}
async function drawCurrents(time){if(S.currentGroup){remove(S.currentGroup);S.currentGroup=null}try{const d=await get(`/ocean/current-grid?time=${encodeURIComponent(time||'')}&depth=0&stride=5`),g=new THREE.Group(),lat=d.latitude||[],lon=d.longitude||[],u=flat(d.u||[]).map(Number),v=flat(d.v||[]).map(Number),nx=lon.length,magMax=Math.max(.001,...u.map((x,k)=>Math.hypot(x,v[k]||0)).filter(finite));for(let j=0;j<lat.length;j++)for(let i=0;i<nx;i++){const k=j*nx+i,uu=u[k],vv=v[k];if(!finite(uu)||!finite(vv))continue;const mag=Math.hypot(uu,vv),p=project(lon[i],lat[j],0),dir=new THREE.Vector3(vv,0,uu);if(dir.lengthSq()<1e-10)continue;dir.normalize();const len=clamp(mag/magMax, .10,1.0),geom=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(0,0,0),new THREE.Vector3(dir.x*len,0,dir.z*len)]);const line=new THREE.Line(geom,new THREE.LineBasicMaterial({color:color(mag/magMax)}));line.position.copy(p);g.add(line)}S.currentGroup=g;S.root.add(g)}catch(e){console.warn('Currents unavailable:',e)}}
function clearField(){remove(S.volume);remove(S.field);S.volume=null;S.field=null;S.volumeMat=null;S.descriptor=null}
async function loadActive(){const token=++S.request,item=S.catalog.find(x=>x.id===S.active);if(!item?.available){status(`${LABEL[S.active]} unavailable`,'error');clearField();return}status(`Loading ${LABEL[S.active]}…`,'busy');try{const desc=await fieldRequest(item,S.times[S.ti]);if(token!==S.request)return;S.range=adaptiveRange(desc.valid);clearField();if(desc.depthDependent){makeVolume(desc);$('depthSection').classList.remove('hidden');$('depthMax').textContent=`${desc.levels.at(-1).toFixed(0)} m`;S.sliceDepth=clamp(S.sliceDepth,0,desc.levels.at(-1)||0)}else{$('depthSection').classList.add('hidden');makeFieldSurface(desc)}$('legendLo').textContent=S.range.lo.toPrecision(5);$('legendHi').textContent=S.range.hi.toPrecision(5);$('legendNote').textContent=`1–99 percentile · ${desc.valid.length.toLocaleString()} finite samples`;status(`${LABEL[S.active]} · ${desc.depthDependent?'3D volume':'surface field'}`);drawCurrents(S.times[S.ti])}catch(e){if(token===S.request){clearField();status(`${LABEL[S.active]} failed · ${e.message}`,'error')}}}
function renderReadout(v){const values=v.values||[];$('coords').textContent=`${Number(v.latitude).toFixed(4)}° · ${Number(v.longitude).toFixed(4)}°`;const grid=$('readoutGrid');grid.innerHTML='';for(const x of values){const b=document.createElement('div');b.className='readoutCell';const val=x.value;if(x.id==='currents'&&val&&typeof val==='object'){const uv=Object.values(val).map(Number);b.innerHTML=`<b>${x.label}</b><strong>u₀: ${finite(uv[0])?uv[0].toFixed(3):'—'}<br>v₀: ${finite(uv[1])?uv[1].toFixed(3):'—'}</strong><small>${x.units||''}</small>`}else{b.innerHTML=`<b>${x.label}</b><strong>${finite(val)?Number(val).toFixed(4):'—'}</strong><small>${x.units||''}</small>`}grid.appendChild(b)}$('readoutTime').textContent=`Dataset time: ${v.time||'—'}`;$('readout').classList.remove('hidden')}
function pick(e){const r=S.renderer.domElement.getBoundingClientRect(),m=new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(m,S.camera);const hits=ray.intersectObjects([S.water,S.seabed,S.field,S.volume].filter(Boolean),true);if(!hits.length)return;const p=hits[0].point,d=S.domain,sz=chunkSize(),lon=(p.x/sz.w)*(d.lon[1]-d.lon[0])+(d.lon[0]+d.lon[1])/2,lat=(p.z/sz.h)*(d.lat[1]-d.lat[0])+(d.lat[0]+d.lat[1])/2;get(`/ocean/point?latitude=${encodeURIComponent(lat)}&longitude=${encodeURIComponent(lon)}&time=${encodeURIComponent(S.times[S.ti]||'')}`).then(renderReadout).catch(err=>status(`Point lookup failed · ${err.message}`,'error'))}
function view(name){const box=new THREE.Box3().setFromObject(S.root),c=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()),r=Math.max(size.x,size.y,size.z,10);let p=new THREE.Vector3();if(name==='top')p.set(c.x,r*1.9,c.z+.01);else if(name==='under')p.set(c.x,-r*.95,c.z+r*.65);else if(name==='profile')p.set(r*1.65,r*.20,c.z);else p.set(r*1.15,r*.85,r*1.15);S.camera.position.copy(p);S.controls.target.copy(c);S.controls.update()}
function resize(){const w=innerWidth,h=innerHeight;S.camera.aspect=w/h;S.camera.updateProjectionMatrix();S.renderer.setSize(w,h,false)}
function initScene(){S.renderer=new THREE.WebGLRenderer({canvas:$('renderCanvas'),antialias:true,powerPreference:'high-performance'});S.renderer.setPixelRatio(Math.min(devicePixelRatio,2));S.renderer.outputColorSpace=THREE.SRGBColorSpace;S.renderer.toneMapping=THREE.ACESFilmicToneMapping;S.renderer.toneMappingExposure=1.05;S.scene=new THREE.Scene();S.scene.background=new THREE.Color(0xdbeaf4);S.camera=new THREE.PerspectiveCamera(45,innerWidth/innerHeight,.1,5000);S.camera.position.set(34,26,34);S.controls=new OrbitControls(S.camera,S.renderer.domElement);S.controls.enableDamping=true;S.controls.dampingFactor=.08;S.controls.minDistance=5;S.controls.maxDistance=180;S.root=new THREE.Group();S.scene.add(S.root);S.scene.add(new THREE.HemisphereLight(0xffffff,0x4b5d70,2));const dl=new THREE.DirectionalLight(0xffffff,2.2);dl.position.set(20,50,20);S.scene.add(dl);resize();addEventListener('resize',resize);$('renderCanvas').addEventListener('click',pick);requestAnimationFrame(loop)}
function loop(){S.controls?.update();if(S.playing&&S.times.length&&performance.now()-(S.lastPlay||0)>1600){S.lastPlay=performance.now();S.ti=(S.ti+1)%S.times.length;updateTimeUI();loadActive()}S.renderer?.render(S.scene,S.camera);requestAnimationFrame(loop)}
function renderVars(){const root=$('vars');root.innerHTML='';for(const x of S.catalog){const b=document.createElement('button');b.className=`var ${x.id===S.active?'active':''} ${x.available?'':'disabled'}`;b.disabled=!x.available;b.innerHTML=`<b>${x.label}</b><small>${x.units||'—'}</small><i></i>`;b.onclick=()=>{if(S.active!==x.id){S.active=x.id;renderVars();loadActive()}};root.appendChild(b)}}
function updateTimeUI(){const t=S.times[S.ti];$('timeSlider').value=S.ti;$('timeSlider').max=Math.max(0,S.times.length-1);$('timeCount').textContent=`${S.ti+1}/${S.times.length}`;$('timeValue').textContent=t?new Date(t).toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'}):'—';$('timeRaw').textContent=t||'—'}
function events(){document.querySelectorAll('.view[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.view[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');view(b.dataset.view)});$('reset').onclick=()=>{S.controls.reset();view('3d')};$('fullscreen').onclick=()=>document.documentElement.requestFullscreen?.();$('closeReadout').onclick=()=>$('readout').classList.add('hidden');$('exaggeration').oninput=e=>{S.depthEx=Number(e.target.value);$('exagValue').textContent=`${S.depthEx}×`;if(S.descriptor){makeVolume(S.descriptor);if(S.bathyInfo)bathyMesh(S.bathyInfo)}};$('depthSlider').oninput=e=>{const max=S.descriptor?.levels.at(-1)||0;S.sliceDepth=Number(e.target.value)/100*max;$('depthValue').textContent=`${S.sliceDepth.toFixed(0)} m`;updateVolumeUniforms();$('depthBadge').textContent=`${S.depthMode==='slice'?`Slice · ${S.sliceDepth.toFixed(0)} m`:'Volume'}`};document.querySelectorAll('[data-depth-mode]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-depth-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.depthMode=b.dataset.depthMode;$('depthSlider').disabled=S.depthMode!=='slice';updateVolumeUniforms()});$('timeSlider').oninput=e=>{S.ti=Number(e.target.value);updateTimeUI();loadActive()};$('play').onclick=()=>{S.playing=!S.playing;$('play').textContent=S.playing?'PAUSE':'PLAY'};}
async function boot(){initScene();events();status('Discovering datasets…','busy');const [catalog,time]=await Promise.all([get('/ocean/catalog'),get('/ocean/time')]);S.catalog=catalog.variables||[];S.times=time.values||[];updateTimeUI();renderVars();const first=S.catalog.find(x=>x.available);if(first){const meta=await metaFile(first.file);S.domain=getDomain(meta);makeSurface()}await loadBathymetry();await loadActive();$('loading').classList.add('hidden');view('3d')}
boot().catch(fail);
