import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

const $ = id => document.getElementById(id);
const API = `${location.protocol === 'file:' ? 'http:' : location.protocol}//${location.hostname || '127.0.0.1'}:8000`;
const finite = v => Number.isFinite(Number(v));
const clamp = (v, a, b) => Math.max(a, Math.min(b, v));
const DIMS = new Set(['depth','deptht','depthu','depthv','depthw','lev','level','z']);
const LAT = new Set(['lat','latitude']);
const LON = new Set(['lon','longitude']);
const LABEL = {temperature:'Temperature',temperature_anomaly:'SST anomaly',salinity:'Salinity',currents:'Currents',sea_level:'Sea level',chlorophyll:'Chlorophyll'};
const PAL = {
 temperature:[[0x08218f,0],[0x0877e0,.18],[0x00c7d9,.36],[0x22d36e,.5],[0xffef27,.64],[0xff7818,.82],[0xb40d20,1]],
 temperature_anomaly:[[0x123b8d,0],[0x5aa7e8,.25],[0xffffff,.5],[0xff9c72,.75],[0xb2182b,1]],
 salinity:[[0x07229d,0],[0x00b4ef,.22],[0x16d495,.45],[0xd2e638,.7],[0xffe400,1]],
 sea_level:[[0x162fa5,0],[0x12a9ef,.25],[0x2bd38b,.5],[0xffd51e,.75],[0xd30d16,1]],
 chlorophyll:[[0xf5fff1,0],[0xb6f36b,.22],[0x35c943,.48],[0x05823c,.74],[0x003b28,1]],
 fallback:[[0x08218f,0],[0x06c7dd,.25],[0xeff21f,.5],[0xff6816,.75],[0xb40d20,1]]
};
const S={scene:null,camera:null,renderer:null,controls:null,root:null,geom:null,descriptor:null,range:null,active:'temperature',catalog:[],times:[],ti:0,depthMode:'volume',sliceDepth:0,depthEx:10,water:null,waterGroups:[],land:null,landWalls:null,coast:null,seabed:null,oceanSurface:null,currents:null,ray:new THREE.Raycaster(),mouse:new THREE.Vector2(),token:0,playing:false,lastPlay:0};

async function api(path){const r=await fetch(API+path,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${await r.text()}`);return r.json()}
async function staticJson(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${await r.text()}`);return r.json()}
function status(t,k='ok'){$('status').textContent=t;$('statusDot').className=k==='error'?'error':k==='busy'?'busy':''}
function clear(o){if(!o)return;o.traverse(x=>{x.geometry?.dispose();if(x.material)(Array.isArray(x.material)?x.material:[x.material]).forEach(m=>m.dispose())});o.parent?.remove(o)}
function q(a,p){if(!a.length)return NaN;const b=[...a].sort((x,y)=>x-y),x=(b.length-1)*p,i=Math.floor(x),j=Math.ceil(x);return b[i]+(b[j]-b[i])*(x-i)}
function valueRange(values){const v=values.filter(finite).map(Number);if(!v.length)throw Error('No finite values returned');let lo=q(v,.01),hi=q(v,.99);if(S.active==='temperature_anomaly'){const m=Math.max(Math.abs(lo),Math.abs(hi));lo=-m;hi=m}if(!(hi>lo)){const d=Math.max(Math.abs(lo)*.02,1e-6);lo-=d;hi+=d}return{lo,hi}}
function color(v){const p=PAL[S.active]||PAL.fallback;let t=clamp((v-S.range.lo)/(S.range.hi-S.range.lo||1),0,1),a=p[0],b=p.at(-1);for(let i=0;i<p.length-1;i++)if(t<=p[i+1][1]){a=p[i];b=p[i+1];break}const u=(t-a[1])/(b[1]-a[1]||1),ar=(a[0]>>16)&255,ag=(a[0]>>8)&255,ab=a[0]&255,br=(b[0]>>16)&255,bg=(b[0]>>8)&255,bb=b[0]&255;return new THREE.Color((ar+(br-ar)*u)/255,(ag+(bg-ag)*u)/255,(ab+(bb-ab)*u)/255)}
function metadataDomain(m){const c=m.coordinates||{},la=c.latitude||c.lat,lo=c.longitude||c.lon;if(!la||!lo)throw Error('Dataset has no latitude/longitude');return{lat:[+la.min,+la.max],lon:[+lo.min,+lo.max]}}
function strideFor(m,n){const v=(m.variables||[]).find(x=>x.name===n),d=v?.dimensions||[],s=v?.shape||[];let a=1,b=1;d.forEach((x,i)=>{if(LAT.has(x))a=s[i]||1;if(LON.has(x))b=s[i]||1});const g=a*b;return g>3600?5:g>2400?4:g>1200?3:g>600?2:1}
function parse(packet){const dims=packet.dimensions||[],shape=packet.shape||[],c=packet.coordinates||{},ln=dims.find(x=>LON.has(x)),lt=dims.find(x=>LAT.has(x)),zn=dims.find(x=>DIMS.has(x));if(!ln||!lt)throw Error('Field has no lat/lon dimensions');const lats=(c[lt]||[]).map(Number).sort((a,b)=>a-b),lons=(c[ln]||[]).map(Number).sort((a,b)=>a-b),levels=(zn?(c[zn]||[]).map(Number):[0]).map(Math.abs).sort((a,b)=>a-b),raw=(function(v){const o=[];(function f(x){Array.isArray(x)?x.forEach(f):o.push(x)})(v||[]);return o.map(Number)})(packet.data);const li=dims.indexOf(lt),xi=dims.indexOf(ln),zi=zn?dims.indexOf(zn):-1,st=[];let k=1;for(let i=shape.length-1;i>=0;i--){st[i]=k;k*=shape[i]}const oi=(x,y,z)=>{let p=0;for(let d=0;d<dims.length;d++){let i=0;if(d===xi)i=x;else if(d===li)i=y;else if(d===zi)i=z;p+=i*st[d]}return p},w=lons.length,h=lats.length,z=levels.length,values=new Float32Array(w*h*z);values.fill(NaN);const valid=[];const xo=(c[ln]||[]).map(Number).map((v,i)=>[v,i]).sort((a,b)=>a[0]-b[0]),yo=(c[lt]||[]).map(Number).map((v,i)=>[v,i]).sort((a,b)=>a[0]-b[0]),zo=(zn?(c[zn]||[]).map(Number):[0]).map((v,i)=>[Math.abs(v),i]).sort((a,b)=>a[0]-b[0]);for(let z0=0;z0<z;z0++)for(let y=0;y<h;y++)for(let x=0;x<w;x++){const v=Number(raw[oi(xo[x][1],yo[y][1],zi<0?0:zo[z0][1])]);values[z0*w*h+y*w+x]=v;if(finite(v))valid.push(v)}return{w,h,z,lons,lats,levels,values,valid,depthDependent:z>1}}
function proj(lon,lat){const b=S.geom.bounds,midLat=(b[2]+b[3])/2;return[(lon-(b[0]+b[1])/2)*111.32*Math.cos(midLat*Math.PI/180),(lat-midLat)*111.32]}
function terrainDepth(lon,lat){const t=S.geom.terrain;if(!t?.x?.length)return 0;const p=proj(lon,lat),nx=t.x.length,ny=t.y.length,ix=clamp(Math.round((p[0]-t.x[0])/((t.x.at(-1)-t.x[0])||1)*(nx-1)),0,nx-1),iy=clamp(Math.round((p[1]-t.y[0])/((t.y.at(-1)-t.y[0])||1)*(ny-1)),0,ny-1),d=Number((t.rawDepthKm[iy]||[])[ix]);return finite(d)?Math.max(0,d*1000):0}
function yDepth(m){return -m*S.depthEx/1000}
function polygonMesh(parts,y){const pos=[],ind=[];let base=0;for(const p of parts||[]){for(const v of p.vertices||[])pos.push(+v[0],y,+v[1]);for(const t of p.triangles||[])ind.push(base+t[0],base+t[1],base+t[2]);base+=(p.vertices||[]).length}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setIndex(ind);g.computeVertexNormals();return g}
function linesMesh(lines,y){const pos=[];for(const line of lines||[])for(let i=0;i<line.length-1;i++)pos.push(line[i][0],y,line[i][1],line[i+1][0],y,line[i+1][1]);const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));return g}
function drawLand(){clear(S.land);clear(S.landWalls);clear(S.coast);const g=S.geom;if(!g)return;S.land=new THREE.Mesh(polygonMesh([...(g.land||[]),...(g.islands||[])],.08),new THREE.MeshBasicMaterial({color:0x4e9656,side:THREE.DoubleSide}));S.root.add(S.land);const bottom=-(Number(g.landThickness||3)*S.depthEx/1000),p=[];for(const line of [...(g.landBoundary||[]),...(g.islandCoast||[])])for(let i=0;i<line.length-1;i++){const a=line[i],b=line[i+1];p.push(a[0],.05,a[1],b[0],.05,b[1],a[0],bottom,a[1],b[0],bottom,b[1])}const wg=new THREE.BufferGeometry();wg.setAttribute('position',new THREE.Float32BufferAttribute(p,3));S.landWalls=new THREE.LineSegments(wg,new THREE.LineBasicMaterial({color:0x315d37,transparent:true,opacity:.8}));S.root.add(S.landWalls);S.coast=new THREE.LineSegments(linesMesh(g.coast||[],.10),new THREE.LineBasicMaterial({color:0x123f24}));S.root.add(S.coast)}
function drawSeabed(){clear(S.seabed);const t=S.geom.terrain;if(!t?.x?.length)return;const w=t.x.length,h=t.y.length,id=new Int32Array(w*h);id.fill(-1),pos=[];for(let y=0;y<h;y++)for(let x=0;x<w;x++){const d=Number((t.rawDepthKm[y]||[])[x]);if(!finite(d))continue;id[y*w+x]=pos.length/3;pos.push(t.x[x],-d*S.depthEx,t.y[y])}const ind=[];for(let y=0;y<h-1;y++)for(let x=0;x<w-1;x++){const a=id[y*w+x],b=id[y*w+x+1],c=id[(y+1)*w+x],d=id[(y+1)*w+x+1];if(a>=0&&b>=0&&c>=0&&d>=0)ind.push(a,c,b,b,c,d)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setIndex(ind);g.computeVertexNormals();S.seabed=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:0x73502d,roughness:1,side:THREE.DoubleSide}));S.root.add(S.seabed)}
function drawOceanSurface(){clear(S.oceanSurface);const o=S.geom.ocean;if(!o?.length)return;S.oceanSurface=new THREE.Mesh(polygonMesh(o,.14),new THREE.MeshPhysicalMaterial({color:0x087cc3,transparent:true,opacity:.10,roughness:.08,depthWrite:false,side:THREE.DoubleSide}));S.root.add(S.oceanSurface)}
function bounds(a,i){if(a.length===1)return[a[0]-.02,a[0]+.02];if(i===0)return[a[0]-(a[1]-a[0])/2,(a[0]+a[1])/2];if(i===a.length-1)return[(a[i-1]+a[i])/2,a[i]+(a[i]-a[i-1])/2];return[(a[i-1]+a[i])/2,(a[i]+a[i+1])/2]}
function buildInstances(cells,opacity){if(!cells.length)return null;const geo=new THREE.BoxGeometry(1,1,1),mat=new THREE.MeshBasicMaterial({vertexColors:true,transparent:true,opacity,depthWrite:false,side:THREE.DoubleSide}),m=new THREE.InstancedMesh(geo,mat,cells.length),d=new THREE.Object3D();for(let i=0;i<cells.length;i++){const c=cells[i];d.position.set(c.x,c.y,c.z);d.scale.set(c.sx,Math.max(.015,c.sy),c.sz);d.updateMatrix();m.setMatrixAt(i,d.matrix);m.setColorAt(i,color(c.value))}m.instanceMatrix.needsUpdate=true;m.instanceColor.needsUpdate=true;m.userData={cells,isWater:true};return m}
function buildWater(desc){clear(S.water);S.waterGroups=[];S.water=new THREE.Group();const N=desc.w*desc.h,box=new THREE.BoxGeometry(1,1,1),valueAt=(k,i,j)=>{let v=desc.values[k*N+j*desc.w+i];if(finite(v))return+v;for(let d=1;d<desc.z;d++){for(const kk of [k-d,k+d])if(kk>=0&&kk<desc.z){v=desc.values[kk*N+j*desc.w+i];if(finite(v))return+v}}return NaN};if(!desc.depthDependent){const cells=[];for(let j=0;j<desc.h;j++)for(let i=0;i<desc.w;i++){const v=valueAt(0,i,j);if(!finite(v))continue;const xb=bounds(desc.lons,i),zb=bounds(desc.lats,j),a=proj(xb[0],desc.lats[j]),b=proj(xb[1],desc.lats[j]),c=proj(desc.lons[i],zb[0]),d=proj(desc.lons[i],zb[1]);cells.push({x:(a[0]+b[0])/2,z:(c[1]+d[1])/2,sx:Math.abs(b[0]-a[0]),sz:Math.abs(d[1]-c[1]),y:yDepth(.25),sy:Math.max(.3,S.depthEx*.05),value:v,lon:desc.lons[i],lat:desc.lats[j],depth:0})}const m=buildInstances(cells,.25);if(m)S.water.add(m);S.waterGroups.push({depth:0,mesh:m})}else for(let k=0;k<desc.z;k++){const top=k?desc.levels[k-1]:0,cells=[];for(let j=0;j<desc.h;j++)for(let i=0;i<desc.w;i++){const v=valueAt(k,i,j);if(!finite(v))continue;const seaBed=terrainDepth(desc.lons[i],desc.lats[j]),last=k===desc.z-1,bottom=last?Math.max(desc.levels[k],seaBed):desc.levels[k],thick=bottom-top;if(thick<=.05)continue;const xb=bounds(desc.lons,i),zb=bounds(desc.lats,j),a=proj(xb[0],desc.lats[j]),b=proj(xb[1],desc.lats[j]),c=proj(desc.lons[i],zb[0]),d=proj(desc.lons[i],zb[1]);cells.push({x:(a[0]+b[0])/2,z:(c[1]+d[1])/2,sx:Math.abs(b[0]-a[0]),sz:Math.abs(d[1]-c[1]),y:yDepth(top+thick/2),sy:thick*S.depthEx/1000,value:v,lon:desc.lons[i],lat:desc.lats[j],depth:top+thick/2})}const m=buildInstances(cells,k===0?.25:.13);if(m)S.water.add(m);S.waterGroups.push({depth:top,mesh:m})}box.dispose();S.root.add(S.water);updateWaterVisibility()}
function updateWaterVisibility(){for(const g of S.waterGroups)if(g.mesh)g.mesh.visible=S.depthMode==='volume'||Math.abs(g.depth-S.sliceDepth)<=Math.max(1,(S.descriptor?.levels?.at(-1)||1)*.035)}
function rebuild(){drawLand();drawSeabed();drawOceanSurface();if(S.descriptor)buildWater(S.descriptor)}
function drawCurrents(){clear(S.currents);if(S.active!=='currents')return;const p=new URLSearchParams({stride:'5'});if(S.times[S.ti])p.set('time',S.times[S.ti]);p.set('depth',String(S.depthMode==='slice'?S.sliceDepth:0));api(`/ocean/current-grid?${p}`).then(data=>{const lat=(data.latitude||[]).map(Number),lon=(data.longitude||[]).map(Number),u=data.u||[],v=data.v||[],q=[],pos=[];let max=0;for(let j=0;j<lat.length;j++)for(let i=0;i<lon.length;i++){const a=Number(u[j]?.[i]),b=Number(v[j]?.[i]);if(!finite(a)||!finite(b))continue;const mag=Math.hypot(a,b);max=Math.max(max,mag);q.push({i,j,a,b,mag})}max=Math.max(max,1e-9);for(const a of q){const p0=proj(lon[a.i],lat[a.j]),L=7+18*a.mag/max,dx=a.a/max*L,dz=a.b/max*L,x=p0[0],z=p0[1],ang=Math.atan2(dz,dx),ah=Math.min(5,L*.25);pos.push(x,.5,z,x+dx,.5,z+dz,x+dx,.5,z+dz,x+dx-ah*Math.cos(ang-.55),.5,z+dz-ah*Math.sin(ang-.55),x+dx,.5,z+dz,x+dx-ah*Math.cos(ang+.55),.5,z+dz-ah*Math.sin(ang+.55))}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));S.currents=new THREE.LineSegments(g,new THREE.LineBasicMaterial({color:0x083e6c,transparent:true,opacity:.9}));S.root.add(S.currents)}).catch(e=>console.warn('Currents',e))}
async function loadField(){const token=++S.token,it=S.catalog.find(x=>x.id===S.active);if(!it?.available){status(`${LABEL[S.active]} unavailable`,'error');return}status(`Loading ${LABEL[S.active]}…`,'busy');const m=await api(`/metadata/${encodeURIComponent(it.file)}`),d=metadataDomain(m),qs=new URLSearchParams({file:it.file,variable:it.variable,lat_min:String(d.lat[0]),lat_max:String(d.lat[1]),lon_min:String(d.lon[0]),lon_max:String(d.lon[1]),stride:String(strideFor(m,it.variable))});if(S.times[S.ti]){qs.set('time_start',S.times[S.ti]);qs.set('time_end',S.times[S.ti])}const packet=await api(`/data/region/array?${qs}`);if(token!==S.token)return;S.descriptor=parse(packet);if(!S.descriptor.valid.length)throw Error('No finite values returned');S.range=valueRange(S.descriptor.valid);clear(S.water);clear(S.currents);if(S.descriptor.depthDependent){$('depthSection').classList.remove('hidden');$('depthMax').textContent=`${S.descriptor.levels.at(-1).toFixed(0)} m`;$('depthSlider').max=String(S.descriptor.levels.at(-1));S.sliceDepth=clamp(S.sliceDepth,0,S.descriptor.levels.at(-1));$('depthSlider').value=String(S.sliceDepth)}else{$('depthSection').classList.add('hidden');S.sliceDepth=0} $('legendLo').textContent=Number(S.range.lo).toPrecision(5);$('legendHi').textContent=Number(S.range.hi).toPrecision(5);$('legendNote').textContent=`1–99 percentile · ${S.descriptor.valid.length.toLocaleString()} finite samples`;rebuild();drawCurrents();updateDepth();status(`${LABEL[S.active]} · ${S.descriptor.depthDependent?S.descriptor.z:1} depth level${S.descriptor.depthDependent?'s':''}`);$('loading').classList.add('hidden')}
function updateDepth(){$('depthValue').textContent=S.depthMode==='volume'?'Volume':`${S.sliceDepth.toFixed(0)} m`;$('depthBadge').textContent=S.depthMode==='volume'?'Volume':`${S.sliceDepth.toFixed(0)} m`;updateWaterVisibility()}
function fit(){const b=S.geom.bounds,mid=(b[2]+b[3])/2,w=(b[1]-b[0])*111.32*Math.cos(mid*Math.PI/180),h=(b[3]-b[2])*111.32,d=(S.geom.terrain?.maxDepthKm||1)*S.depthEx,r=Math.max(w,h,d,100);S.camera.position.set(r*.92,r*.58,r*1.05);S.controls.target.set(0,-Math.min(d*.25,r*.3),0);S.camera.near=.05;S.camera.far=r*25;S.camera.updateProjectionMatrix();S.controls.update()}
function view(v){const b=S.geom.bounds,mid=(b[2]+b[3])/2,w=(b[1]-b[0])*111.32*Math.cos(mid*Math.PI/180),h=(b[3]-b[2])*111.32,d=Math.max(80,(S.geom.terrain?.maxDepthKm||1)*S.depthEx),r=Math.max(w,h,d);if(v==='top')S.camera.position.set(0,r*1.6,.01);else if(v==='profile')S.camera.position.set(r*1.25,0,0);else if(v==='under')S.camera.position.set(0,-r*.7,r*.75);else S.camera.position.set(r*.92,r*.58,r*1.05);S.controls.target.set(0,v==='top'?0:-Math.min(d*.22,r*.3),0);S.controls.update()}
function resize(){S.camera.aspect=innerWidth/innerHeight;S.camera.updateProjectionMatrix();S.renderer.setSize(innerWidth,innerHeight,false)}
function onCanvasClick(e){const r=$('renderCanvas').getBoundingClientRect();S.mouse.x=(e.clientX-r.left)/r.width*2-1;S.mouse.y=-(e.clientY-r.top)/r.height*2+1;S.ray.setFromCamera(S.mouse,S.camera);const ts=[];S.water?.traverse(o=>{if(o.userData?.isWater)ts.push(o)});const hit=S.ray.intersectObjects(ts,false)[0];if(!hit)return;const c=hit.object.userData.cells?.[hit.instanceId];if(!c)return;showPoint(c.lat,c.lon,c.depth)}
async function showPoint(lat,lon,depth){try{const qs=new URLSearchParams({latitude:String(lat),longitude:String(lon)});if(S.times[S.ti])qs.set('time',S.times[S.ti]);const data=await api(`/ocean/point?${qs}`);$('coords').textContent=`${lat.toFixed(4)}° N · ${lon.toFixed(4)}° E · ${depth.toFixed(0)} m`;$('readoutGrid').innerHTML='';for(const x of data.values||[]){if(!x.available)continue;let v=x.value;if(v&&typeof v==='object'&&!Array.isArray(v)){const a=Object.values(v).filter(finite).map(Number);v=a.length?Math.hypot(...a):'—'}if(!finite(v))v='—';const c=document.createElement('div');c.className='readoutCard';c.innerHTML=`<b>${x.label}</b><strong>${typeof v==='number'?v.toFixed(4):v}</strong><small>${x.units||'—'}</small>`;$('readoutGrid').appendChild(c)}$('readoutTime').textContent=S.times[S.ti]||'—';$('readout').classList.remove('hidden')}catch(e){console.warn('point',e)}}
function ui(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');view(b.dataset.view)});$('reset').onclick=fit;$('fullscreen').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.();$('closeReadout').onclick=()=>$('readout').classList.add('hidden');$('depthMode').onclick=e=>{const b=e.target.closest('[data-depth-mode]');if(!b)return;document.querySelectorAll('#depthMode button').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.depthMode=b.dataset.depthMode;updateDepth()};$('depthSlider').oninput=e=>{S.sliceDepth=+e.target.value;updateDepth()};$('exaggeration').oninput=e=>{S.depthEx=+e.target.value;$('exagValue').textContent=`${S.depthEx}×`;rebuild();fit()};$('play').onclick=()=>{S.playing=!S.playing;$('play').textContent=S.playing?'PAUSE':'PLAY';S.lastPlay=0};$('timeSlider').oninput=e=>{S.ti=+e.target.value;timeline();loadField().catch(fail)};$('renderCanvas').onclick=onCanvasClick;$('vars').onclick=e=>{const b=e.target.closest('[data-field]');if(!b||b.disabled)return;document.querySelectorAll('[data-field]').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.active=b.dataset.field;loadField().catch(fail)};addEventListener('resize',resize)}
function vars(){const x=$('vars');x.innerHTML='';for(const v of S.catalog){const b=document.createElement('button');b.className=`field ${v.id===S.active?'active':''}`;b.disabled=!v.available;b.dataset.field=v.id;b.innerHTML=`<b>${v.label||LABEL[v.id]}</b><small>${v.units||'—'}</small><i></i>`;x.appendChild(b)}}
function timeline(){const t=S.times[S.ti];if(!t)return;const d=new Date(t);$('timeValue').textContent=d.toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'});$('timeRaw').textContent=d.toISOString();$('timeCount').textContent=`${S.ti+1}/${S.times.length}`}
function renderer(){const c=$('renderCanvas');S.renderer=new THREE.WebGLRenderer({canvas:c,antialias:true,powerPreference:'high-performance'});S.renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));S.renderer.setSize(innerWidth,innerHeight,false);S.renderer.setClearColor(0xaedce6,1);S.renderer.outputColorSpace=THREE.SRGBColorSpace;S.scene=new THREE.Scene();S.scene.fog=new THREE.FogExp2(0xaedce6,.00045);S.camera=new THREE.PerspectiveCamera(46,innerWidth/innerHeight,.05,5000);S.controls=new OrbitControls(S.camera,c);S.controls.enableDamping=true;S.controls.screenSpacePanning=true;S.root=new THREE.Group();S.scene.add(S.root);const hemi=new THREE.HemisphereLight(0xdaf5ff,0x624a2e,1.3),sun=new THREE.DirectionalLight(0xffffff,1.2);sun.position.set(200,300,100);S.scene.add(hemi,sun)}
async function init(){renderer();ui();status('Loading land + coastline + GEBCO…','busy');S.geom=await staticJson('geometry.json');if(!S.geom.land||!S.geom.terrain)throw Error('geometry.json does not contain land and GEBCO terrain');drawLand();drawSeabed();drawOceanSurface();fit();const [cat,t]=await Promise.all([api('/ocean/catalog'),api('/ocean/time')]);S.catalog=cat.variables||[];S.times=t.values||[];vars();$('timeSlider').max=String(Math.max(0,S.times.length-1));timeline();await loadField()}
function fail(e){console.error(e);$('loading').classList.add('hidden');$('fatalText').textContent=e?.message||String(e);$('fatal').classList.add('show');status(`Viewer failed · ${e?.message||e}`,'error')}
function loop(t=0){requestAnimationFrame(loop);if(S.playing&&S.times.length>1&&t-S.lastPlay>650){S.lastPlay=t;S.ti=(S.ti+1)%S.times.length;$('timeSlider').value=String(S.ti);timeline();loadField().catch(fail)}S.controls?.update();S.renderer?.render(S.scene,S.camera)}
init().catch(fail);loop();
