import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

const $=id=>document.getElementById(id);
const finite=v=>Number.isFinite(Number(v));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const flat=v=>{const a=[];(function f(x){Array.isArray(x)?x.forEach(f):a.push(x)})(v);return a;};
const API=`${location.protocol==='file:'?'http:':location.protocol}//${location.hostname||'127.0.0.1'}:8000`;
const DEPTH_NAMES=new Set(['depth','deptht','depthu','depthv','depthw','lev','level','z']);
const LAT_NAMES=new Set(['latitude','lat']);
const LON_NAMES=new Set(['longitude','lon']);
const LABEL={temperature:'Temperature',temperature_anomaly:'SST anomaly',salinity:'Salinity',currents:'Currents',sea_level:'Sea level',chlorophyll:'Chlorophyll'};

const S={scene:null,camera:null,renderer:null,controls:null,root:null,geometry:null,catalog:[],times:[],ti:0,active:'temperature',descriptor:null,land:null,coast:null,seabed:null,water:null,surface:null,depthEx:10,playing:false,lastPlay:0,request:0,ray:new THREE.Raycaster(),mouse:new THREE.Vector2(),waterMeshes:[],anchor:null};

async function get(p){const r=await fetch(API+p,{cache:'no-store'});if(!r.ok)throw Error(`${r.status} ${await r.text()}`);return r.json();}
async function staticGet(p){const r=await fetch(p,{cache:'no-store'});if(!r.ok)throw Error(`${r.status} ${await r.text()}`);return r.json();}
function status(t,type='ok'){if($('status'))$('status').textContent=t;if($('statusDot'))$('statusDot').className=type==='error'?'error':type==='busy'?'busy':'';}
function fail(e){console.error(e);$('loading')?.classList.add('hidden');if($('fatalText'))$('fatalText').textContent=e?.message||String(e);$('fatal')?.classList.add('show');status(`Viewer failed · ${e?.message||e}`,'error');}
function dispose(o){if(!o)return;o.traverse(x=>{if(x.geometry)x.geometry.dispose();if(x.material){if(Array.isArray(x.material))x.material.forEach(m=>m.dispose());else x.material.dispose();}});o.parent?.remove(o);}
function project(lon,lat){const b=S.geometry?.bounds||[84,93,16,24],midLat=(b[2]+b[3])/2,midLon=(b[0]+b[1])/2;return[(+lon-midLon)*111.32*Math.cos(midLat*Math.PI/180),(+lat-(b[2]+b[3])/2)*111.32];}
function depthY(m){return -Math.max(0,+m)*S.depthEx/1000;}
function terrainDepthAt(lon,lat){const t=S.geometry?.terrain;if(!t?.x?.length||!t?.y?.length)return 0;const p=project(lon,lat),nx=t.x.length,ny=t.y.length,ix=clamp(Math.round((p[0]-t.x[0])/((t.x[nx-1]-t.x[0])||1)*(nx-1)),0,nx-1),iy=clamp(Math.round((p[1]-t.y[0])/((t.y[ny-1]-t.y[0])||1)*(ny-1)),0,ny-1),d=Number((t.rawDepthKm[iy]||[])[ix]);return finite(d)?Math.max(0,d*1000):0;}
function polygonGeometry(parts,y=0){const p=[],idx=[];let base=0;for(const part of parts||[]){for(const v of part.vertices||[])p.push(+v[0],y,+v[1]);for(const t of part.triangles||[])idx.push(base+t[0],base+t[1],base+t[2]);base+=(part.vertices||[]).length;}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setIndex(idx);g.computeVertexNormals();return g;}
function lineGeometry(parts,y=0){const p=[];for(const l of parts||[])for(let i=0;i<l.length-1;i++)p.push(+l[i][0],y,+l[i][1],+l[i+1][0],y,+l[i+1][1]);const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));return g;}
function cellBounds(a,i){if(a.length===1)return[a[i]-.025,a[i]+.025];if(i===0)return[a[0]-(a[1]-a[0])/2,(a[0]+a[1])/2];if(i===a.length-1)return[(a[i-1]+a[i])/2,a[i]+(a[i]-a[i-1])/2];return[(a[i-1]+a[i])/2,(a[i]+a[i+1])/2];}

function drawLand(){dispose(S.land);dispose(S.coast);const g=S.geometry;if(!g)return;S.land=new THREE.Mesh(polygonGeometry([...(g.land||[]),...(g.islands||[])],0.12),new THREE.MeshStandardMaterial({color:0x43a447,roughness:1,side:THREE.DoubleSide}));S.land.renderOrder=50;S.root.add(S.land);S.coast=new THREE.LineSegments(lineGeometry([...(g.coast||[]),...(g.landBoundary||[]),...(g.islandCoast||[])],0.2),new THREE.LineBasicMaterial({color:0x123a20}));S.coast.renderOrder=70;S.root.add(S.coast);}
function drawSeabed(){dispose(S.seabed);const t=S.geometry?.terrain;if(!t?.x?.length||!t?.y?.length)return;const w=t.x.length,h=t.y.length,p=[],map=new Int32Array(w*h);map.fill(-1);for(let j=0;j<h;j++)for(let i=0;i<w;i++){const d=Number((t.rawDepthKm[j]||[])[i]);if(!finite(d))continue;map[j*w+i]=p.length/3;p.push(t.x[i],depthY(d),t.y[j]);}const idx=[];for(let j=0;j<h-1;j++)for(let i=0;i<w-1;i++){const a=map[j*w+i],b=map[j*w+i+1],c=map[(j+1)*w+i],d=map[(j+1)*w+i+1];if(a>=0&&b>=0&&c>=0&&d>=0)idx.push(a,c,b,b,c,d);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setIndex(idx);g.computeVertexNormals();S.seabed=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:0x76502c,roughness:1,side:THREE.DoubleSide}));S.seabed.renderOrder=5;S.root.add(S.seabed);}
function drawSurface(){dispose(S.surface);const o=S.geometry?.ocean||[];if(!o.length)return;S.surface=new THREE.Mesh(polygonGeometry(o,0.3),new THREE.MeshStandardMaterial({color:0x2b95ba,transparent:true,opacity:0.16,roughness:.4,depthWrite:false,side:THREE.DoubleSide}));S.surface.renderOrder=35;S.root.add(S.surface);}

function parseField(packet){const dims=packet.dimensions||[],shape=packet.shape||[],c=packet.coordinates||{};const la=dims.find(d=>LAT_NAMES.has(d)),lo=dims.find(d=>LON_NAMES.has(d)),de=dims.find(d=>DEPTH_NAMES.has(d));if(!la||!lo)throw Error('Field has no latitude/longitude dimensions');const lat=(c[la]||[]).map(Number),lon=(c[lo]||[]).map(Number),dep=de?(c[de]||[]).map(Number):[0],raw=flat(packet.data||[]).map(Number);const st=new Array(shape.length);let q=1;for(let i=shape.length-1;i>=0;i--){st[i]=q;q*=shape[i];}const li=dims.indexOf(la),xi=dims.indexOf(lo),zi=de?dims.indexOf(de):-1,ys=lat.map((v,i)=>[v,i]).sort((a,b)=>a[0]-b[0]),xs=lon.map((v,i)=>[v,i]).sort((a,b)=>a[0]-b[0]),zs=dep.map((v,i)=>[Math.abs(v),i]).sort((a,b)=>a[0]-b[0]);const w=xs.length,h=ys.length,z=zs.length,values=new Float32Array(w*h*z);values.fill(NaN);const at=(x,j,k)=>{let n=0;for(let d=0;d<dims.length;d++){const r=d===xi?x:d===li?j:d===zi?k:0;n+=r*st[d];}return n;};const valid=[];for(let k=0;k<z;k++)for(let j=0;j<h;j++)for(let i=0;i<w;i++){const v=Number(raw[at(xs[i][1],ys[j][1],zi<0?0:zs[k][1])]);values[k*w*h+j*w+i]=v;if(finite(v))valid.push(v);}return{width:w,height:h,depth:z,lon:xs.map(v=>v[0]),lat:ys.map(v=>v[0]),levels:zs.map(v=>v[0]),values,valid};}

function buildWater(d){dispose(S.water);S.water=null;S.waterMeshes=[];const w=d.width,h=d.height,sp=w*h,levels=d.levels;S.water=new THREE.Group();S.water.renderOrder=20;const box=new THREE.BoxGeometry(1,1,1);for(let k=0;k<d.depth;k++){const top=k===0?0:levels[k-1];const nominal=k<d.depth-1?levels[k]:null;const cells=[];for(let j=0;j<h;j++)for(let i=0;i<w;i++){let v=d.values[k*sp+j*w+i];if(!finite(v)){for(let q=1;q<d.depth&&!finite(v);q++){const a=k-q>=0?d.values[(k-q)*sp+j*w+i]:NaN;const b=k+q<d.depth?d.values[(k+q)*sp+j*w+i]:NaN;if(finite(a))v=a;else if(finite(b))v=b;}}if(!finite(v))continue;const localBottom=terrainDepthAt(d.lon[i],d.lat[j]);if(localBottom<=top+0.1)continue;const bottom=nominal==null?localBottom:Math.min(nominal,localBottom);if(bottom<=top+0.1)continue;const xb=cellBounds(d.lon,i),zb=cellBounds(d.lat,j),x0=project(xb[0],d.lat[j])[0],x1=project(xb[1],d.lat[j])[0],z0=project(d.lon[i],zb[0])[1],z1=project(d.lon[i],zb[1])[1];cells.push({x:(x0+x1)/2,z:(z0+z1)/2,sx:Math.abs(x1-x0)*1.04,sz:Math.abs(z1-z0)*1.04,y:depthY((top+bottom)/2),sy:Math.max(.12,Math.abs(depthY(bottom)-depthY(top))),lon:d.lon[i],lat:d.lat[j],depth:(top+bottom)/2});}
if(!cells.length)continue;const mat=new THREE.MeshPhysicalMaterial({color:0x2b9bc4,transparent:true,opacity:k===0?.28:.22,roughness:.3,metalness:0,clearcoat:.12,depthWrite:false,side:THREE.DoubleSide});const mesh=new THREE.InstancedMesh(box,mat,cells.length);const dummy=new THREE.Object3D();for(let i=0;i<cells.length;i++){const c=cells[i];dummy.position.set(c.x,c.y,c.z);dummy.scale.set(Math.max(.1,c.sx),c.sy,Math.max(.1,c.sz));dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix);}mesh.instanceMatrix.needsUpdate=true;mesh.userData={cells,isWater:true};mesh.renderOrder=20+k;S.water.add(mesh);S.waterMeshes.push(mesh);}box.dispose();S.root.add(S.water);}

function renderVariableButtons(){const host=$('vars');if(!host)return;host.innerHTML='';for(const x of S.catalog){const b=document.createElement('button');b.className=`var ${x.id===S.active?'active':''} ${x.available===false?'off':''}`;b.disabled=x.available===false;b.dataset.field=x.id;b.innerHTML=`<span class="vicon">${x.id==='temperature'?'T':x.id==='salinity'?'S':x.id==='currents'?'C':x.id==='sea_level'?'η':x.id==='chlorophyll'?'Ch':'Δ'}</span><span><b>${x.label||LABEL[x.id]||x.id}</b><small>${x.units||'—'}</small></span><span class="dot"></span>`;host.appendChild(b);}}

function fmt(v,unit=''){return finite(v)?`${Math.abs(Number(v))<1?Number(v).toFixed(5):Number(v).toFixed(2)} ${unit}`:'—';}
async function pointInfo(lon,lat){try{const q=new URLSearchParams({lon:String(lon),lat:String(lat)});if(S.times[S.ti])q.set('time',S.times[S.ti]);const p=await get(`/ocean/point?${q}`);const v=p?.values||p||{};$('coords').textContent=`${Number(lat).toFixed(4)}° N · ${Number(lon).toFixed(4)}° E`;$('readoutGrid').innerHTML=[['Temperature',v.temperature,'°C'],['Salinity',v.salinity,'PSU'],['Chlorophyll',v.chlorophyll,'mg m⁻³'],['Sea level',v.sea_level??v.seaLevel,'m'],['SST anomaly',v.temperature_anomaly??v.sst_anomaly,'°C']].map(r=>`<div class="rval"><b>${r[0]}</b><span>${fmt(r[1],r[2])}</span></div>`).join('');$('readoutTime').textContent=p?.time||S.times[S.ti]||'Current time';$('readout').classList.remove('hidden');S.anchor={lon,lat};}catch(e){status(`Point lookup failed · ${e.message}`,'error');}}
function raycast(e){const r=S.renderer.domElement.getBoundingClientRect();S.mouse.x=((e.clientX-r.left)/r.width)*2-1;S.mouse.y=-((e.clientY-r.top)/r.height)*2+1;S.ray.setFromCamera(S.mouse,S.camera);const hit=S.ray.intersectObjects(S.waterMeshes,true).find(h=>h.object?.userData?.isWater&&h.instanceId!=null);if(hit){const c=hit.object.userData.cells[hit.instanceId];if(c)pointInfo(c.lon,c.lat);}}

async function loadField(){const token=++S.request;const item=S.catalog.find(x=>x.id===S.active);if(!item||item.available===false){status(`${LABEL[S.active]||S.active} unavailable`,'error');return;}status(`Loading ${LABEL[S.active]||S.active}…`,'busy');const m=await get(`/metadata/${encodeURIComponent(item.file)}`);const c=m.coordinates||{},la=c.latitude||c.lat,lo=c.longitude||c.lon;if(!la||!lo)throw Error('No geographic bounds in metadata');const v=(m.variables||[]).find(x=>x.name===item.variable),dims=v?.dimensions||[],shape=v?.shape||[];let li=-1,xi=-1;dims.forEach((d,i)=>{if(LAT_NAMES.has(d))li=i;if(LON_NAMES.has(d))xi=i;});const grid=li>=0&&xi>=0?(shape[li]||1)*(shape[xi]||1):1,stride=grid>3600?5:grid>2200?4:grid>1200?3:grid>600?2:1;const q=new URLSearchParams({file:item.file,variable:item.variable,lat_min:String(la.min),lat_max:String(la.max),lon_min:String(lo.min),lon_max:String(lo.max),stride:String(stride)});if(S.times[S.ti]){q.set('time_start',S.times[S.ti]);q.set('time_end',S.times[S.ti]);}const d=parseField(await get(`/data/region/array?${q}`));if(token!==S.request)return;S.descriptor=d;buildWater(d);if($('depthSection'))$('depthSection').classList.add('hidden');$('loading')?.classList.add('hidden');status(`${LABEL[S.active]||S.active} · physical water volume`);}

function fit(){const b=new THREE.Box3().setFromObject(S.root);if(b.isEmpty())return;const c=b.getCenter(new THREE.Vector3()),s=b.getSize(new THREE.Vector3()),r=Math.max(s.x,s.y,s.z);S.controls.target.copy(c);S.camera.position.set(c.x+r*1.15,c.y+r*.68,c.z+r*1.2);S.camera.lookAt(c);S.controls.update();}
function updateTimeUI(){const t=S.times[S.ti]||'';if($('timeValue'))$('timeValue').textContent=t?new Date(t).toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'}):'Ocean time';if($('timeRaw'))$('timeRaw').textContent=t||'—';if($('timeSlider')){$('timeSlider').max=Math.max(0,S.times.length-1);$('timeSlider').value=S.ti;}if($('timeCount'))$('timeCount').textContent=`${S.ti+1}/${Math.max(1,S.times.length)}`;}
function setupUI(){
$('vars')?.addEventListener('click',async e=>{const b=e.target.closest('[data-field]');if(!b||b.disabled)return;S.active=b.dataset.field;renderVariableButtons();try{await loadField();}catch(err){fail(err);}});
$('views')?.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(!b)return;const box=new THREE.Box3().setFromObject(S.root),c=box.getCenter(new THREE.Vector3()),s=box.getSize(new THREE.Vector3()),r=Math.max(s.x,s.y,s.z);const v=b.dataset.view;if(v==='top')S.camera.position.set(c.x,c.y+r*1.5,c.z+.01);else if(v==='profile')S.camera.position.set(c.x+r*1.5,c.y,c.z);else if(v==='under')S.camera.position.set(c.x,c.y-r*1.2,c.z+.01);else{S.camera.position.set(c.x+r*1.15,c.y+r*.68,c.z+r*1.2);}S.controls.target.copy(c);S.controls.update();document.querySelectorAll('#views .view[data-view]').forEach(x=>x.classList.toggle('active',x===b));});
$('reset')?.addEventListener('click',fit);$('fullscreen')?.addEventListener('click',()=>document.documentElement.requestFullscreen?.());$('closeReadout')?.addEventListener('click',()=>$('readout')?.classList.add('hidden'));$('renderCanvas')?.addEventListener('pointerdown',e=>{if(e.button===0)raycast(e)});
$('exaggeration')?.addEventListener('input',e=>{S.depthEx=Number(e.target.value);if($('exagValue'))$('exagValue').textContent=`${S.depthEx}×`;drawSeabed();drawLand();drawSurface();if(S.descriptor)buildWater(S.descriptor);fit();});
$('play')?.addEventListener('click',()=>{S.playing=!S.playing;$('play').textContent=S.playing?'PAUSE':'PLAY';});
$('timeSlider')?.addEventListener('input',async e=>{S.ti=Number(e.target.value);updateTimeUI();try{await loadField();}catch(err){status(err.message,'error');}});
window.addEventListener('resize',()=>{S.camera.aspect=innerWidth/innerHeight;S.camera.updateProjectionMatrix();S.renderer.setSize(innerWidth,innerHeight);});
updateTimeUI();}

async function init(){S.geometry=await staticGet('/geometry.json');const [catalog,times]=await Promise.all([get('/ocean/catalog'),get('/ocean/time')]);S.catalog=catalog.variables||catalog||[];S.times=Array.isArray(times)?times:(times.times||[]);S.scene=new THREE.Scene();S.scene.background=new THREE.Color(0xb9dce8);S.camera=new THREE.PerspectiveCamera(40,innerWidth/innerHeight,.1,100000);S.renderer=new THREE.WebGLRenderer({canvas:$('renderCanvas'),antialias:true});S.renderer.setPixelRatio(Math.min(devicePixelRatio,2));S.renderer.setSize(innerWidth,innerHeight);S.renderer.outputColorSpace=THREE.SRGBColorSpace;S.renderer.shadowMap.enabled=true;S.scene.add(new THREE.HemisphereLight(0xffffff,0x557078,1.6));const light=new THREE.DirectionalLight(0xffffff,2);light.position.set(500,1000,500);S.scene.add(light);S.root=new THREE.Group();S.scene.add(S.root);drawSeabed();drawLand();drawSurface();S.controls=new OrbitControls(S.camera,S.renderer.domElement);S.controls.enableDamping=true;S.controls.dampingFactor=.07;S.controls.minDistance=140;S.controls.maxDistance=4000;renderVariableButtons();setupUI();await loadField();fit();animate();}
function animate(ms=0){requestAnimationFrame(animate);if(S.playing&&S.times.length>1&&ms-S.lastPlay>700){S.lastPlay=ms;S.ti=(S.ti+1)%S.times.length;updateTimeUI();loadField().catch(e=>status(e.message,'error'));}S.controls?.update();S.renderer?.render(S.scene,S.camera);}
init().catch(fail);
