import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
const $=id=>document.getElementById(id), finite=v=>Number.isFinite(Number(v)), clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const API=`${location.protocol==='file:'?'http:':location.protocol}//${location.hostname||'127.0.0.1'}:8000`, DEPTH_NAMES=new Set(['depth','deptht','depthu','depthv','depthw','lev','level','z']), LAT_NAMES=new Set(['latitude','lat']), LON_NAMES=new Set(['longitude','lon']);
const LABEL={temperature:'Temperature',temperature_anomaly:'SST anomaly',salinity:'Salinity',currents:'Currents',sea_level:'Sea level',chlorophyll:'Chlorophyll'};
const PAL={temperature:[[0x062b9c,0],[0x008dff,.2],[0x00d9a8,.42],[0xffe600,.63],[0xff6a00,.82],[0xc40000,1]],temperature_anomaly:[[0x1646b8,0],[0x64b9e8,.25],[0xf7f7f7,.5],[0xff9b68,.75],[0xb71924,1]],salinity:[[0x09249a,0],[0x00a7ff,.25],[0x19d39b,.5],[0xffdc24,.75],[0xf06b00,1]],sea_level:[[0x1133a7,0],[0x00aaff,.25],[0x30d49b,.5],[0xffd322,.75],[0xc90000,1]],chlorophyll:[[0xf3fff0,0],[0xb9ee5d,.25],[0x39c844,.5],[0x078d39,.75],[0x003b20,1]],fallback:[[0x07339f,0],[0x00c8ff,.25],[0x20d38e,.5],[0xffdf21,.75],[0xc40000,1]]};
const S={scene:null,camera:null,renderer:null,controls:null,root:null,geometry:null,catalog:[],times:[],ti:0,active:'temperature',descriptor:null,range:null,land:null,coast:null,seabed:null,water:null,surface:null,currents:null,waterGroups:[],depthMode:'volume',sliceDepth:0,depthEx:10,playing:false,lastPlay:0,ray:new THREE.Raycaster(),mouse:new THREE.Vector2(),box:new THREE.BoxGeometry(1,1,1)};
async function get(p){const r=await fetch(API+p,{cache:'no-store'});if(!r.ok)throw Error(`${r.status} ${await r.text()}`);return r.json()} async function stat(p){const r=await fetch(p,{cache:'no-store'});if(!r.ok)throw Error(`${r.status}`);return r.json()}
function status(t,type='ok'){if($('status'))$('status').textContent=t;if($('statusDot'))$('statusDot').className=type==='error'?'error':type==='busy'?'busy':''} function fail(e){console.error(e);$('loading')?.classList.add('hidden');$('fatalText').textContent=e?.message||String(e);$('fatal').classList.add('show');status(`Viewer failed · ${e?.message||e}`,'error')}
function clear(o){if(!o)return;o.traverse(x=>{if(x.geometry&&x.geometry!==S.box)x.geometry.dispose();if(x.material){if(Array.isArray(x.material))x.material.forEach(m=>m.dispose());else x.material.dispose()}});o.parent?.remove(o)}
function pct(a,p){const v=[...a].sort((x,y)=>x-y),q=(v.length-1)*p,i=Math.floor(q),j=Math.ceil(q);return v[i]+(v[j]-v[i])*(q-i)}
function color(v){const s=PAL[S.active]||PAL.fallback,t=clamp((v-S.range.lo)/(S.range.hi-S.range.lo||1),0,1);let a=s[0],b=s.at(-1);for(let i=0;i<s.length-1;i++)if(t<=s[i+1][1]){a=s[i];b=s[i+1];break}const u=(t-a[1])/(b[1]-a[1]||1);return new THREE.Color(a[0]).lerp(new THREE.Color(b[0]),u)}
function poly(parts,y){const p=[],idx=[];let base=0;for(const part of parts||[]){for(const v of part.vertices||[])p.push(+v[0],y,+v[1]);for(const t of part.triangles||[])idx.push(base+t[0],base+t[1],base+t[2]);base+=(part.vertices||[]).length}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setIndex(idx);return g}
function lines(ls,y){const p=[];for(const l of ls||[])for(let i=0;i<l.length-1;i++)p.push(+l[i][0],y,+l[i][1],+l[i+1][0],y,+l[i+1][1]);const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));return g}
function project(lon,lat){const b=S.geometry?.bounds||[84,93,16,24],m=(b[2]+b[3])/2;return[(lon-(b[0]+b[1])/2)*111.32*Math.cos(m*Math.PI/180),(lat-(b[2]+b[3])/2)*111.32]}
function y(depth){return -Math.max(0,depth)*S.depthEx/1000}
function bathy(lon,lat){const t=S.geometry?.terrain;if(!t?.x?.length)return 0;const p=project(lon,lat),nx=t.x.length,ny=t.y.length,ix=clamp(Math.round((p[0]-t.x[0])/((t.x[nx-1]-t.x[0])||1)*(nx-1)),0,nx-1),iy=clamp(Math.round((p[1]-t.y[0])/((t.y[ny-1]-t.y[0])||1)*(ny-1)),0,ny-1),d=Number((t.rawDepthKm[iy]||[])[ix]);return finite(d)?Math.max(0,d*1000):0}
function bounds(a,i){if(a.length===1)return[a[i]-.05,a[i]+.05];if(i===0)return[a[0]-(a[1]-a[0])/2,(a[0]+a[1])/2];if(i===a.length-1)return[(a[i-1]+a[i])/2,a[i]+(a[i]-a[i-1])/2];return[(a[i-1]+a[i])/2,(a[i]+a[i+1])/2]}
function drawLand(){clear(S.land);clear(S.coast);const g=S.geometry;S.land=new THREE.Mesh(poly([...(g.land||[]),...(g.islands||[])],.08),new THREE.MeshBasicMaterial({color:0x43a64b,side:THREE.DoubleSide}));S.land.renderOrder=40;S.root.add(S.land);S.coast=new THREE.LineSegments(lines([...(g.coast||[]),...(g.landBoundary||[]),...(g.islandCoast||[])],.14),new THREE.LineBasicMaterial({color:0x092d18}));S.coast.renderOrder=50;S.root.add(S.coast)}
function drawSeabed(){clear(S.seabed);const t=S.geometry?.terrain;if(!t?.x?.length)return;const w=t.x.length,h=t.y.length,p=[],map=new Int32Array(w*h);map.fill(-1);for(let j=0;j<h;j++)for(let i=0;i<w;i++){const d=Number((t.rawDepthKm[j]||[])[i]);if(!finite(d))continue;map[j*w+i]=p.length/3;p.push(t.x[i],-Math.max(0,d)*S.depthEx,t.y[j])}const idx=[];for(let j=0;j<h-1;j++)for(let i=0;i<w-1;i++){const a=map[j*w+i],b=map[j*w+i+1],c=map[(j+1)*w+i],d=map[(j+1)*w+i+1];if(a>=0&&b>=0&&c>=0&&d>=0)idx.push(a,c,b,b,c,d)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setIndex(idx);S.seabed=new THREE.Mesh(g,new THREE.MeshBasicMaterial({color:0x6b431f,side:THREE.DoubleSide}));S.seabed.renderOrder=1;S.root.add(S.seabed)}
function parse(packet){const dims=packet.dimensions||[],shape=packet.shape||[],c=packet.coordinates||{},la=dims.find(d=>LAT_NAMES.has(d)),lo=dims.find(d=>LON_NAMES.has(d)),de=dims.find(d=>DEPTH_NAMES.has(d));if(!la||!lo)throw Error('No latitude/longitude dimensions');const lat=(c[la]||[]).map(Number),lon=(c[lo]||[]).map(Number),dep=de?(c[de]||[]).map(Number):[0],raw=[];(function f(x){Array.isArray(x)?x.forEach(f):raw.push(x)})(packet.data||[]);const st=new Array(shape.length);let q=1;for(let i=shape.length-1;i>=0;i--){st[i]=q;q*=shape[i]}const li=dims.indexOf(la),xi=dims.indexOf(lo),zi=de?dims.indexOf(de):-1,ys=lat.map((v,i)=>[v,i]).sort((a,b)=>a[0]-b[0]),xs=lon.map((v,i)=>[v,i]).sort((a,b)=>a[0]-b[0]),zs=dep.map((v,i)=>[Math.abs(v),i]).sort((a,b)=>a[0]-b[0]),w=xs.length,h=ys.length,z=zs.length,values=new Float32Array(w*h*z);values.fill(NaN);const valid=[];const at=(x,j,k)=>{let n=0;for(let d=0;d<dims.length;d++){let r=d===xi?x:d===li?j:d===zi?k:0;n+=r*st[d]}return n};for(let k=0;k<z;k++)for(let j=0;j<h;j++)for(let i=0;i<w;i++){const v=Number(raw[at(xs[i][1],ys[j][1],zi<0?0:zs[k][1])]);values[k*w*h+j*w+i]=v;if(finite(v))valid.push(v)}return{width:w,height:h,depth:z,lon:xs.map(x=>x[0]),lat:ys.map(x=>x[0]),levels:zs.map(x=>x[0]),values,valid}}
function cellBounds(a,i){if(a.length===1)return[a[i]-.05,a[i]+.05];if(i===0)return[a[0]-(a[1]-a[0])/2,(a[0]+a[1])/2];if(i===a.length-1)return[(a[i-1]+a[i])/2,a[i]+(a[i]-a[i-1])/2];return[(a[i-1]+a[i])/2,(a[i]+a[i+1])/2]}
function buildWater(d){clear(S.water);S.waterGroups=[];S.water=new THREE.Group();const sp=d.width*d.height;const value=(k,i,j)=>{let v=d.values[k*sp+j*d.width+i];if(finite(v))return v;for(let q=1;q<d.depth;q++){if(k-q>=0&&finite(d.values[(k-q)*sp+j*d.width+i]))return d.values[(k-q)*sp+j*d.width+i];if(k+q<d.depth&&finite(d.values[(k+q)*sp+j*d.width+i]))return d.values[(k+q)*sp+j*d.width+i]}return NaN};for(let k=0;k<d.depth;k++){const top=k===0?0:(d.levels[k-1]+d.levels[k])/2,next=k<d.depth-1?(d.levels[k]+d.levels[k+1])/2:null,cells=[];for(let j=0;j<d.height;j++)for(let i=0;i<d.width;i++){const v=value(k,i,j);if(!finite(v))continue;const bottom=next??bathy(d.lon[i],d.lat[j]),th=bottom-top;if(th<=.2)continue;const xb=cellBounds(d.lon,i),zb=cellBounds(d.lat,j),x0=project(xb[0],d.lat[j])[0],x1=project(xb[1],d.lat[j])[0],z0=project(d.lon[i],zb[0])[1],z1=project(d.lon[i],zb[1])[1];cells.push({x:(x0+x1)/2,z:(z0+z1)/2,sx:Math.abs(x1-x0),sz:Math.abs(z1-z0),y:y((top+bottom)/2),sy:Math.max(.08,Math.abs(y(th))),value:v,lat:d.lat[j],lon:d.lon[i],depth:(top+bottom)/2})}if(!cells.length)continue;const mat=new THREE.MeshBasicMaterial({vertexColors:true,transparent:true,opacity:d.depth===1?.72:.36,depthWrite:false,side:THREE.DoubleSide});const mesh=new THREE.InstancedMesh(S.box,mat,cells.length),dummy=new THREE.Object3D();for(let i=0;i<cells.length;i++){const c=cells[i];dummy.position.set(c.x,c.y,c.z);dummy.scale.set(Math.max(.1,c.sx),Math.max(.05,c.sy),Math.max(.1,c.sz));dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix);mesh.setColorAt(i,color(c.value))}mesh.instanceMatrix.needsUpdate=true;mesh.instanceColor.needsUpdate=true;mesh.computeBoundingSphere();mesh.userData={cells,isWater:true};mesh.renderOrder=10+k;S.water.add(mesh);S.waterGroups.push({depth:top,mesh})}S.root.add(S.water);updateWater()}
function updateWater(){for(const g of S.waterGroups)g.mesh.visible=S.depthMode==='volume'||Math.abs(g.depth-S.sliceDepth)<=Math.max(3,(S.descriptor?.levels?.at(-1)||1)*.03)}
function domain(m){const c=m.coordinates||{},a=c.latitude||c.lat,b=c.longitude||c.lon;if(!a||!b)throw Error('No geographic coordinates');return{lat:[+a.min,+a.max],lon:[+b.min,+b.max]}}
function stride(m,n){const v=(m.variables||[]).find(x=>x.name===n),d=v?.dimensions||[],s=v?.shape||[],a=d.findIndex(x=>LAT_NAMES.has(x)),b=d.findIndex(x=>LON_NAMES.has(x)),g=a>=0&&b>=0?(s[a]||1)*(s[b]||1):1;return g>3600?5:g>2200?4:g>1200?3:g>600?2:1}
async function field(){const item=S.catalog.find(x=>x.id===S.active);if(!item?.available)return status(`${LABEL[S.active]} unavailable`,'error');status(`Loading ${LABEL[S.active]}…`,'busy');const m=await get(`/metadata/${encodeURIComponent(item.file)}`),b=domain(m),q=new URLSearchParams({file:item.file,variable:item.variable,lat_min:b.lat[0],lat_max:b.lat[1],lon_min:b.lon[0],lon_max:b.lon[1],stride:String(stride(m,item.variable))});if(S.times[S.ti]){q.set('time_start',S.times[S.ti]);q.set('time_end',S.times[S.ti])}const d=parse(await get(`/data/region/array?${q}`));if(!d.valid.length)throw Error('No finite values returned');S.descriptor=d;let lo=pct(d.valid,.01),hi=pct(d.valid,.99);if(S.active==='temperature_anomaly'){const z=Math.max(Math.abs(lo),Math.abs(hi));lo=-z;hi=z}if(!(hi>lo)){lo-=1e-6;hi+=1e-6}S.range={lo,hi};$('legendLo').textContent=lo.toPrecision(5);$('legendHi').textContent=hi.toPrecision(5);$('legendNote').textContent=`1–99 percentile · ${d.valid.length.toLocaleString()} finite samples`;$('depthSection').classList.toggle('hidden',d.depth<=1);if(d.depth>1){const max=d.levels.at(-1)||1;$('depthMax').textContent=`${max.toFixed(0)} m`;$('depthSlider').max=max;S.sliceDepth=clamp(S.sliceDepth,0,max);$('depthSlider').value=S.sliceDepth}else S.sliceDepth=0;buildWater(d);$('loading').classList.add('hidden');status(`${LABEL[S.active]} · ${d.depth} depth level${d.depth===1?'':'s'}`);updateBadge()}
function updateBadge(){$('depthValue').textContent=S.depthMode==='volume'?'Volume':`${S.sliceDepth.toFixed(0)} m`;$('depthBadge').textContent=S.depthMode==='volume'?'Volume':`${S.sliceDepth.toFixed(0)} m`}
function buttons(){const b=$('vars');b.innerHTML='';for(const x of S.catalog){const e=document.createElement('button');e.className=`field ${x.id===S.active?'active':''}`;e.dataset.field=x.id;e.disabled=!x.available;e.innerHTML=`<b>${x.label||LABEL[x.id]}</b><small>${x.units||'—'}</small><i></i>`;b.appendChild(e)}}
function setup(){ $('vars').addEventListener('click',e=>{const b=e.target.closest('[data-field]');if(!b||b.disabled)return;document.querySelectorAll('[data-field]').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.active=b.dataset.field;field().catch(fail)});$('depthMode').addEventListener('click',e=>{const b=e.target.closest('[data-depth-mode]');if(!b)return;document.querySelectorAll('#depthMode button').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.depthMode=b.dataset.depthMode;updateWater();updateBadge()});$('depthSlider').addEventListener('input',e=>{S.sliceDepth=+e.target.value;updateWater();updateBadge()});$('exaggeration').addEventListener('input',e=>{S.depthEx=+e.target.value;$('exagValue').textContent=`${S.depthEx}×`;drawSeabed();buildWater(S.descriptor);fit()});document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));if(b.dataset.view){b.classList.add('active');view(b.dataset.view)}}));$('reset').addEventListener('click',fit);$('fullscreen').addEventListener('click',()=>document.fullscreenElement?document.exitFullscreen?.():document.documentElement.requestFullscreen?.());$('play').addEventListener('click',()=>{S.playing=!S.playing;$('play').textContent=S.playing?'PAUSE':'PLAY';S.lastPlay=0});$('timeSlider').addEventListener('input',e=>{S.ti=+e.target.value;timeline();field().catch(fail)});$('closeReadout').addEventListener('click',()=>$('readout').classList.add('hidden'));$('renderCanvas').addEventListener('pointerdown',click);addEventListener('resize',()=>{S.camera.aspect=innerWidth/innerHeight;S.camera.updateProjectionMatrix();S.renderer.setSize(innerWidth,innerHeight,false)})}
function fit(){const b=S.geometry.bounds,m=(b[2]+b[3])/2,w=(b[1]-b[0])*111.32*Math.cos(m*Math.PI/180),h=(b[3]-b[2])*111.32,d=Math.max(80,(S.geometry.terrain?.maxDepthKm||1)*S.depthEx),r=Math.max(w,h,d,100);S.camera.position.set(r*.9,r*.62,r*1.02);S.controls.target.set(0,-Math.min(d*.2,r*.25),0);S.camera.far=r*30;S.camera.updateProjectionMatrix();S.controls.update()}
function view(v){const b=S.geometry.bounds,m=(b[2]+b[3])/2,w=(b[1]-b[0])*111.32*Math.cos(m*Math.PI/180),h=(b[3]-b[2])*111.32,d=Math.max(80,(S.geometry.terrain?.maxDepthKm||1)*S.depthEx),r=Math.max(w,h,d);if(v==='top')S.camera.position.set(0,r*1.35,.01);else if(v==='profile')S.camera.position.set(r*1.35,-r*.08,0);else if(v==='under')S.camera.position.set(0,-r*.8,r*.75);else S.camera.position.set(r,r*.58,r);S.controls.target.set(0,v==='top'?0:-Math.min(d*.2,r*.25),0);S.controls.update()}
function timeline(){if(!S.times.length)return;const d=new Date(S.times[S.ti]);$('timeValue').textContent=d.toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'});$('timeRaw').textContent=d.toISOString();$('timeCount').textContent=`${S.ti+1}/${S.times.length}`}
function click(e){const r=$('renderCanvas').getBoundingClientRect();S.mouse.x=(e.clientX-r.left)/r.width*2-1;S.mouse.y=-(e.clientY-r.top)/r.height*2+1;S.ray.setFromCamera(S.mouse,S.camera);const a=[];S.water?.traverse(o=>{if(o.userData?.isWater&&o.visible)a.push(o)});const h=S.ray.intersectObjects(a,false)[0];if(!h)return;const c=h.object.userData.cells?.[h.instanceId];if(!c)return;const q=new URLSearchParams({latitude:c.lat,longitude:c.lon});if(S.times[S.ti])q.set('time',S.times[S.ti]);get(`/ocean/point?${q}`).then(d=>{$('coords').textContent=`${c.lat.toFixed(4)}° N · ${c.lon.toFixed(4)}° E · ${c.depth.toFixed(0)} m`;$('readoutGrid').innerHTML='';for(const x of d.values||[]){if(!x.available)continue;let v=x.value;if(v&&typeof v==='object'){const z=Object.values(v).filter(finite).map(Number);v=z.length?Math.hypot(...z):'—'}if(!finite(v))v='—';const e=document.createElement('div');e.className='readoutCard';e.innerHTML=`<b>${x.label}</b><strong>${typeof v==='number'?v.toFixed(4):v}</strong><small>${x.units||'—'}</small>`;$('readoutGrid').appendChild(e)}$('readout').classList.remove('hidden')}).catch(console.warn)}
function renderer(){const c=$('renderCanvas');S.renderer=new THREE.WebGLRenderer({canvas:c,antialias:true,powerPreference:'high-performance'});S.renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));S.renderer.setSize(innerWidth,innerHeight,false);S.renderer.setClearColor(0xaedce6,1);S.renderer.outputColorSpace=THREE.SRGBColorSpace;S.scene=new THREE.Scene();S.camera=new THREE.PerspectiveCamera(46,innerWidth/innerHeight,.1,10000);S.controls=new OrbitControls(S.camera,c);S.controls.enableDamping=true;S.controls.screenSpacePanning=true;S.controls.maxDistance=10000;S.root=new THREE.Group();S.scene.add(S.root);S.scene.add(new THREE.HemisphereLight(0xd7f5ff,0x50351f,1.4),new THREE.DirectionalLight(0xffffff,1.2))}
function loop(t=0){requestAnimationFrame(loop);if(S.playing&&S.times.length>1&&t-S.lastPlay>700){S.lastPlay=t;S.ti=(S.ti+1)%S.times.length;$('timeSlider').value=S.ti;timeline();field().catch(fail)}S.controls?.update();S.renderer?.render(S.scene,S.camera)}
async function init(){renderer();setup();status('Loading land, coastline and GEBCO seabed…','busy');S.geometry=await stat('geometry.json');if(!S.geometry?.land||!S.geometry?.terrain)throw Error('geometry.json must contain land and terrain');drawLand();drawSeabed();fit();const [cat,t]=await Promise.all([get('/ocean/catalog'),get('/ocean/time')]);S.catalog=cat.variables||[];S.times=t.values||[];buttons();$('timeSlider').max=Math.max(0,S.times.length-1);timeline();await field()}
init().catch(fail);loop();