import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

const $ = (id) => document.getElementById(id);
const API = `${location.protocol === 'file:' ? 'http:' : location.protocol}//${location.hostname || '127.0.0.1'}:8000`;
const finite = (v) => Number.isFinite(Number(v));

const S = {scene:null,camera:null,renderer:null,controls:null,root:null,geometry:null,land:null,landSides:null,landBottom:null,coast:null,seabed:null,water:null,surface:null,catalog:[],times:[],ti:0,active:'temperature',depthEx:10,ray:new THREE.Raycaster(),mouse:new THREE.Vector2(),playing:false,lastPlay:0};

async function getJSON(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${await r.text()}`);return r.json()}
function setStatus(text,type='ok'){if($('status'))$('status').textContent=text;if($('statusDot'))$('statusDot').className=type==='error'?'error':type==='busy'?'busy':''}
function fail(err){console.error(err);$('loading')?.classList.add('hidden');if($('fatalText'))$('fatalText').textContent=err?.message||String(err);$('fatal')?.classList.add('show');setStatus(`Viewer failed · ${err?.message||err}`,'error')}
function dispose(o){if(!o)return;o.traverse(x=>{if(x.geometry)x.geometry.dispose();if(x.material){if(Array.isArray(x.material))x.material.forEach(m=>m.dispose());else x.material.dispose()}});o.parent?.remove(o)}
function project(lon,lat){const b=S.geometry.bounds,midLat=(b[2]+b[3])/2,kmLat=111.32,kmLon=111.32*Math.cos(midLat*Math.PI/180);return[(Number(lon)-(b[0]+b[1])/2)*kmLon,(Number(lat)-(b[2]+b[3])/2)*kmLat]}
function depthZ(m){return-Math.max(0,Number(m))*S.depthEx/1000}
function lineGeometry(lines,z){const p=[];for(const l of lines||[])for(let i=0;i<l.length-1;i++)p.push(l[i][0],l[i][1],z,l[i+1][0],l[i+1][1],z);const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));return g}
function polygonGeometry(parts,z){const p=[],idx=[];let base=0;for(const part of parts||[]){for(const v of part.vertices||[])p.push(Number(v[0]),Number(v[1]),z);for(const t of part.triangles||[])idx.push(base+t[0],base+t[1],base+t[2]);base+=(part.vertices||[]).length}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setIndex(idx);g.computeVertexNormals();return g}

function drawLand(){dispose(S.land);dispose(S.landSides);dispose(S.landBottom);const parts=[...(S.geometry.land||[]),...(S.geometry.islands||[])],top=.35,thickness=Math.max(2,Number(S.geometry.landThickness||3)*S.depthEx/1000),bottom=top-thickness;S.land=new THREE.Mesh(polygonGeometry(parts,top),new THREE.MeshStandardMaterial({color:0x3f9a45,roughness:.95,side:THREE.DoubleSide}));S.land.renderOrder=50;S.root.add(S.land);const pos=[],idx=[];for(const part of parts){const ring=part.top||[];for(let i=0;i<ring.length-1;i++){const a=ring[i],b=ring[i+1],q=pos.length/3;pos.push(a[0],a[1],top,a[0],a[1],bottom,b[0],b[1],top,b[0],b[1],bottom);idx.push(q,q+2,q+1,q+2,q+3,q+1)}}const sg=new THREE.BufferGeometry();sg.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));sg.setIndex(idx);sg.computeVertexNormals();S.landSides=new THREE.Mesh(sg,new THREE.MeshStandardMaterial({color:0x76502f,roughness:1,side:THREE.DoubleSide}));S.landSides.renderOrder=48;S.root.add(S.landSides);S.landBottom=new THREE.Mesh(polygonGeometry(parts,bottom),new THREE.MeshStandardMaterial({color:0x593b28,roughness:1,side:THREE.DoubleSide}));S.landBottom.renderOrder=47;S.root.add(S.landBottom)}
function drawCoast(){dispose(S.coast);const lines=[...(S.geometry.coast||[]),...(S.geometry.landBoundary||[]),...(S.geometry.islandCoast||[])];S.coast=new THREE.LineSegments(lineGeometry(lines,.5),new THREE.LineBasicMaterial({color:0x09281b}));S.coast.renderOrder=80;S.root.add(S.coast)}
function drawSeabed(){dispose(S.seabed);const t=S.geometry.terrain,nx=t.x.length,ny=t.y.length,pos=[],idx=[],map=new Int32Array(nx*ny);map.fill(-1);for(let j=0;j<ny;j++)for(let i=0;i<nx;i++){const d=Number((t.rawDepthKm[j]||[])[i]);if(!finite(d))continue;map[j*nx+i]=pos.length/3;pos.push(t.x[i],t.y[j],depthZ(d*1000))}for(let j=0;j<ny-1;j++)for(let i=0;i<nx-1;i++){const a=map[j*nx+i],b=map[j*nx+i+1],c=map[(j+1)*nx+i],d=map[(j+1)*nx+i+1];if(a>=0&&b>=0&&c>=0&&d>=0)idx.push(a,c,b,b,c,d)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setIndex(idx);g.computeVertexNormals();S.seabed=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:0x80542f,roughness:.98,side:THREE.DoubleSide}));S.seabed.renderOrder=5;S.root.add(S.seabed)}

function buildWater(){dispose(S.water);S.water=new THREE.Group();const t=S.geometry.terrain,nx=t.x.length,ny=t.y.length,raw=t.rawDepthKm,step=Math.max(1,Math.ceil(Math.sqrt(nx*ny/14000))),cells=[];for(let j=0;j<ny-1;j+=step)for(let i=0;i<nx-1;i+=step){const i2=Math.min(nx-1,i+step),j2=Math.min(ny-1,j+step),ds=[];for(let y=j;y<=j2;y++)for(let x=i;x<=i2;x++){const d=Number((raw[y]||[])[x]);if(finite(d))ds.push(d)}if(!ds.length)continue;const depthKm=Math.min(...ds);if(depthKm<=.01)continue;const x0=t.x[i],x1=t.x[i2],y0=t.y[j],y1=t.y[j2],h=Math.abs(depthZ(depthKm*1000));if(h<.08)continue;cells.push({x:(x0+x1)/2,y:(y0+y1)/2,sx:Math.max(.25,Math.abs(x1-x0)*.98),sy:Math.max(.25,Math.abs(y1-y0)*.98),h,depthKm})}if(!cells.length)throw new Error('Could not construct ocean water volume');const box=new THREE.BoxGeometry(1,1,1),mat=new THREE.MeshPhysicalMaterial({color:0x278faf,transparent:true,opacity:.27,roughness:.18,metalness:0,transmission:.05,ior:1.333,depthWrite:false,side:THREE.DoubleSide}),mesh=new THREE.InstancedMesh(box,mat,cells.length),dummy=new THREE.Object3D();for(let n=0;n<cells.length;n++){const c=cells[n];dummy.position.set(c.x,c.y,-c.h/2);dummy.scale.set(c.sx,c.sy,c.h);dummy.updateMatrix();mesh.setMatrixAt(n,dummy.matrix)}mesh.instanceMatrix.needsUpdate=true;mesh.userData={isWater:true,cells};mesh.renderOrder=20;S.water.add(mesh);S.root.add(S.water);box.dispose()}
function drawSurface(){dispose(S.surface);const b=S.geometry.bounds,mid=(b[2]+b[3])/2,W=(b[1]-b[0])*111.32*Math.cos(mid*Math.PI/180),H=(b[3]-b[2])*111.32,g=new THREE.PlaneGeometry(W,H);g.rotateX(-Math.PI/2);S.surface=new THREE.Mesh(g,new THREE.MeshPhysicalMaterial({color:0x2a94b7,transparent:true,opacity:.08,roughness:.2,transmission:.05,ior:1.333,depthWrite:false,side:THREE.DoubleSide}));S.surface.position.z=.55;S.surface.renderOrder=60;S.root.add(S.surface)}

function renderVariables(){const host=$('vars');if(!host)return;host.innerHTML='';const icons={temperature:'T',temperature_anomaly:'∆',salinity:'S',currents:'C',sea_level:'η',chlorophyll:'Ch'};for(const item of S.catalog){const b=document.createElement('button');b.className=`var ${item.id===S.active?'active':''} ${item.available===false?'off':''}`;b.dataset.field=item.id;b.disabled=item.available===false;b.innerHTML=`<span class="vicon">${icons[item.id]||'•'}</span><span><b>${item.label||item.id}</b><small>${item.units||'inspection only'}</small></span><span class="dot"></span>`;b.onclick=()=>{S.active=item.id;renderVariables();setStatus(`${item.label||item.id} · inspection only`)};host.appendChild(b)}}
function fmt(v,u){if(!finite(v))return'—';const n=Number(v);return`${n.toFixed(Math.abs(n)<1?4:2)} ${u||''}`.trim()}
function showPoint(data,lon,lat){const v=data?.values||data||{};$('coords').textContent=`${Number(lat).toFixed(4)}° N · ${Number(lon).toFixed(4)}° E`;const rows=[['Temperature',v.temperature,'°C'],['Salinity',v.salinity,'PSU'],['Chlorophyll',v.chlorophyll,'mg m⁻³'],['Sea level',v.sea_level??v.seaLevel,'m'],['SST anomaly',v.temperature_anomaly??v.sst_anomaly,'°C']];$('readoutGrid').innerHTML=rows.map(([n,x,u])=>`<div class="rval"><b>${n}</b><span>${fmt(x,u)}</span></div>`).join('');$('readoutTime').textContent=data?.time||S.times[S.ti]||'Current time';$('readout')?.classList.remove('hidden')}
async function inspect(lon,lat){try{setStatus('Reading ocean point…','busy');const q=new URLSearchParams({lon:String(lon),lat:String(lat)});if(S.times[S.ti])q.set('time',S.times[S.ti]);showPoint(await getJSON(`/ocean/point?${q}`),lon,lat);setStatus('Ocean point inspected')}catch(e){setStatus(`Point lookup failed · ${e.message}`,'error')}}
function clickOcean(e){if(!S.renderer||!S.camera||!S.water)return;const r=S.renderer.domElement.getBoundingClientRect();S.mouse.x=(e.clientX-r.left)/r.width*2-1;S.mouse.y=-(e.clientY-r.top)/r.height*2+1;S.ray.setFromCamera(S.mouse,S.camera);const hit=S.ray.intersectObjects(S.water.children,true).find(h=>h.object?.userData?.isWater&&h.instanceId!=null);if(!hit)return;const c=hit.object.userData.cells[hit.instanceId],b=S.geometry.bounds,mid=(b[2]+b[3])/2,kmLon=111.32*Math.cos(mid*Math.PI/180);inspect((b[0]+b[1])/2+c.x/kmLon,(b[2]+b[3])/2+c.y/111.32)}

function setupUI(){ $('reset')?.addEventListener('click',fitCamera);$('fullscreen')?.addEventListener('click',()=>document.documentElement.requestFullscreen?.());$('closeReadout')?.addEventListener('click',()=>$('readout')?.classList.add('hidden'));$('renderCanvas')?.addEventListener('pointerdown',e=>{if(e.button===0)clickOcean(e)});$('exaggeration')?.addEventListener('input',e=>{S.depthEx=Number(e.target.value);if($('exagValue'))$('exagValue').textContent=`${S.depthEx}×`;drawLand();drawSeabed();buildWater();fitCamera()});$('play')?.addEventListener('click',()=>{S.playing=!S.playing;$('play').textContent=S.playing?'PAUSE':'PLAY'});$('timeSlider')?.addEventListener('input',e=>{S.ti=Number(e.target.value);updateTimeUI()})}
function setupViews(){if(!S.controls||!S.camera)return;document.querySelectorAll('#views .view').forEach(b=>b.onclick=()=>{const box=new THREE.Box3().setFromObject(S.root),c=box.getCenter(new THREE.Vector3()),s=box.getSize(new THREE.Vector3()),r=Math.max(s.x,s.y,s.z,1),v=b.dataset.view;if(v==='top')S.camera.position.set(c.x,c.y,c.z+r*1.55);else if(v==='profile')S.camera.position.set(c.x+r*1.55,c.y,c.z+.05*r);else if(v==='under')S.camera.position.set(c.x+r*.8,c.y,c.z-r*1.35);else{S.camera.position.set(c.x+r*1.12,c.y+r*.72,c.z+r*1.25)}S.controls.target.copy(c);S.controls.update();document.querySelectorAll('#views .view').forEach(x=>x.classList.remove('active'));b.classList.add('active')})}
function fitCamera(){if(!S.root||!S.controls||!S.camera)return;const box=new THREE.Box3().setFromObject(S.root);if(box.isEmpty())return;const c=box.getCenter(new THREE.Vector3()),s=box.getSize(new THREE.Vector3()),r=Math.max(s.x,s.y,s.z,1);S.controls.target.copy(c);S.camera.position.set(c.x+r*1.12,c.y+r*.72,c.z+r*1.25);S.camera.lookAt(c);S.controls.update()}
function updateTimeUI(){const t=S.times[S.ti]||'';if($('timeValue'))$('timeValue').textContent=t?new Date(t).toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'}):'Ocean time';if($('timeRaw'))$('timeRaw').textContent=t||'—';if($('timeSlider')){$('timeSlider').max=Math.max(0,S.times.length-1);$('timeSlider').value=S.ti}if($('timeCount'))$('timeCount').textContent=`${S.ti+1}/${Math.max(1,S.times.length)}`}
function animate(ms=0){requestAnimationFrame(animate);if(S.playing&&S.times.length>1&&ms-S.lastPlay>900){S.lastPlay=ms;S.ti=(S.ti+1)%S.times.length;updateTimeUI()}S.controls?.update();S.renderer?.render(S.scene,S.camera)}

async function init(){
  S.geometry=await getJSON('/geometry.json');
  const catalog=await getJSON(`${API}/ocean/catalog`).catch(()=>[]);
  S.catalog=Array.isArray(catalog)?catalog:(catalog.variables||[]);
  const timeData=await getJSON(`${API}/ocean/time`).catch(()=>[]);
  S.times=Array.isArray(timeData)?timeData:(timeData.times||[]);
  S.scene=new THREE.Scene();S.scene.background=new THREE.Color(0xb9dfe9);S.scene.fog=new THREE.Fog(0xb9dfe9,1200,5200);
  S.camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.1,100000);
  S.renderer=new THREE.WebGLRenderer({canvas:$('renderCanvas'),antialias:true,powerPreference:'high-performance'});S.renderer.setPixelRatio(Math.min(devicePixelRatio,2));S.renderer.setSize(innerWidth,innerHeight);S.renderer.outputColorSpace=THREE.SRGBColorSpace;
  S.scene.add(new THREE.HemisphereLight(0xffffff,0x49636b,2));const sun=new THREE.DirectionalLight(0xffffff,2.4);sun.position.set(400,700,800);S.scene.add(sun);
  S.root=new THREE.Group();S.scene.add(S.root);
  drawSeabed();drawLand();drawCoast();buildWater();drawSurface();
  // Controls must exist before fitCamera/setupViews. This fixes the null target crash.
  S.controls=new OrbitControls(S.camera,S.renderer.domElement);S.controls.enableDamping=true;S.controls.dampingFactor=.055;S.controls.screenSpacePanning=true;S.controls.minDistance=100;S.controls.maxDistance=6000;S.controls.target.set(0,0,0);
  renderVariables();setupViews();setupUI();updateTimeUI();if($('depthMax'))$('depthMax').textContent=`${Number(S.geometry.terrain.maxDepthKm||0).toFixed(1)} km`;if($('depthValue'))$('depthValue').textContent='Volume';$('loading')?.classList.add('hidden');setStatus('3D ocean chunk ready');fitCamera();animate()
}
addEventListener('resize',()=>{if(!S.camera||!S.renderer)return;S.camera.aspect=innerWidth/innerHeight;S.camera.updateProjectionMatrix();S.renderer.setSize(innerWidth,innerHeight)});
init().catch(fail);
