(() => {
'use strict';
const $=id=>document.getElementById(id), finite=v=>typeof v==='number'&&Number.isFinite(v);
let data=null,depthEx=10,engine,scene,camera,seabed=null,waterSurface=null,layerMeshes=[],waterWallMeshes=[],landMeshes=[],waterBump=null,currentView='3d';
const SURFACE_Y=0,LAND_TOP_Y=3,LAND_BOTTOM_Y=-3,WATER_LAYER_COUNT=50,WATER_MAX_POINTS=24000,WATER_BUMP_URL='https://www.babylonjs-playground.com/textures/waterbump.png';
function status(text,type='ok'){$('status').textContent=text;$('statusDot').className=`statusdot ${type==='error'?'error':type==='busy'?'busy':''}`}
function fail(e){console.error(e);status(`3D viewer failed: ${e?.message||e}`,'error');$('loading')?.classList.add('hide');$('fatalText').textContent=e?.message||String(e);$('fatal').style.display='block'}
function geo(){const x=data.terrain.x,z=data.terrain.y,minX=Math.min(...x),maxX=Math.max(...x),minZ=Math.min(...z),maxZ=Math.max(...z);return{minX,maxX,minZ,maxZ,width:maxX-minX,height:maxZ-minZ,cx:(minX+maxX)/2,cz:(minZ+maxZ)/2,size:Math.max(maxX-minX,maxZ-minZ)}}
function makeMesh(name,pos,ind,mat){const m=new BABYLON.Mesh(name,scene),v=new BABYLON.VertexData();v.positions=pos;v.indices=ind;v.applyToMesh(m,true);m.material=mat;m.metadata={solvx:true};return m}
function landMaterial(){const m=new BABYLON.StandardMaterial('dark forest cover',scene);m.diffuseColor=new BABYLON.Color3(.045,.22,.055);m.emissiveColor=new BABYLON.Color3(.004,.018,.005);m.specularColor=BABYLON.Color3.Black();m.backFaceCulling=false;return m}
function seabedMaterial(){const m=new BABYLON.StandardMaterial('real soil seabed',scene);m.diffuseColor=new BABYLON.Color3(.30,.17,.075);m.emissiveColor=new BABYLON.Color3(.018,.008,.003);m.specularColor=new BABYLON.Color3(.025,.018,.01);m.backFaceCulling=false;return m}
function waterMaterial(){const m=new BABYLON.StandardMaterial('opaque dark blue sea surface',scene);m.diffuseColor=new BABYLON.Color3(.004,.075,.30);m.emissiveColor=new BABYLON.Color3(.001,.006,.025);m.specularColor=new BABYLON.Color3(.25,.42,.70);m.specularPower=80;m.alpha=1;m.backFaceCulling=false;waterBump=new BABYLON.Texture(WATER_BUMP_URL,scene);waterBump.uScale=8;waterBump.vScale=8;waterBump.level=.18;m.bumpTexture=waterBump;return m}
function makeSeabed(){const t=data.terrain,x=t.x,z=t.y,r=t.rawDepthKm,nx=x.length,nz=z.length,p=new Float32Array(nx*nz*3),ind=[];let k=0;for(let j=0;j<nz;j++)for(let i=0;i<nx;i++,k++){const d=r[j]?.[i];p[k*3]=x[i];p[k*3+1]=finite(d)?-d*depthEx*8:LAND_BOTTOM_Y;p[k*3+2]=z[j]}for(let j=0;j<nz-1;j++)for(let i=0;i<nx-1;i++){const q=[r[j]?.[i],r[j]?.[i+1],r[j+1]?.[i],r[j+1]?.[i+1]];if(!q.every(finite))continue;const a=j*nx+i,b=a+1,c=a+nx,d=c+1;ind.push(a,c,b,b,c,d)}const m=makeMesh('GEBCO SOIL SEABED',Array.from(p),ind,seabedMaterial());m.renderingGroupId=0;return m}
function makeLand(){const mat=landMaterial();let count=0;for(const ps of [data.land||[],data.islands||[]])for(const poly of ps){if(!poly?.vertices?.length||!poly?.triangles?.length)continue;const n=poly.vertices.length,p=[];for(const q of poly.vertices)p.push(+q[0],LAND_TOP_Y,+q[1]);for(const q of poly.vertices)p.push(+q[0],LAND_BOTTOM_Y,+q[1]);const ind=[];for(const t of poly.triangles){if(t?.length<3)continue;const a=+t[0],b=+t[1],c=+t[2];ind.push(a,c,b,a+n,b+n,c+n)}const ring=poly.top||[];for(let i=0;i<ring.length-1;i++){let ia=-1,ib=-1,da=Infinity,db=Infinity;for(let v=0;v<poly.vertices.length;v++){const vx=+poly.vertices[v][0],vz=+poly.vertices[v][1],aa=Math.hypot(vx-ring[i][0],vz-ring[i][1]),bb=Math.hypot(vx-ring[i+1][0],vz-ring[i+1][1]);if(aa<da){da=aa;ia=v}if(bb<db){db=bb;ib=v}}if(ia>=0&&ib>=0)ind.push(ia,ib,ia+n,ib,ib+n,ia+n)}if(!ind.length)continue;const m=makeMesh(`FOREST LAND ${count++}`,p,ind,mat);m.renderingGroupId=3;landMeshes.push(m)}return count}
function addLines(name,parts,y,color){for(let n=0;n<(parts||[]).length;n++){const a=parts[n];if(!a||a.length<2)continue;const line=BABYLON.MeshBuilder.CreateLines(`${name}-${n}`,{points:a.map(q=>new BABYLON.Vector3(+q[0],y,+q[1]))},scene);line.color=color;line.renderingGroupId=5;line.metadata={solvx:true}}}
function depthLevels(){const s=Array.isArray(data.temperatureDepthsM)?data.temperatureDepthsM.filter(finite):[];if(!s.length){const max=Math.max(1000,(data.terrain.maxDepthKm||5)*1000);return Array.from({length:WATER_LAYER_COUNT},(_,i)=>max*i/(WATER_LAYER_COUNT-1))}const lo=s[0]||0,hi=s.at(-1)||lo+1;return Array.from({length:WATER_LAYER_COUNT},(_,i)=>lo+(hi-lo)*i/(WATER_LAYER_COUNT-1))}
function depthY(m){return-(m/1000)*depthEx*8}
function waterGrid(){const t=data.terrain,x=t.x,z=t.y,r=t.rawDepthKm,nx=x.length,nz=z.length,step=Math.max(1,Math.ceil(Math.sqrt(nx*nz/24000))),ii=[],jj=[];for(let i=0;i<nx;i+=step)ii.push(i);if(ii.at(-1)!==nx-1)ii.push(nx-1);for(let j=0;j<nz;j+=step)jj.push(j);if(jj.at(-1)!==nz-1)jj.push(nz-1);return{t,x,z,r,nx,nz,ii,jj}}
function waterMat(i,total){const t=i/(total-1),c=new BABYLON.Color3(.004-.002*t,.095-.040*t,.34-.15*t),m=new BABYLON.StandardMaterial(`opaque water stratum ${i+1}`,scene);m.diffuseColor=c;m.emissiveColor=new BABYLON.Color3(c.r*.035,c.g*.035,c.b*.045);m.specularColor=new BABYLON.Color3(.10,.20,.38);m.specularPower=70;m.alpha=1;m.backFaceCulling=false;return m}
function bathyLayer(grid,fraction,name,mat){const{x,z,r,ii,jj}=grid,pos=[],map=new Map();for(let j=0;j<jj.length;j++)for(let i=0;i<ii.length;i++){const oi=ii[i],oj=jj[j],d=r[oj]?.[oi];if(!finite(d))continue;const id=pos.length/3;map.set(`${oj}:${oi}`,id);pos.push(x[oi],-d*depthEx*8*fraction,z[oj])}const ind=[];for(let j=0;j<jj.length-1;j++)for(let i=0;i<ii.length-1;i++){const a=map.get(`${jj[j]}:${ii[i]}`),b=map.get(`${jj[j]}:${ii[i+1]}`),c=map.get(`${jj[j+1]}:${ii[i]}`),d=map.get(`${jj[j+1]}:${ii[i+1]}`);if([a,b,c,d].every(v=>v!==undefined))ind.push(a,c,b,b,c,d)}return ind.length?makeMesh(name,pos,ind,mat):null}
function nearestDepth(grid,x,z){const ix=Math.max(0,Math.min(grid.nx-1,Math.round((x-grid.x[0])/(grid.x[grid.nx-1]-grid.x[0])*(grid.nx-1))));const iz=Math.max(0,Math.min(grid.nz-1,Math.round((z-grid.z[0])/(grid.z[grid.nz-1]-grid.z[0])*(grid.nz-1))));const d=grid.r[iz]?.[ix];return finite(d)?d:0}
function waterWallMaterial(){const m=new BABYLON.StandardMaterial('opaque dark blue ocean walls',scene);m.diffuseColor=new BABYLON.Color3(.003,.055,.22);m.emissiveColor=new BABYLON.Color3(.001,.004,.018);m.specularColor=new BABYLON.Color3(.08,.16,.32);m.alpha=1;m.backFaceCulling=false;return m}
function makeWaterWalls(){waterWallMeshes.forEach(m=>m.dispose(false,true));waterWallMeshes=[];const grid=waterGrid(),mat=waterWallMaterial();for(let p=0;p<(data.ocean||[]).length;p++){const ring=data.ocean[p]?.top||[];if(ring.length<2)continue;const pos=[],ind=[],n=ring.length;for(const q of ring)pos.push(+q[0],SURFACE_Y,+q[1]);for(const q of ring){const d=nearestDepth(grid,+q[0],+q[1]);pos.push(+q[0],-d*depthEx*8,+q[1])}for(let i=0;i<n-1;i++)ind.push(i,i+1,i+n,i+1,i+n+1,i+n);if(ind.length){const m=makeMesh(`OPAQUE OCEAN WALL ${p}`,pos,ind,mat);m.renderingGroupId=1;m.metadata={solvx:true,waterWall:true};waterWallMeshes.push(m)}}return waterWallMeshes.length}
function makeWaterLayers(){layerMeshes.forEach(m=>m.dispose(false,true));layerMeshes=[];const grid=waterGrid(),levels=depthLevels();for(let i=0;i<WATER_LAYER_COUNT;i++){const m=bathyLayer(grid,i/(WATER_LAYER_COUNT-1),`BATHYMETRY WATER LAYER ${i+1}`,waterMat(i,WATER_LAYER_COUNT));if(m){m.renderingGroupId=1;m.metadata={solvx:true,waterLayer:true,depth:levels[i],fraction:i/(WATER_LAYER_COUNT-1)};layerMeshes.push(m)}}return layerMeshes.length}
function makeWaterSurface(){if(waterSurface)waterSurface.dispose(false,true);const grid=waterGrid();waterSurface=bathyLayer(grid,0,'SEA LEVEL WATER SURFACE',waterMaterial());waterSurface.renderingGroupId=2}
function setViewVisibility(mode){const top=mode==='top';if(waterSurface)waterSurface.setEnabled(top);layerMeshes.forEach(m=>m.setEnabled(!top));waterWallMeshes.forEach(m=>m.setEnabled(!top));if(seabed)seabed.setEnabled(true);landMeshes.forEach(m=>m.setEnabled(true))}
function fit(mode='3d'){currentView=mode;const g=geo(),max=Math.abs(depthY(depthLevels().at(-1)||1000)),d=Math.max(650,g.size*1.30);if(mode==='top'){camera.target.set(g.cx,0,g.cz);camera.alpha=-Math.PI/2;camera.beta=.08;camera.radius=d*.92}else if(mode==='profile'){camera.target.set(g.cx,-max*.48,g.cz);camera.alpha=0;camera.beta=1.25;camera.radius=d*1.02}else if(mode==='under'){camera.target.set(g.cx,-max*.45,g.cz);camera.alpha=.55;camera.beta=2.10;camera.radius=d*.90}else{camera.target.set(g.cx,-max*.08,g.cz);camera.alpha=-.78;camera.beta=.88;camera.radius=d*1.05}setViewVisibility(mode)}
function build(){scene.meshes.slice().forEach(m=>{if(m.metadata?.solvx)m.dispose(false,true)});landMeshes=[];waterWallMeshes=[];seabed=makeSeabed();const landCount=makeLand();addLines('COASTLINE',data.coast,LAND_TOP_Y+.35,new BABYLON.Color3(.01,.045,.01));addLines('EEZ',data.eez,LAND_TOP_Y+.20,new BABYLON.Color3(.95,.55,.04));const count=makeWaterLayers();makeWaterWalls();makeWaterSurface();fit(currentView);const src=data.temperatureDepthsM?.length?`${data.temperatureDepthsM.length} source levels`:'bathymetry fallback';status(`Ocean ready · ${landCount} forest land chunks · coastline · ${count} opaque dark-blue water layers (${src})`);$('loading').classList.add('hide')}
async function init(){try{if(!window.BABYLON)throw new Error('Babylon.js CDN did not load');const canvas=$('renderCanvas');engine=new BABYLON.Engine(canvas,true,{stencil:true,preserveDrawingBuffer:false},true);scene=new BABYLON.Scene(engine);scene.clearColor=new BABYLON.Color4(.86,.91,.95,1);const hemi=new BABYLON.HemisphericLight('hemi',new BABYLON.Vector3(0,1,0),scene);hemi.intensity=1.25;const sun=new BABYLON.DirectionalLight('sun',new BABYLON.Vector3(-.5,-1,-.4),scene);sun.intensity=1.6;camera=new BABYLON.ArcRotateCamera('camera',-.78,.88,1500,BABYLON.Vector3.Zero(),scene);camera.attachControl(canvas,true);camera.lowerRadiusLimit=30;camera.upperRadiusLimit=12000;camera.wheelPrecision=2;camera.panningSensibility=90;status('Loading geometry.json…','busy');const response=await fetch(`geometry.json?${Date.now()}`,{cache:'no-store'});if(!response.ok)throw new Error(`${response.status} ${response.statusText}`);data=await response.json();if(!data.terrain?.x?.length||!data.terrain?.y?.length)throw new Error('Invalid terrain grid');build();engine.runRenderLoop(()=>{if(waterBump){waterBump.uOffset+=.00035;waterBump.vOffset+=.00014}scene.render()});addEventListener('resize',()=>engine.resize())}catch(error){fail(error)}}
$('exaggeration').value=10;$('exagValue').textContent='10×';$('exaggeration').addEventListener('input',e=>{depthEx=+(e.target.value||10);$('exagValue').textContent=`${depthEx}×`;build()});$('reset').onclick=()=>fit('3d');$('fullscreen').onclick=()=>document.documentElement.requestFullscreen?.();document.querySelectorAll('[data-view]').forEach(button=>{button.onclick=()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));button.classList.add('active');fit(button.dataset.view)}});init();
})();
