(() => {
  'use strict';
  const $=id=>document.getElementById(id), finite=v=>typeof v==='number'&&Number.isFinite(v);
  let data=null,depthEx=55,engine,scene,camera,terrain=null,water=null;
  function status(t,type='ok'){const e=$('status'),d=$('statusDot');if(e)e.textContent=t;if(d)d.className=`statusdot ${type==='error'?'error':type==='busy'?'busy':''}`}
  function fail(e){console.error('SolvX Babylon initialization failed:',e);status(`3D viewer failed: ${e?.message||e}`,'error');$('loading')?.classList.add('hide');$('fatalText').textContent=e?.message||String(e);$('fatal').style.display='block'}
  function makeTerrain(){const t=data.terrain,xs=t.x,ys=t.y,raw=t.rawDepthKm,nx=xs.length,ny=ys.length;if(nx<2||ny<2)throw Error('GEBCO grid is too small');const p=new Float32Array(nx*ny*3),ind=[];let k=0;for(let j=0;j<ny;j++){for(let i=0;i<nx;i++,k++){const d=raw[j]?.[i];p[k*3]=xs[i];p[k*3+1]=ys[j];p[k*3+2]=finite(d)?-d*depthEx:-2}}for(let j=0;j<ny-1;j++)for(let i=0;i<nx-1;i++){const q=[raw[j]?.[i],raw[j]?.[i+1],raw[j+1]?.[i],raw[j+1]?.[i+1]];if(q.every(finite)){const a=j*nx+i,b=a+1,c=a+nx,d=c+1;ind.push(a,c,b,b,c,d)}}const m=new BABYLON.Mesh('GEBCO seabed',scene),vd=new BABYLON.VertexData();vd.positions=p;vd.indices=ind;vd.applyToMesh(m,true);const mat=new BABYLON.StandardMaterial('seabed material',scene);mat.diffuseColor=new BABYLON.Color3(.42,.30,.21);mat.specularColor=BABYLON.Color3.Black();m.material=mat;return m}
  function addLand(){const positions=[],indices=[];let offset=0,count=0;for(const polygons of [data.land||[],data.islands||[]])for(const p of polygons){if(!Array.isArray(p.vertices)||!Array.isArray(p.triangles)||p.vertices.length<3||!p.triangles.length)continue;for(const q of p.vertices)if(Array.isArray(q)&&finite(+q[0])&&finite(+q[1]))positions.push(+q[0],+q[1],12);for(const tri of p.triangles){if(!Array.isArray(tri)||tri.length<3)continue;const a=+tri[0],b=+tri[1],c=+tri[2];if([a,b,c].every(Number.isInteger)&&a>=0&&b>=0&&c>=0&&a<p.vertices.length&&b<p.vertices.length&&c<p.vertices.length)indices.push(offset+a,offset+b,offset+c)}offset+=p.vertices.length;count++}if(!positions.length||!indices.length)return 0;const m=new BABYLON.Mesh('Natural Earth land',scene),vd=new BABYLON.VertexData();vd.positions=positions;vd.indices=indices;vd.applyToMesh(m,true);const mat=new BABYLON.StandardMaterial('land material',scene);mat.diffuseColor=new BABYLON.Color3(.25,.60,.33);mat.specularColor=BABYLON.Color3.Black();m.material=mat;m.renderingGroupId=2;return count}
  function addLines(name,parts,z,color){let n=0;for(const part of parts||[]){if(!Array.isArray(part)||part.length<2)continue;const pts=part.map(p=>new BABYLON.Vector3(+p[0],+p[1],z)),m=BABYLON.MeshBuilder.CreateLines(`${name}-${n++}`,{points:pts},scene);m.color=color;m.renderingGroupId=3}}
  function bounds(){const xs=data.terrain.x,ys=data.terrain.y;let minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity;for(const x of xs){minX=Math.min(minX,x);maxX=Math.max(maxX,x)}for(const y of ys){minY=Math.min(minY,y);maxY=Math.max(maxY,y)}return{minX,maxX,minY,maxY,cx:(minX+maxX)/2,cy:(minY+maxY)/2,size:Math.max(maxX-minX,maxY-minY)}}
  function fitCamera(mode='3d'){const b=bounds(),d=Math.max(650,b.size*1.5),target=new BABYLON.Vector3(b.cx,b.cy,mode==='under'||mode==='profile'?-120:0);if(mode==='top')camera.position.set(b.cx,b.cy,d*.95);else if(mode==='under')camera.position.set(b.cx+d*.45,b.cy-d*.45,-d*.25);else if(mode==='profile')camera.position.set(b.cx+d*.8,b.cy,d*.18);else{camera.position.set(b.cx+d*.72,b.cy-d*.82,d*.62);target.z=-Math.min(100,b.size*.05)}camera.setTarget(target)}
  function build(){terrain?.dispose(false,true);water?.dispose(false,true);terrain=makeTerrain();const b=bounds();water=BABYLON.MeshBuilder.CreatePlane('ocean surface',{width:b.maxX-b.minX,height:b.maxY-b.minY},scene);/* Babylon Plane is already in XY, matching our x/y geographic coordinates. */water.position.set(b.cx,b.cy,3);const wm=new BABYLON.StandardMaterial('water material',scene);wm.diffuseColor=new BABYLON.Color3(.05,.45,.68);wm.alpha=.22;wm.specularColor=new BABYLON.Color3(.4,.7,.85);wm.backFaceCulling=false;water.material=wm;water.renderingGroupId=1;const n=addLand();addLines('coast',data.coast,15,new BABYLON.Color3(.06,.25,.30));addLines('eez',data.eez,14.5,new BABYLON.Color3(.72,.50,.08));fitCamera();status(`3D ocean ready · ${n} land polygons`);$('loading')?.classList.add('hide')}
  function initBabylon(){const canvas=$('renderCanvas');if(!canvas)throw Error('renderCanvas missing');if(!window.BABYLON)throw Error('Babylon.js CDN did not load');engine=new BABYLON.Engine(canvas,true,{preserveDrawingBuffer:false,stencil:true},true);scene=new BABYLON.Scene(engine);scene.clearColor=new BABYLON.Color4(.875,.918,.945,1);camera=new BABYLON.ArcRotateCamera('camera',-.85,1,2500,BABYLON.Vector3.Zero(),scene);camera.attachControl(canvas,true);camera.lowerRadiusLimit=30;camera.upperRadiusLimit=14000;camera.wheelPrecision=2;camera.panningSensibility=80;scene.activeCamera=camera;const hemi=new BABYLON.HemisphericLight('hemi',new BABYLON.Vector3(0,0,1),scene);hemi.intensity=1.6;const sun=new BABYLON.DirectionalLight('sun',new BABYLON.Vector3(-.4,-.5,-1),scene);sun.intensity=1.8}
  async function init(){try{status('Starting Babylon.js renderer…','busy');initBabylon();status('Loading geometry.json…','busy');const r=await fetch(`geometry.json?${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(`${r.status} ${r.statusText}`);data=await r.json();if(!data.terrain||!Array.isArray(data.terrain.x)||!Array.isArray(data.terrain.y))throw Error('Invalid geometry.json terrain');build();engine.runRenderLoop(()=>scene.render());addEventListener('resize',()=>engine.resize())}catch(e){fail(e)}}
  $('exaggeration')?.addEventListener('input',e=>{depthEx=+e.target.value||55;$('exagValue').textContent=`${depthEx}×`;if(!terrain)return;const vd=terrain.getVerticesData(BABYLON.VertexBuffer.PositionKind);const raw=data.terrain.rawDepthKm,nx=data.terrain.x.length,ny=data.terrain.y.length;for(let j=0;j<ny;j++)for(let i=0;i<nx;i++){const k=j*nx+i,d=raw[j]?.[i];vd[k*3+2]=finite(d)?-d*depthEx:-2}terrain.updateVerticesData(BABYLON.VertexBuffer.PositionKind,vd,false,false)});
  $('reset')?.addEventListener('click',()=>fitCamera('3d'));$('fullscreen')?.addEventListener('click',()=>document.documentElement.requestFullscreen?.());$('closeReadout')?.addEventListener('click',()=>$('readout')?.classList.remove('show'));document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');fitCamera(b.dataset.view||'3d')}));init();
})();
