(() => {
'use strict';
const $=id=>document.getElementById(id), finite=v=>typeof v==='number'&&Number.isFinite(v);
let data=null,depthEx=10,engine,scene,camera,seabed=null,water=null,waterLayers=[];
const WATER_BUMP='https://www.babylonjs-playground.com/textures/waterbump.png';
function status(t,type='ok'){ $('status').textContent=t; $('statusDot').className=`statusdot ${type==='error'?'error':type==='busy'?'busy':''}` }
function fail(e){console.error(e);status(`3D viewer failed: ${e?.message||e}`,'error');$('loading')?.classList.add('hide');$('fatalText').textContent=e?.message||String(e);$('fatal').style.display='block'}
function bounds(){const xs=data.terrain.x,ys=data.terrain.y;let minX=Infinity,maxX=-Infinity,minZ=Infinity,maxZ=-Infinity;for(const x of xs){if(x<minX)minX=x;if(x>maxX)maxX=x}for(const y of ys){if(y<minZ)minZ=y;if(y>maxZ)maxZ=y}return{minX,maxX,minZ,maxZ,cx:(minX+maxX)/2,cz:(minZ+maxZ)/2,size:Math.max(maxX-minX,maxZ-minZ)}}
function mesh(name,pos,idx,mat){const m=new BABYLON.Mesh(name,scene),v=new BABYLON.VertexData();v.positions=pos;v.indices=idx;v.applyToMesh(m,true);m.material=mat;return m}
function landMat(){const m=new BABYLON.StandardMaterial('solid green land',scene);m.diffuseColor=new BABYLON.Color3(.12,.48,.16);m.emissiveColor=new BABYLON.Color3(.015,.055,.02);m.specularColor=BABYLON.Color3.Black();m.backFaceCulling=false;return m}
function seabedMat(){const m=new BABYLON.StandardMaterial('GEBCO seabed',scene);m.diffuseColor=new BABYLON.Color3(.31,.24,.18);m.specularColor=BABYLON.Color3.Black();return m}
function makeSeabed(){const t=data.terrain,xs=t.x,ys=t.y,raw=t.rawDepthKm,nx=xs.length,ny=ys.length,p=new Float32Array(nx*ny*3),idx=[];let k=0;for(let j=0;j<ny;j++)for(let i=0;i<nx;i++,k++){const d=raw[j]?.[i];p[k*3]=xs[i];p[k*3+1]=finite(d)?-d*depthEx:-3;p[k*3+2]=ys[j]}for(let j=0;j<ny-1;j++)for(let i=0;i<nx-1;i++){const q=[raw[j]?.[i],raw[j]?.[i+1],raw[j+1]?.[i],raw[j+1]?.[i+1]];if(q.every(finite)){const a=j*nx+i,b=a+1,c=a+nx,d=c+1;idx.push(a,c,b,b,c,d)}}return mesh('GEBCO seabed',Array.from(p),idx,seabedMat())}
function addLand(){const mat=landMat();const bottom=-Math.max(55,Math.min(160,(data.terrain.maxDepthKm||5)*depthEx*.12));let count=0;for(const polys of [data.land||[],data.islands||[]])for(const poly of polys){if(!poly?.vertices?.length||!poly?.triangles?.length)continue;const n=poly.vertices.length,top=poly.vertices.map(q=>[+q[0],8,+q[1]]),bot=poly.vertices.map(q=>[+q[0],bottom,+q[1]]),pos=top.concat(bot).flat(),idx=[];for(const t of poly.triangles){if(Array.isArray(t)&&t.length>=3){const a=+t[0],b=+t[1],c=+t[2];idx.push(a,c,b);idx.push(a+n,b+n,c+n)}}const ring=poly.top||[];for(let i=0;i<ring.length-1;i++){const va=poly.vertices.findIndex(q=>Math.hypot(q[0]-ring[i][0],q[1]-ring[i][1])<.0001),vb=poly.vertices.findIndex(q=>Math.hypot(q[0]-ring[i+1][0],q[1]-ring[i+1][1])<.0001);if(va>=0&&vb>=0)idx.push(va,vb,va+n,vb,vb+n,va+n)}if(idx.length){const m=mesh(`land-chunk-${count}`,pos,idx,mat);m.renderingGroupId=3;m.metadata={solvx:true};count++}}return count}
function addLines(name,parts,y,color){for(let n=0;n<(parts||[]).length;n++){const a=parts[n];if(a.length<2)continue;const pts=a.map(q=>new BABYLON.Vector3(+q[0],y,+q[1]));const l=BABYLON.MeshBuilder.CreateLines(`${name}-${n}`,{points:pts},scene);l.color=color;l.renderingGroupId=4;l.metadata={solvx:true}}}
function makeWater(){const b=bounds();if(water)water.dispose(false,true);const w=BABYLON.MeshBuilder.CreateGround('ocean water surface',{width:b.maxX-b.minX,height:b.maxZ-b.minZ,subdivisions:160},scene);w.position.set(b.cx,4,b.cz);let m;if(BABYLON.WaterMaterial){m=new BABYLON.WaterMaterial('realistic ocean water',scene);m.bumpTexture=new BABYLON.Texture(WATER_BUMP,scene);m.windForce=3;m.waveHeight=.55;m.bumpHeight=.22;m.windDirection=new BABYLON.Vector2(.8,.35);m.waveLength=.55;m.waterColor=new BABYLON.Color3(.01,.28,.62);m.waterColor2=new BABYLON.Color3(.02,.55,.78);m.colorBlendFactor=.32;m.alpha=1;m.addToRenderList(seabed);scene.meshes.filter(x=>x.metadata?.solvx).forEach(x=>m.addToRenderList(x));}else{m=new BABYLON.StandardMaterial('opaque ocean',scene);m.diffuseColor=new BABYLON.Color3(.015,.36,.72);m.specularColor=new BABYLON.Color3(.35,.55,.8)}w.material=m;w.renderingGroupId=2;w.metadata={solvx:true};water=w}
function makeLayers(){waterLayers.forEach(x=>x.dispose(false,true));waterLayers=[];const b=bounds(),levels=[{y:2.5,c:new BABYLON.Color3(.02,.62,.82)},{y:-8,c:new BABYLON.Color3(.015,.50,.78)},{y:-22,c:new BABYLON.Color3(.01,.40,.70)},{y:-40,c:new BABYLON.Color3(.008,.31,.60)},{y:-65,c:new BABYLON.Color3(.006,.23,.50)}];for(let i=0;i<levels.length;i++){const q=levels[i],m=BABYLON.MeshBuilder.CreateGround(`ocean-layer-${i}`,{width:b.maxX-b.minX,height:b.maxZ-b.minZ,subdivisions:1},scene);m.position.set(b.cx,q.y,b.cz);const mat=new BABYLON.StandardMaterial(`ocean-stratum-${i}`,scene);mat.diffuseColor=q.c;mat.emissiveColor=new BABYLON.Color3(q.c.r*.08,q.c.g*.08,q.c.b*.08);mat.specularColor=BABYLON.Color3.Black();mat.alpha=.16;mat.backFaceCulling=false;m.material=mat;m.renderingGroupId=1;m.metadata={solvx:true};waterLayers.push(m)}}
function fit(mode='3d'){const b=bounds(),d=Math.max(650,b.size*1.35);camera.target.set(b.cx,0,b.cz);if(mode==='top'){camera.alpha=-Math.PI/2;camera.beta=.12;camera.radius=d*1.03}else if(mode==='profile'){camera.alpha=0;camera.beta=1.1;camera.radius=d}else if(mode==='under'){camera.alpha=.7;camera.beta=2.25;camera.radius=d*.9}else{camera.alpha=-.85;camera.beta=1.0;camera.radius=d}}
function build(){scene.meshes.slice().forEach(m=>{if(m.metadata?.solvx)m.dispose(false,true)});seabed=makeSeabed();seabed.metadata={solvx:true};const landCount=addLand();addLines('coast',data.coast,9.3,new BABYLON.Color3(.02,.20,.22));addLines('eez',data.eez,9.1,new BABYLON.Color3(.95,.55,.04));makeLayers();makeWater();fit('3d');status(`3D ocean ready · ${landCount} solid green land chunks`);$('loading').classList.add('hide')}
async function init(){try{if(!window.BABYLON)throw Error('Babylon.js CDN did not load');const c=$('renderCanvas');engine=new BABYLON.Engine(c,true,{stencil:true,preserveDrawingBuffer:false},true);scene=new BABYLON.Scene(engine);scene.clearColor=new BABYLON.Color4(.875,.918,.945,1);const hemi=new BABYLON.HemisphericLight('hemi',new BABYLON.Vector3(0,1,0),scene);hemi.intensity=1.35;const sun=new BABYLON.DirectionalLight('sun',new BABYLON.Vector3(-.5,-1,-.4),scene);sun.intensity=2;camera=new BABYLON.ArcRotateCamera('camera',-.85,1,2500,BABYLON.Vector3.Zero(),scene);camera.attachControl(c,true);camera.lowerRadiusLimit=30;camera.upperRadiusLimit=18000;camera.wheelPrecision=2;camera.panningSensibility=90;status('Loading geometry.json…','busy');const r=await fetch(`geometry.json?${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(`${r.status} ${r.statusText}`);data=await r.json();if(!data.terrain?.x?.length)throw Error('Invalid terrain grid');build();engine.runRenderLoop(()=>scene.render());addEventListener('resize',()=>engine.resize())}catch(e){fail(e)}}
$('exaggeration').value=10;$('exagValue').textContent='10×';$('exaggeration').addEventListener('input',e=>{depthEx=+e.target.value||10;if(seabed){const v=seabed.getVerticesData(BABYLON.VertexBuffer.PositionKind),raw=data.terrain.rawDepthKm,nx=data.terrain.x.length,ny=data.terrain.y.length;for(let j=0;j<ny;j++)for(let i=0;i<nx;i++){const k=j*nx+i,d=raw[j]?.[i];v[k*3+1]=finite(d)?-d*depthEx:-3}seabed.updateVerticesData(BABYLON.VertexBuffer.PositionKind,v,false,false);makeLayers();makeWater();fit('3d')}});
$('reset').onclick=()=>fit('3d');$('fullscreen').onclick=()=>document.documentElement.requestFullscreen?.();document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');fit(b.dataset.view)});init();
})();
