(()=>{
'use strict';
const API='http://127.0.0.1:8000',$=id=>document.getElementById(id);
const S={catalog:[],times:[],i:0,active:'temperature',playing:false,timer:null,field:null,geo:null,datasets:[],meta:{}};
const labels={temperature:'Temperature',temperature_anomaly:'Sea surface temperature anomaly',salinity:'Salinity',currents:'Currents',sea_level:'Sea level',chlorophyll:'Chlorophyll',abnormal:'Abnormal / disaster data'};
const order=['temperature','temperature_anomaly','salinity','currents','sea_level','abnormal','chlorophyll'];
const descriptions={temperature:'3D water temperature',temperature_anomaly:'SST anomaly',salinity:'Salinity / PSU',currents:'Direction and speed',sea_level:'Sea-surface height',chlorophyll:'Chlorophyll-a',abnormal:'Cyclone / warning information'};
async function get(path){const r=await fetch(API+path,{cache:'no-store'});if(!r.ok){let x='';try{x=await r.text()}catch{}throw Error(r.status+' '+x)}return r.json()}
function asDate(v){if(v==null)return null;if(typeof v==='number'||/^\d{16,}$/.test(String(v))){let n=Number(v);if(Math.abs(n)>1e17)n/=1e6;else if(Math.abs(n)>1e14)n/=1e3;const d=new Date(n);if(!isNaN(d))return d}const d=new Date(v);return isNaN(d)?null:d}
function apiTime(v){const d=asDate(v);return d?d.toISOString():String(v??'')}
function fmt(v){const d=asDate(v);return d?d.toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'}):String(v??'')}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function bounds(){return S.geo?.bounds||[84.104975983510294,92.99298840579259,16.070728135396756,23.524363913510872]}
function info(id){return S.catalog.find(x=>x.id===id)}
function abnormal(){for(const d of S.datasets||[])for(const v of d.variables||[]){if(/cyclone|storm|disaster|warning|alert|tropical/i.test(`${v.name} ${v.long_name||''} ${v.standard_name||''}`))return{...v,file:d.file}}return null}
function buildVars(){const a=abnormal(),box=$('vars');if(!box)return;const arr=order.map(id=>id==='abnormal'?{id,label:labels[id],available:!!a,file:a?.file,variable:a?.name,units:a?.units}:info(id)||{id,label:labels[id],available:false});box.innerHTML=arr.map((v,i)=>`<button class="var ${v.id===S.active?'active':''} ${v.available===false?'off':''}" data-var="${v.id}"><span class="ico">${i+1}</span><span><strong>${esc(v.label)}</strong><span>${esc(v.available===false?'No backend dataset detected':descriptions[v.id])}</span></span><i class="dot ${v.available===false?'off':''}"></i></button>`).join('');box.querySelectorAll('.var').forEach(b=>b.onclick=()=>selectVar(b.dataset.var));legend()}
function legend(){const v=info(S.active),l=$('legend'),t=$('legendTitle');if(!l)return;if(S.active==='currents'||S.active==='abnormal'){l.style.display='none';t.textContent=S.active==='currents'?'Currents: arrows show direction and speed':'Abnormal / disaster information';return}l.style.display='block';l.className='legend '+({temperature:'temp',temperature_anomaly:'anomaly',salinity:'sal',chlorophyll:'chl',sea_level:'neutral'}[S.active]||'neutral');t.textContent=(v?.label||labels[S.active])+' range';$('legendLo').textContent=S.field?.min!=null?Number(S.field.min).toFixed(2)+' '+(v?.units||''):'low';$('legendHi').textContent=S.field?.max!=null?Number(S.field.max).toFixed(2)+' '+(v?.units||''):'high'}
function timeline(){const x=$('timeSlider');if(!x)return;x.max=Math.max(0,S.times.length-1);x.value=S.i;$('timeCount').textContent=S.times.length+' time steps';ticks();renderTime();x.oninput=()=>{S.i=+x.value;renderTime();loadField()};$('play').onclick=play}
function ticks(){const e=$('timeScale');e.innerHTML='';const n=S.times.length;if(!n)return;for(let k=0;k<Math.min(9,n);k++){const i=Math.round(k*(n-1)/(Math.min(9,n)-1||1)),s=document.createElement('span');s.className='tick';s.style.left=(i/(n-1||1)*100)+'%';s.textContent=fmt(S.times[i]);e.appendChild(s)}}
function renderTime(){const v=S.times[S.i];$('timeValue').textContent=fmt(v);$('timeRaw').textContent=apiTime(v);$('timeSlider').value=S.i}
function play(){if(S.playing){clearInterval(S.timer);S.playing=false;$('play').textContent='PLAY';return}if(S.times.length<2)return;S.playing=true;$('play').textContent='PAUSE';S.timer=setInterval(()=>{S.i=(S.i+1)%S.times.length;renderTime();loadField()},1000)}
function flat(a){const o=[];(function w(x){if(Array.isArray(x))x.forEach(w);else if(typeof x==='number'&&isFinite(x))o.push(x)})(a);return o}
function nearest(a,x){let lo=0,hi=a.length-1;if(!a.length)return 0;const asc=a[0]<=a[hi];while(lo<hi){const m=(lo+hi)>>1;if(asc?a[m]<x:a[m]>x)lo=m+1;else hi=m}return lo&&lo<a.length&&Math.abs(a[lo]-x)>=Math.abs(a[lo-1]-x)?lo-1:lo}
function value(a,shape,ix){if(!shape.length)return typeof a==='number'?a:null;let q=0,str=1;for(let k=shape.length-1;k>=0;k--){q+=(ix[k]||0)*str;str*=shape[k]}const f=flat(a);return f[q]}
function colors(id,q){q=Math.max(0,Math.min(1,q));if(id==='temperature')return[.03+.9*q,.22+.5*q,.85-.78*q];if(id==='temperature_anomaly')return[.1+.82*q,.4+.3*(1-q),.8-.65*q];if(id==='salinity')return[.05+.3*q,.3+.6*q,.9-.5*q];if(id==='chlorophyll')return[.86-.82*q,.96-.2*q,.75-.55*q];return[.7-.45*q,.84-.35*q,.92-.35*q]}
function apply(field){S.field=field;const scene=BABYLON.Engine.LastCreatedEngine?.scenes?.[0];if(!scene)return;const b=bounds(),klat=111.32,klon=111.32*Math.cos((b[2]+b[3])/2*Math.PI/180),lon0=(b[0]+b[1])/2,lat0=(b[2]+b[3])/2,lat=field.coordinates?.latitude,lon=field.coordinates?.longitude,dep=field.coordinates?.depth,dims=field.dimensions||[],vals=field.data;if(!lat||!lon||vals==null)return;const nums=flat(vals);S.field.min=nums.length?Math.min(...nums):null;S.field.max=nums.length?Math.max(...nums):null;legend();scene.meshes.filter(m=>m.metadata?.waterLayer).forEach(m=>{const p=m.getVerticesData(BABYLON.VertexBuffer.PositionKind);if(!p)return;const out=[],di=dep&&m.metadata.depth!=null?nearest(dep,m.metadata.depth):0;for(let k=0;k<p.length;k+=3){const yi=nearest(lat,lat0+p[k+2]/klat),xi=nearest(lon,lon0+p[k]/klon),ix=dims.map(d=>d==='depth'?di:(d==='latitude'||d==='lat'?yi:(d==='longitude'||d==='lon'?xi:0))),z=value(vals,field.shape||[],ix),q=typeof z==='number'&&S.field.max!==S.field.min?(z-S.field.min)/(S.field.max-S.field.min):.45,c=colors(S.active,q);out.push(c[0],c[1],c[2],1)}m.material.useVertexColors=true;m.setVerticesData(BABYLON.VertexBuffer.ColorKind,out,true)})}
async function loadField(){let v=info(S.active);if(S.active==='abnormal'){const a=abnormal();if(!a)return;v=a}if(!v?.available||!v.file||!v.variable)return;if(S.active==='currents')return;try{const p=new URLSearchParams({file:v.file,variable:v.variable,lat_min:String(bounds()[2]),lat_max:String(bounds()[3]),lon_min:String(bounds()[0]),lon_max:String(bounds()[1]),time_start:apiTime(S.times[S.i]),time_end:apiTime(S.times[S.i]),stride:'4'});if(S.meta[v.file]?.depth){p.set('depth_min',S.meta[v.file].depth.min);p.set('depth_max',S.meta[v.file].depth.max)}apply(await get('/data/region/array?'+p))}catch(e){$('status').textContent=`${labels[S.active]} unavailable: ${e.message}`}}
async function selectVar(id){S.active=id;document.querySelectorAll('.var').forEach(b=>b.classList.toggle('active',b.dataset.var===id));legend();await loadField()}
async function init(){try{S.geo=await fetch('geometry.json?'+Date.now()).then(r=>r.json());const [c,t,d]=await Promise.all([get('/ocean/catalog'),get('/ocean/time'),get('/datasets')]);S.catalog=c.variables||[];S.times=t.values||[];S.datasets=d.datasets||[];for(const v of S.catalog.filter(x=>x.available)){try{const m=await get('/metadata/'+encodeURIComponent(v.file));S.meta[v.file]={depth:m.coordinates?.depth}}catch{}}buildVars();timeline();await loadField()}catch(e){console.error('Ocean data UI',e)}}
setTimeout(init,700);
})();
