(()=>{
'use strict';
const $=id=>document.getElementById(id);
const API=`${location.protocol==='file:'?'http:':location.protocol}//${location.hostname||'127.0.0.1'}:8000`;
let geo=null,scene=null,canvas=null,token=0;
const get=async path=>{const r=await fetch(API+path,{cache:'no-store'});if(!r.ok){let text='';try{text=await r.text()}catch{}throw new Error(`${r.status} ${text||r.statusText}`)}return r.json()};
const finite=v=>Number.isFinite(Number(v));
const bounds=()=>geo?.bounds||[84.104975983510294,92.99298840579259,16.070728135396756,23.524363913510872];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function toGeo(x,z){const b=bounds(),lat0=(b[2]+b[3])/2,lon0=(b[0]+b[1])/2;const klat=111.32,klon=111.32*Math.cos(lat0*Math.PI/180);return{longitude:clamp(lon0+x/klon,b[0],b[1]),latitude:clamp(lat0+z/klat,b[2],b[3])}}
function sceneFromBabylon(){const B=window.BABYLON;if(!B)return null;const engines=B.Engine?.Instances||B.EngineStore?.Instances||[];for(const e of engines){if(e?.scenes?.length)return e.scenes[0]}return null}
function setStatus(text,type='ok'){const e=$('status');if(e)e.textContent=text;const d=$('statusDot');if(d)d.className='statusdot '+(type==='error'?'error':type==='busy'?'busy':'')}
function num(v){return finite(v)?Number(v):null}
function fmt(v){const n=num(v);if(n==null)return'—';const a=Math.abs(n);return a>=100?n.toFixed(2):a>=10?n.toFixed(3):n.toFixed(4)}
function esc(s){return String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function renderValues(payload){const grid=$('readoutGrid');if(!grid)return;grid.innerHTML='';for(const item of payload?.values||[]){const card=document.createElement('div');card.className='rval';const label=esc(item.label||item.id),units=esc(item.units||'');let value='—';if(item.available!==false&&item.value!=null){if(item.id==='currents'&&item.value&&typeof item.value==='object'){value=Object.entries(item.value).map(([k,v])=>`${esc(k)}: ${fmt(v)}`).join('<br>')}else if(Array.isArray(item.value)){value=item.value.filter(v=>v!=null).map(fmt).join(', ')||'—'}else if(typeof item.value==='number'){value=fmt(item.value)}else if(typeof item.value==='string'){value=esc(item.value)}else if(typeof item.value==='object'){value=Object.entries(item.value).map(([k,v])=>`${esc(k)}: ${fmt(v)}`).join('<br>')||'—'}}card.innerHTML=`<b>${label}</b><span>${value}${units?` <small>${units}</small>`:''}</span>`;grid.appendChild(card)}}
async function inspect(latitude,longitude){const id=++token;setStatus('Reading all variables at selected point…','busy');const t=window.__SOLVX_TIME__?.();try{const q=new URLSearchParams({latitude:latitude.toFixed(6),longitude:longitude.toFixed(6)});if(t)q.set('time',t);const data=await get(`/ocean/point?${q}`);if(id!==token)return;const coords=$('coords');if(coords)coords.textContent=`${data.latitude.toFixed(4)}° N · ${data.longitude.toFixed(4)}° E`;if($('readoutTime'))$('readoutTime').textContent=data.time?`Dataset time: ${data.time}`:'Dataset time: surface/current selection';renderValues(data);if($('readout'))$('readout').style.display='block';setStatus('Point selected · all available variables loaded')}catch(e){if(id===token)setStatus(`Point data unavailable: ${e.message}`,'error')}}
function pickPredicate(m){if(!m||m.isDisposed?.())return false;const n=String(m.name||'');return !!m.metadata?.waterLayer||!!m.metadata?.waterWall||n==='SOLVX_REAL_OCEAN_FIELD'||n==='SOLVX_DIAGNOSTIC_COLOR_PREVIEW'}
function onPointer(){if(!scene||!canvas)return;const hit=scene.pick(scene.pointerX,scene.pointerY,pickPredicate);if(!hit?.hit||!hit.pickedPoint)return;const g=toGeo(hit.pickedPoint.x,hit.pickedPoint.z);inspect(g.latitude,g.longitude)}
async function boot(){try{canvas=$('renderCanvas');scene=sceneFromBabylon();let tries=0;while(!scene&&tries++<200){await new Promise(r=>setTimeout(r,50));scene=sceneFromBabylon()}if(!scene)throw new Error('Babylon scene not available');geo=await fetch(`geometry.json?${Date.now()}`,{cache:'no-store'}).then(r=>r.json());canvas.addEventListener('pointerdown',e=>{canvas.__sx=e.clientX;canvas.__sy=e.clientY});canvas.addEventListener('pointerup',e=>{if(e.button!==0)return;const moved=Math.hypot(e.clientX-canvas.__sx,e.clientY-canvas.__sy);if(moved<5)setTimeout(onPointer,0)});$('closeReadout')?.addEventListener('click',()=>{$('readout').style.display='none'});window.__SOLVX_POINT_INSPECT__=inspect;setStatus('Ocean point inspection ready · click any water location')}catch(e){console.error(e)}}
boot();
})();
