(()=>{"use strict";
const API="http://127.0.0.1:8000", $=id=>document.getElementById(id), finite=v=>typeof v==="number"&&Number.isFinite(v);
const S={catalog:[],times:[],i:0,active:"temperature",geo:null,meta:{},fields:[],currents:[],raf:0,token:0,playing:false};
const IDS=["temperature","temperature_anomaly","salinity","currents","sea_level","abnormal","chlorophyll"];
const LABEL={temperature:"Temperature",temperature_anomaly:"Sea surface temperature anomaly",salinity:"Salinity",currents:"Currents",sea_level:"Sea level",abnormal:"Abnormal / disaster data",chlorophyll:"Chlorophyll"};
const PAL={temperature:[[0,.01,.18],[0,.18,.95],[0,.85,1],[1,1,0],[1,.28,0],[.55,0,0]],temperature_anomaly:[[.02,.18,.65],[.15,.60,1],[1,1,1],[1,.55,.18],[.65,0,.02]],salinity:[[.02,.02,.45],[0,.35,1],[0,.95,.65],[.75,1,.08],[1,.55,0]],sea_level:[[.01,.05,.55],[0,.55,1],[.05,.95,1],[1,.85,.05],[.8,0,.02]],chlorophyll:[[.96,1,.92],[.65,.96,.25],[.08,.78,.18],[0,.35,.05],[0,.06,.015]],default:[[.02,.02,.2],[.2,.15,.8],[0,.8,.7],[.8,1,.1],[1,.2,.02]]};
const get=async p=>{const r=await fetch(API+p,{cache:"no-store"});if(!r.ok)throw Error(`${r.status} ${await r.text().catch(()=>"")}`);return r.json()};
function flatten(x,o=[]){if(Array.isArray(x)){for(const y of x)flatten(y,o)}else o.push(x);return o}
function quantile(a,p){if(!a.length)return 0;const x=(a.length-1)*p,i=Math.floor(x),j=Math.ceil(x);return a[i]+(a[j]-a[i])*(x-i)}
function robustStats(values){const a=values.filter(finite).sort((x,y)=>x-y);if(!a.length)return null;const p001=quantile(a,.001),p005=quantile(a,.005),p01=quantile(a,.01),p995=quantile(a,.995),p999=quantile(a,.999);return{a,min:a[0],max:a.at(-1),p001,p005,p01,p995,p999,p50:quantile(a,.5)}}
function iso(v){const d=new Date(v);return isNaN(d)?String(v??""):d.toISOString()}
function date(v){const d=new Date(v);return isNaN(d)?String(v??"—"):d.toLocaleDateString(undefined,{day:"2-digit",month:"short",year:"numeric"})}
function bounds(){return S.geo?.bounds||[84.104975983510294,92.99298840579259,16.070728135396756,23.524363913510872]}
function info(id){return S.catalog.find(v=>v.id===id)||null}
function palette(id){return PAL[id]||PAL.default}
function color(id,q){const p=palette(id);q=Math.max(0,Math.min(1,q));const x=q*(p.length-1),i=Math.min(p.length-2,Math.floor(x)),t=x-i,a=p[i],b=p[i+1];return[a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t,a[2]+(b[2]-a[2])*t]}
function scene(){return BABYLON.Engine.LastCreatedEngine?.scenes?.[0]}
function baseMeshes(){const sc=scene();return sc?sc.meshes.filter(m=>m.metadata?.waterLayer||m.metadata?.waterWall||m.metadata?.solvxWaterSurface):[]}
function hideBase(){baseMeshes().forEach(m=>m.setEnabled(false))} function showBase(){baseMeshes().forEach(m=>m.setEnabled(true)}
function clearFields(){S.fields.forEach(m=>m.dispose(false,true));S.fields=[]} function clearCurrents(){if(S.raf){cancelAnimationFrame(S.raf);S.raf=0}S.currents.forEach(a=>{a.line?.dispose(false,true);a.head?.dispose(false,true)});S.currents=[]}
function extract2D(f){const dims=f.dimensions||[],shape=f.shape||[],lat=f.coordinates?.latitude||f.coordinates?.lat||[],lon=f.coordinates?.longitude||f.coordinates?.lon||[],li=dims.includes("latitude")?dims.indexOf("latitude"):dims.indexOf("lat"),oi=dims.includes("longitude")?dims.indexOf("longitude"):dims.indexOf("lon");if(li<0||oi<0||!shape[li]||!shape[oi]||!lat.length||!lon.length)return null;const raw=flatten(f.data),nx=shape[oi],ny=shape[li],values=new Array(nx*ny);for(let y=0;y<ny;y++)for(let x=0;x<nx;x++){const ix=new Array(shape.length).fill(0);ix[li]=y;ix[oi]=x;let flat=0,mul=1;for(let k=shape.length-1;k>=0;k--){flat+=ix[k]*mul;mul*=shape[k]}values[y*nx+x]=Number(raw[flat])}return{lat,lon,nx,ny,values}}
function depthY(depth){const ex=+$('exaggeration')?.value||10;return 1-(Number(depth)||0)/1000*ex*8}
function equalizedQ(v,stats){if(!finite(v)||!stats)return .5;let q;if(stats.max===stats.min)return .5;if(v<=stats.p005)q=.02*(v-stats.min)/(stats.p005-stats.min||1);else if(v>=stats.p995)q=.98+.02*(v-stats.p995)/(stats.max-stats.p995||1);else q=.02+.96*(v-stats.p005)/(stats.p995-stats.p005||1);return Math.max(0,Math.min(1,q))}
function rangeFor(values,id){const s=robustStats(values);if(!s)return null;let lo=s.p005,hi=s.p995;if(id==='temperature_anomaly'){const m=Math.max(Math.abs(lo),Math.abs(hi),Math.abs(s.min),Math.abs(s.max));lo=-m;hi=m}if(!(hi>lo)){const pad=Math.max(Math.abs(lo)*.01,1e-6);lo-=pad;hi+=pad}return{...s,lo,hi}}
function makeField(f,depth,range,layer){const sc=scene(),d=extract2D(f);if(!sc||!d||!range)return null;const W=Math.min(1024,Math.max(512,2**Math.ceil(Math.log2(Math.max(d.nx,d.ny))))),H=W,canvas=document.createElement("canvas");canvas.width=W;canvas.height=H;const ctx=canvas.getContext("2d",{alpha:true});if(!ctx)return null;const img=ctx.createImageData(W,H),pix=img.data,inv=1/(range.hi-range.lo||1),gamma=.82;for(let py=0;py<H;py++){const gy=(py/(H-1))*(d.ny-1),y0=Math.floor(gy),y1=Math.min(d.ny-1,y0+1),ty=gy-y0;for(let px=0;px<W;px++){const gx=(px/(W-1))*(d.nx-1),x0=Math.floor(gx),x1=Math.min(d.nx-1,x0+1),tx=gx-x0,a=d.values[y0*d.nx+x0],b=d.values[y0*d.nx+x1],c=d.values[y1*d.nx+x0],e=d.values[y1*d.nx+x1],off=(py*W+px)*4;if(![a,b,c,e].every(finite)){pix[off+3]=0;continue}const v=a*(1-tx)*(1-ty)+b*tx*(1-ty)+c*(1-tx)*ty+e*tx*ty;let q=equalizedQ(v,range);if(S.active!=="temperature_anomaly")q=Math.pow(q,gamma);else q=Math.max(0,Math.min(1,.06+.88*q));const cc=color(S.active,q);pix[off]=Math.round(cc[0]*255);pix[off+1]=Math.round(cc[1]*255);pix[off+2]=Math.round(cc[2]*255);pix[off+3]=255}}ctx.putImageData(img,0,0);const tex=new BABYLON.DynamicTexture(`SOLVX FIELD TEXTURE ${S.active} ${layer}`,canvas,{generateMipMaps:false,samplingMode:BABYLON.Texture.BILINEAR_SAMPLINGMODE},sc);tex.hasAlpha=true;tex.update(false);const b=bounds(),lonSpan=Math.max(.001,b[1]-b[0])*111.32*Math.cos(((b[2]+b[3])/2)*Math.PI/180),latSpan=Math.max(.001,b[3]-b[2])*111.32;const mesh=BABYLON.MeshBuilder.CreateGround(`SOLVX FIELD ${S.active} ${layer}`,{width:lonSpan,height:latSpan,subdivisions:1,updatable:false},sc);mesh.position.y=depthY(depth);const mat=new BABYLON.StandardMaterial(`SOLVX FIELD MATERIAL ${layer}`,sc);mat.diffuseTexture=tex;mat.diffuseColor=BABYLON.Color3.White();mat.emissiveColor=BABYLON.Color3.White();mat.specularColor=BABYLON.Color3.Black();mat.backFaceCulling=false;mat.disableLighting=true;mat.alpha=1;mat.transparencyMode=BABYLON.Material.MATERIAL_ALPHABLEND;mesh.material=mat;mesh.renderingGroupId=20;mesh.isPickable=false;mesh.metadata={solvxField:true,depth:Number(depth)||0,range:[range.lo,range.hi],texture:true};return mesh}
async function scalar(){clearFields();clearCurrents();hideBase();const v=info(S.active);if(!v?.available){showBase();$('status').textContent=`${LABEL[S.active]}: no backend dataset detected`;return}const token=++S.token;try{const levels=(S.meta[v.file]?.values||[]).filter(finite);let indices;if(levels.length){const center=Math.max(0,Math.min(levels.length-1,Math.floor(levels.length/2))),n=Math.min(5,levels.length),start=Math.max(0,Math.min(levels.length-n,center-Math.floor(n/2)));indices=Array.from({length:n},(_,k)=>start+k)}else indices=[null];const frames=[];for(const idx of indices){const b=bounds(),q=new URLSearchParams({file:v.file,variable:v.variable,lat_min:String(b[2]),lat_max:String(b[3]),lon_min:String(b[0]),lon_max:String(b[1]),time_start:iso(S.times[S.i]),time_end:iso(S.times[S.i]),stride:"3"});if(idx!==null){q.set("depth_min",String(levels[idx]));q.set("depth_max",String(levels[idx]))}frames.push({f:await get("/data/region/array?"+q),depth:idx===null?0:levels[idx]})}if(token!==S.token)return;for(const frame of frames){const vals=flatten(frame.f.data).map(Number).filter(finite);if(!vals.length)continue;const range=rangeFor(vals,S.active);const m=makeField(frame.f,frame.depth,range,frames.indexOf(frame));if(m)S.fields.push(m);frame.range=range}if(!S.fields.length)throw Error("Backend returned no finite values");const ranges=frames.filter(x=>x.range).map(x=>x.range),lo=Math.min(...ranges.map(x=>x.lo)),hi=Math.max(...ranges.map(x=>x.hi));$('legendTitle').textContent=`${v.label} · locally adaptive 0.5–99.5 percentile`;$('legendLo').textContent=lo.toFixed(3);$('legendHi').textContent=hi.toFixed(3);$('legend').style.display="block";$('status').textContent=`${v.label} · ${S.fields.length} adaptive data layers · local contrast per layer · ${date(S.times[S.i])}`}catch(e){if(token===S.token){clearFields();showBase();$('status').textContent=`${LABEL[S.active]} failed: ${e.message}`;console.error(e)}}}
function makeArrow(x,z,dx,dz,len,mag){const sc=scene(),y=5,p=new BABYLON.Vector3(x,y,z),q=new BABYLON.Vector3(x+dx*len,y,z+dz*len),line=BABYLON.MeshBuilder.CreateLines("SOLVX CURRENT VECTOR",{points:[p,q],updatable:false},sc),head=BABYLON.MeshBuilder.CreateLines("SOLVX CURRENT MOVING HEAD",{points:[q,q,q,q],updatable:true},sc);line.color=new BABYLON.Color3(.02,.28,1);line.renderingGroupId=30;line.isPickable=false;head.color=new BABYLON.Color3(0,1,1);head.renderingGroupId=31;head.isPickable=false;S.currents.push({line,head,x,z,dx,dz,len,mag,phase:Math.random()})}
async function currents(){clearFields();clearCurrents();hideBase();try{const d=await get("/ocean/current-grid?"+new URLSearchParams({stride:"4",time:iso(S.times[S.i]),depth:"0"})),la=d.latitude||[],lo=d.longitude||[],u=d.u||[],v=d.v||[],mags=[];for(let j=0;j<la.length;j++)for(let i=0;i<lo.length;i++){const a=Number(u[j]?.[i]),b=Number(v[j]?.[i]);if(finite(a)&&finite(b))mags.push(Math.hypot(a,b))}mags.sort((a,b)=>a-b);const p95=quantile(mags,.95)||1,b=bounds(),lat0=(b[2]+b[3])/2,lon0=(b[0]+b[1])/2,klon=111.32*Math.cos(lat0*Math.PI/180);for(let j=0;j<la.length;j++)for(let i=0;i<lo.length;i++){const a=Number(u[j]?.[i]),bb=Number(v[j]?.[i]);if(!finite(a)||!finite(bb))continue;const mag=Math.hypot(a,bb);if(mag<p95*.005)continue;const x=(lo[i]-lon0)*klon,z=(la[j]-lat0)*111.32,ang=Math.atan2(bb,a),len=20+80*Math.min(1,mag/p95);makeArrow(x,z,Math.cos(ang),Math.sin(ang),len,mag)}$('legendTitle').textContent="Currents · speed + direction";$('legendLo').textContent="0 m/s";$('legendHi').textContent=`${p95.toFixed(3)} m/s`;$('legend').style.display="block";$('status').textContent=`Currents · ${S.currents.length} moving vectors · P95 ${p95.toFixed(3)} m/s · ${date(S.times[S.i])}`;animate(performance.now())}catch(e){showBase();$('status').textContent=`Currents failed: ${e.message}`;console.error(e)}}
function animate(t){for(const a of S.currents){const f=((t/900)*(.35+Math.min(2.2,a.mag/Math.max(a.mag,.001)))+a.phase)%1,d=f*a.len,x=a.x+a.dx*d,z=a.z+a.dz*d,tip=new BABYLON.Vector3(x,5,z),h1=new BABYLON.Vector3(x-a.dx*7-a.dz*3,5,z-a.dz*7+a.dz*0+a.dx*3),h2=new BABYLON.Vector3(x-a.dx*7+a.dz*3,5,z-a.dz*7-a.dz*0-a.dx*3),arr=a.head.getVerticesData(BABYLON.VertexBuffer.PositionKind);arr[0]=tip.x;arr[1]=5;arr[2]=tip.z;arr[3]=h1.x;arr[4]=5;arr[5]=h1.z;arr[6]=tip.x;arr[7]=5;arr[8]=tip.z;arr[9]=h2.x;arr[10]=5;arr[11]=h2.z;a.head.updateVerticesData(BABYLON.VertexBuffer.PositionKind,arr)}if(S.currents.length)S.raf=requestAnimationFrame(animate)}
async function meta(v){try{const m=await get("/metadata/"+encodeURIComponent(v.file));S.meta[v.file]={values:m.coordinates?.depth?.values||[]}}catch{S.meta[v.file]={values:[]}}}
function abnormal(){return null}
function buildVars(){const box=$("vars");if(!box)return;box.innerHTML="";for(const id of IDS){const v=info(id),b=document.createElement("button");b.className=`var ${v?.available?"":"off"} ${S.active===id?"active":""}`;b.innerHTML=`<span class="ico">${IDS.indexOf(id)+1}</span><span><strong>${LABEL[id]}</strong><span>${v?.available?(v.units||""):"No backend dataset detected"}</span></span><i class="dot ${v?.available?"":"off"}"></i>`;if(v?.available)b.onclick=()=>select(id);box.appendChild(b)}}
async function select(id){S.active=id;buildVars();clearFields();clearCurrents();const v=info(id);if(!v?.available){showBase();$("status").textContent=`${LABEL[id]}: no backend dataset detected`;return}if(id==="abnormal"){showBase();$("status").textContent="Abnormal/disaster data has no scalar ocean renderer";return}if(id==="currents"){await currents();return}await meta(v);await scalar()}
function setTime(i){if(!S.times.length)return;S.i=Math.max(0,Math.min(S.times.length-1,+i||0));$("timeSlider").value=S.i;$("timeValue").textContent=date(S.times[S.i]);$("timeRaw").textContent=iso(S.times[S.i]);$("timeCount").textContent=`${S.i+1}/${S.times.length}`;if(S.active==="currents")currents();else if(info(S.active)?.available)scalar()}
function bindTimeline(){const sl=$("timeSlider");if(sl)sl.addEventListener("input",e=>setTime(e.target.value));const play=$("play");if(play)play.onclick=()=>{S.playing=!S.playing;play.textContent=S.playing?"PAUSE":"PLAY";if(S.playing)stepPlay()}}
function stepPlay(){if(!S.playing)return;setTime((S.i+1)%Math.max(1,S.times.length));setTimeout(stepPlay,900)}
async function init(){try{S.geo=await fetch("geometry.json?"+Date.now()).then(r=>{if(!r.ok)throw Error("geometry.json "+r.status);return r.json()});const c=await get("/ocean/catalog");S.catalog=c.variables||[];const t=await get("/ocean/time");S.times=t.values||[];buildVars();bindTimeline();if(S.times.length){const sl=$("timeSlider");sl.max=S.times.length-1;sl.value=0;$("timeCount").textContent=`1/${S.times.length}`;$("timeValue").textContent=date(S.times[0]);$("timeRaw").textContent=iso(S.times[0])}const first=info("temperature")||S.catalog.find(x=>x.available);if(first)await select(first.id);else showBase()}catch(e){console.error(e);$("status").textContent=`Field renderer failed: ${e.message}`}}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();})();