(() => {
'use strict';
const API='http://127.0.0.1:8000';
const $=id=>document.getElementById(id);
const state={catalog:[],times:[],index:0,active:'temperature',playing:false,timer:null,field:null,geo:null,datasets:[],meta:{},currentArrows:[]};
const labels={temperature:'Temperature',temperature_anomaly:'Sea surface temp anomaly',salinity:'Salinity',currents:'Currents',sea_level:'Sea level',abnormal:'Abnormal / disaster data',chlorophyll:'Chlorophyll'};
const desc={temperature:'3D water temperature',temperature_anomaly:'SST anomaly',salinity:'Salinity / PSU',currents:'Direction and speed',sea_level:'Sea-surface height',abnormal:'Cyclone / warning layers',chlorophyll:'Chlorophyll-a'};
const cls={temperature:'temp',temperature_anomaly:'anomaly',salinity:'sal',chlorophyll:'chl',sea_level:'neutral'};
async function get(path){const r=await fetch(API+path,{cache:'no-store'});if(!r.ok)throw Error(`${r.status} ${path}`);return r.json()}
function date(v){const d=new Date(v);return Number.isNaN(d.getTime())?null:d}
function fmt(v){const d=date(v);return d?d.toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'}):String(v)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function bounds(){return state.geo?.bounds||[84.104975983510294,92.99298840579259,16.070728135396756,23.524363913510872]}
function variableInfo(id){return state.catalog.find(x=>x.id===id)||state.catalog.find(x=>x.id==='temperature')}
function buildVars(){const box=$('vars');if(!box)return;const abnormal=state.datasets.flatMap(d=>d.variables||[]).find(v=>/cyclone|storm|disaster|warning|alert|tropical/i.test(`${d.file} ${v.name} ${v.long_name||''} ${v.standard_name||''}`));const all=[...state.catalog.filter(x=>x.id!=='abnormal'),{id:'abnormal',label:labels.abnormal,available:!!abnormal,file:abnormal?.file,variable:abnormal?.name,units:abnormal?.units,long_name:abnormal?.long_name}];box.innerHTML=all.map((v,i)=>`<button class="var ${v.id===state.active?'active':''} ${v.available===false?'off':''}" data-var="${esc(v.id)}" ${v.available===false?'disabled':''}><span class="ico">${['temperature','temperature_anomaly','salinity','currents','sea_level','abnormal','chlorophyll'][i]==='currents'?'↗':i+1}</span><span><strong>${esc(v.label)}</strong><span>${esc(v.available===false?'No matching NetCDF source':desc[v.id]||'')}</span></span><i class="dot ${v.available===false?'off':''}"></i></button>`).join('');box.querySelectorAll('[data-var]').forEach(b=>b.onclick=()=>selectVar(b.dataset.var));updateLegend()}
function updateLegend(){const v=variableInfo(state.active),leg=$('legend'),title=$('legendTitle'),lo=$('legendLo'),hi=$('legendHi');if(!leg)return;if(state.active==='currents'||state.active==='abnormal'){leg.style.display='none';title.textContent=state.active==='currents'?'Arrows: direction + speed':'Event / warning layer';return}leg.style.display='block';leg.className=`legend ${cls[state.active]||'neutral'}`;title.textContent=`${v?.label||labels[state.active]} range`;const f=state.field;lo.textContent=f?.min!=null?`${Number(f.min).toFixed(2)} ${v?.units||''}`:'low';hi.textContent=f?.max!=null?`${Number(f.max).toFixed(2)} ${v?.units||''}`:'high'}
function setupTimeline(){const input=$('timeSlider');if(!input)return;input.max=Math.max(0,state.times.length-1);input.value=state.index;renderTicks();renderTime();input.oninput=()=>{state.index=+input.value;renderTime();loadField()};$('play').onclick=togglePlay}
function renderTicks(){const s=$('timeScale');if(!s)return;s.innerHTML='';const n=state.times.length;if(!n)return;const count=Math.min(9,n);for(let k=0;k<count;k++){const i=Math.round(k*(n-1)/(count-1||1));const t=document.createElement('span');t.className='tick';t.style.left=`${(i/(n-1||1))*100}%`;t.textContent=fmt(state.times[i]);s.appendChild(t)}}
function renderTime(){const v=state.times[state.index];$('timeValue').textContent=v?fmt(v):'No time coordinate';$('timeRaw').textContent=v||'';const input=$('timeSlider');if(input)input.value=state.index}
function togglePlay(){if(state.playing){clearInterval(state.timer);state.playing=false;$('play').textContent='PLAY';return}if(state.times.length<2)return;state.playing=true;$('play').textContent='PAUSE';state.timer=setInterval(()=>{state.index=(state.index+1)%state.times.length;renderTime();loadField()},650)}
function colorFor(id,t){t=Math.max(0,Math.min(1,t));if(id==='temperature')return [0.03+0.90*t,0.22+0.50*t,0.85-0.78*t];if(id==='temperature_anomaly')return [0.10+0.82*t,0.40+0.30*(1-t),0.80-0.65*t];if(id==='salinity')return [0.05+0.30*t,0.30+0.60*t,0.90-0.50*t];if(id==='chlorophyll')return [0.86-0.82*t,0.96-0.20*t,0.75-0.55*t];if(id==='sea_level')return [0.70-0.45*t,0.84-0.35*t,0.92-0.35*t];return [0.08,0.20,0.65]}
function nearest(arr,x){if(!Array.isArray(arr)||!arr.length)return -1;let lo=0,hi=arr.length-1;const asc=arr[0]<=arr[hi];while(lo<hi){const m=(lo+hi)>>1;if(asc?(arr[m]<x):(arr[m]>x))lo=m+1;else hi=m}if(lo===0)return 0;if(lo===arr.length-1)return lo;return Math.abs(arr[lo]-x)<Math.abs(arr[lo-1]-x)?lo:lo-1}
function flatValues(a){const out=[];(function walk(x){if(Array.isArray(x))x.forEach(walk);else if(typeof x==='number'&&Number.isFinite(x))out.push(x)})(a);return out}
function applyField(field){state.field=field;updateLegend();const engine=BABYLON.Engine.LastCreatedEngine;const scene=engine?.scenes?.[0];if(!scene)return;const b=bounds(),klat=111.32,klon=111.32*Math.cos(((b[2]+b[3])/2)*Math.PI/180),lon0=(b[0]+b[1])/2,lat0=(b[2]+b[3])/2;const lat=field.coordinates?.latitude||field.coordinates?.lat,lon=field.coordinates?.longitude||field.coordinates?.lon,dep=field.coordinates?.depth,values=field.data,dims=field.dimensions||[];if(!lat||!lon||!values)return;const finite=flatValues(values),min=finite.length?Math.min(...finite):null,max=finite.length?Math.max(...finite):null;state.field.min=min;state.field.max=max;updateLegend();scene.meshes.filter(m=>m.metadata?.waterLayer).forEach(mesh=>{mesh.material.useVertexColors=true;mesh.material.diffuseColor=new BABYLON.Color3(1,1,1);mesh.material.emissiveColor=new BABYLON.Color3(.01,.01,.01);const pos=mesh.getVerticesData(BABYLON.VertexBuffer.PositionKind);if(!pos)return;const colors=[];const depthLevel=mesh.metadata?.depth;const di=dep&&depthLevel!=null?nearest(dep,depthLevel):0;const ny=lat.length,nx=lon.length;const hasDepth=dims.includes('depth');for(let k=0;k<pos.length;k+=3){const la=lat0+pos[k+2]/klat,lo=lon0+pos[k]/klon,yi=nearest(lat,la),xi=nearest(lon,lo);let val=null;if(hasDepth&&Array.isArray(values[di]))val=values[di]?.[yi]?.[xi];else if(Array.isArray(values[0]))val=values[yi]?.[xi];else val=values[0];const q=typeof val==='number'&&Number.isFinite(val)&&max!==min?(val-min)/(max-min):.45;const c=colorFor(state.active,q);colors.push(c[0],c[1],c[2],1)}mesh.setVerticesData(BABYLON.VertexBuffer.ColorKind,colors,true)})}
async function loadField(){const v=variableInfo(state.active);if(!v?.available||!v.file||!v.variable)return;if(state.active==='currents')return loadCurrents();try{const qs=new URLSearchParams({file:v.file,variable:v.variable,lat_min:String(bounds()[2]),lat_max:String(bounds()[3]),lon_min:String(bounds()[0]),lon_max:String(bounds()[1]),time_start:String(state.times[state.index]||''),time_end:String(state.times[state.index]||''),stride:'3'});if(state.meta[v.file]?.depth){qs.set('depth_min',String(state.meta[v.file].depth.min));qs.set('depth_max',String(state.meta[v.file].depth.max))}const r=await get('/data/region/array?'+qs);const nums=flatValues(r.data);r.min=nums.length?Math.min(...nums):null;r.max=nums.length?Math.max(...nums):null;applyField(r)}catch(e){$('status').textContent=`Field unavailable: ${e.message}`}}
async function loadCurrents(){try{const t=state.times[state.index],r=await get('/ocean/current-grid?time='+encodeURIComponent(t||'')+'&stride=5'),engine=BABYLON.Engine.LastCreatedEngine,scene=engine?.scenes?.[0];if(!scene)return;state.currentArrows.forEach(m=>m.dispose());state.currentArrows=[];const b=bounds(),klat=111.32,klon=111.32*Math.cos(((b[2]+b[3])/2)*Math.PI/180),lon0=(b[0]+b[1])/2,lat0=(b[2]+b[3])/2;for(let j=0;j<r.latitude.length;j+=2)for(let i=0;i<r.longitude.length;i+=2){const u=r.u[j]?.[i],v=r.v[j]?.[i];if(!Number.isFinite(u)||!Number.isFinite(v))continue;const x=(r.longitude[i]-lon0)*klon,z=(r.latitude[j]-lat0)*klat,s=.7,p=new BABYLON.Vector3(x,3.8,z),q=new BABYLON.Vector3(x+u*s,3.8,z+v*s),line=BABYLON.MeshBuilder.CreateLines('current-arrow',{points:[p,q],updatable:false},scene);line.color=new BABYLON.Color3(.02,.12,.48);line.metadata={solvx:true,currentArrow:true};state.currentArrows.push(line)}$('status').textContent=`Currents · ${r.units||'m/s'} · ${fmt(t)}`}catch(e){$('status').textContent='Current field unavailable'}}
async function selectVar(id){state.active=id;document.querySelectorAll('.var').forEach(b=>b.classList.toggle('active',b.dataset.var===id));updateLegend();await loadField()}
async function pointReadout(point,mesh){const b=bounds(),klat=111.32,klon=111.32*Math.cos(((b[2]+b[3])/2)*Math.PI/180),lon=(b[0]+b[1])/2+point.x/klon,lat=(b[2]+b[3])/2+point.z/klat;let depth=null;if(mesh?.metadata?.waterLayer)depth=mesh.metadata.depth;const t=state.times[state.index];$('coords').textContent=`${lat.toFixed(4)}°N · ${lon.toFixed(4)}°E`;$('readout').style.display='block';$('readoutGrid').innerHTML='<div class="rval">Loading variables…</div>';try{const r=await get('/ocean/point?latitude='+lat+'&longitude='+lon+'&time='+encodeURIComponent(t||''));const cards=[];for(const x of r.values||[]){let val=x.value;if(x.id!=='currents'&&x.available){const v=variableInfo(x.id);if(v?.file&&v?.variable){try{const q=new URLSearchParams({file:v.file,variable:v.variable,latitude:String(lat),longitude:String(lon),time:String(t||'')});if(depth!=null)q.set('depth',String(depth));const z=await get('/data/point?'+q);val=z.value??(z.data?.[0]?.[v.variable])}catch{}}}cards.push(`<div class="rval"><b>${esc(x.label)}</b><span>${typeof val==='object'?esc(JSON.stringify(val)):val==null?'—':esc(Number(val).toFixed?.(3)??val)} ${esc(x.units||'')}</span></div>`)}$('readoutGrid').innerHTML=cards.join('');$('readoutTime').textContent=`${fmt(t)} · depth ${depth==null?'surface':Number(depth).toFixed(1)+' m'}`}catch(e){$('readoutGrid').innerHTML='<div class="rval">Point data unavailable</div>'}}
async function init(){try{state.geo=await fetch('geometry.json?'+Date.now(),{cache:'no-store'}).then(r=>r.json());const [cat,tim,dsets]=await Promise.all([get('/ocean/catalog'),get('/ocean/time'),get('/datasets')]);state.catalog=cat.variables;state.times=tim.values||[];state.datasets=dsets.datasets||[];for(const c of state.catalog.filter(x=>x.available)){try{const m=await get('/metadata/'+encodeURIComponent(c.file));state.meta[c.file]={depth:m.coordinates?.depth||null}}catch{}}buildVars();setupTimeline();renderTime();$('closeReadout').onclick=()=>$('readout').style.display='none';const engine=BABYLON.Engine.LastCreatedEngine,scene=engine?.scenes?.[0];if(scene){scene.onPointerObservable.add(async e=>{if(e.type!==BABYLON.PointerEventTypes.POINTERDOWN||e.event.button!==0)return;const pick=scene.pick(scene.pointerX,scene.pointerY,m=>m.metadata?.waterLayer||m.name==='GEBCO SOIL SEABED');if(pick?.hit&&pick.pickedPoint)await pointReadout(pick.pickedPoint,pick.pickedMesh)})}await loadField()}catch(e){console.warn('Ocean data UI:',e)}}
setTimeout(init,700);
})();
