(()=>{
'use strict';
const $=id=>document.getElementById(id);
const finite=v=>Number.isFinite(Number(v));
const API=`${location.protocol==='file:'?'http:':location.protocol}//${location.hostname||'127.0.0.1'}:8000`;
const IDS=['temperature','temperature_anomaly','salinity','currents','sea_level','abnormal','chlorophyll'];
const LABEL={temperature:'Temperature',temperature_anomaly:'SST anomaly',salinity:'Salinity',currents:'Currents',sea_level:'Sea level',abnormal:'Abnormal / hazard',chlorophyll:'Chlorophyll'};
const PAL={temperature:[[0x071b8f,0],[0x075cff,.15],[0x00c6ff,.32],[0x00e79a,.48],[0xfff000,.62],[0xff6b00,.80],[0xb40000,1]],temperature_anomaly:[[0x06349e,0],[0x4b9fe8,.25],[0xffffff,.5],[0xffa060,.75],[0xb60018,1]],salinity:[[0x071d9b,0],[0x00a6ff,.20],[0x00d49a,.42],[0xb8e52e,.68],[0xffe600,1]],sea_level:[[0x102caa,0],[0x00a9ff,.25],[0x26d08b,.50],[0xffd21a,.75],[0xd40000,1]],chlorophyll:[[0xf7fff0,0],[0xb7ef59,.20],[0x42c83e,.45],[0x078d38,.72],[0x003d20,1]],fallback:[[0x071b8f,0],[0x00cfff,.25],[0xfff000,.5],[0xff6a00,.75],[0xb40000,1]]};
const S={catalog:[],times:[],ti:0,active:'temperature',geo:null,scene:null,arrows:[]};
const get=async p=>{const r=await fetch(p,{cache:'no-store'});if(!r.ok){let t='';try{t=await r.text()}catch{}throw Error(`${r.status} ${t||r.statusText}`)}return r.json()};
const getApi=p=>get(API+p);
const flat=(v,o=[])=>{if(Array.isArray(v))v.forEach(x=>flat(x,o));else o.push(v);return o};
const finiteFlat=v=>flat(v).map(Number).filter(Number.isFinite);
function quantile(a,p){if(!a.length)return null;const x=(a.length-1)*p,i=Math.floor(x),j=Math.ceil(x);return a[i]+(a[j]-a[i])*(x-i)}
function date(v){const d=new Date(v);return isNaN(d)?String(v??'—'):d.toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'})}
function iso(v){const d=new Date(v);return isNaN(d)?String(v??''):d.toISOString()}
function status(text,type='ok'){const e=$('status');if(e)e.textContent=text;const dot=$('statusDot');if(dot)dot.className='statusdot '+(type==='error'?'error':type==='busy'?'busy':'')}
function findScene(){if(S.scene&&!S.scene.isDisposed?.())return S.scene;const B=window.BABYLON;if(!B)return null;const engines=B.Engine?.Instances||B.EngineStore?.Instances||[];for(const e of engines){if(e?.scenes?.length){S.scene=e.scenes[0];return S.scene}}return null}
function bounds(){return S.geo?.bounds||[84.104975983510294,92.99298840579259,16.070728135396756,23.524363913510872]}
function color(id,q){const p=PAL[id]||PAL.fallback;q=Math.max(0,Math.min(1,q));for(let i=0;i<p.length-1;i++){const a=p[i],b=p[i+1];if(q<=b[1]){const t=(q-a[1])/(b[1]-a[1]||1);const ca=BABYLON.Color3.FromHexString('#'+a[0].toString(16).padStart(6,'0'));const cb=BABYLON.Color3.FromHexString('#'+b[0].toString(16).padStart(6,'0'));return BABYLON.Color3.Lerp(ca,cb,t)}}return BABYLON.Color3.FromHexString('#'+p[p.length-1][0].toString(16).padStart(6,'0'))}
function waterMeshes(){const sc=findScene();return sc?sc.meshes.filter(m=>m.metadata?.waterLayer&&!m.metadata?.solvxWaterSurface&&!m.isDisposed?.()):[]}
function clearArrows(){for(const a of S.arrows)a.dispose(false,true);S.arrows=[]}
function restoreWater(){clearArrows();for(const m of waterMeshes()){m.setEnabled(true);if(m.material){m.material.useVertexColors=false;m.material.diffuseColor=new BABYLON.Color3(.004,.075,.30);m.material.emissiveColor=new BABYLON.Color3(.001,.006,.025)}}}
function vars(){const box=$('vars');if(!box)return;box.innerHTML='';for(let i=0;i<IDS.length;i++){const id=IDS[i],v=S.catalog.find(x=>x.id===id),b=document.createElement('button');b.className=`var ${v?.available?'':'off'} ${S.active===id?'active':''}`;b.innerHTML=`<span class="ico">${i+1}</span><span><strong>${LABEL[id]}</strong><span>${v?.available?(v.units||'available'):'No backend dataset detected'}</span></span><i class="dot ${v?.available?'':'off'}"></i>`;if(v?.available)b.onclick=()=>select(id);box.appendChild(b)}}
function fieldRange(values,id){const a=finiteFlat(values).sort((x,y)=>x-y);if(!a.length)return null;let lo=quantile(a,.005),hi=quantile(a,.995);if(id==='temperature_anomaly'){const m=Math.max(Math.abs(lo),Math.abs(hi));lo=-m;hi=m}if(!(hi>lo)){const pad=Math.max(Math.abs(lo)*.02,1e-5);lo-=pad;hi+=pad}return{lo,hi}}
function nearestIndex(values,target){if(!Array.isArray(values)||!values.length||!finite(target))return 0;let best=0,bestD=Infinity;for(let i=0;i<values.length;i++){const d=Math.abs(Number(values[i])-target);if(d<bestD){bestD=d;best=i}}return best}
function valueAt(f,indices){const shape=f.shape||[],raw=flat(f.data||[]);if(!shape.length)return Number(raw[0]);let linear=0,stride=1;for(let k=shape.length-1;k>=0;k--){linear+=(indices[k]||0)*stride;stride*=shape[k]}return Number(raw[linear])}
function descriptor(f){const dims=f.dimensions||[],shape=f.shape||[],latDim=dims.includes('latitude')?dims.indexOf('latitude'):dims.indexOf('lat'),lonDim=dims.includes('longitude')?dims.indexOf('longitude'):dims.indexOf('lon'),depthName=['depth','deptht','depthu','depthv','depthw','lev','level','z'].find(n=>dims.includes(n)),depthDim=depthName?dims.indexOf(depthName):-1;const lat=Array.from(f.coordinates?.latitude||f.coordinates?.lat||[]).map(Number),lon=Array.from(f.coordinates?.longitude||f.coordinates?.lon||[]).map(Number),depth=depthDim>=0?Array.from(f.coordinates?.[depthName]||[]).map(Number):[];if(latDim<0||lonDim<0)throw Error('Backend field has no latitude/longitude dimensions');return{dims,shape,lat,lon,depth,latDim,lonDim,depthDim}}
function meshDepth(mesh){return finite(mesh.metadata?.depth)?Number(mesh.metadata.depth):0}
function colorLayers(f,range){const d=descriptor(f),meshes=waterMeshes();if(!meshes.length)throw Error('No water layers exist');const b=bounds(),lat0=(b[2]+b[3])/2,lon0=(b[0]+b[1])/2,klat=111.32,klon=111.32*Math.cos(lat0*Math.PI/180),surfaceDepth=Math.min(...meshes.map(meshDepth));for(const mesh of meshes){const dep=meshDepth(mesh),di=d.depthDim>=0?nearestIndex(d.depth,dep):0,pos=mesh.getVerticesData(BABYLON.VertexBuffer.PositionKind);if(!pos)continue;const colors=[];let valid=0;for(let k=0;k<pos.length;k+=3){const lon=lon0+pos[k]/klon,lat=lat0+pos[k+2]/klat,yi=nearestIndex(d.lat,lat),xi=nearestIndex(d.lon,lon),ix=new Array(d.shape.length).fill(0);ix[d.latDim]=yi;ix[d.lonDim]=xi;if(d.depthDim>=0)ix[d.depthDim]=di;const v=valueAt(f,ix);if(!finite(v)){colors.push(.003,.012,.035,1);continue}let q=(v-range.lo)/(range.hi-range.lo);q=Math.max(0,Math.min(1,q));const c=color(S.active,Math.pow(q,.82));colors.push(c.r,c.g,c.b,1);valid++}if(valid===0){mesh.setEnabled(false);continue}mesh.setEnabled(true);mesh.setVerticesData(BABYLON.VertexBuffer.ColorKind,colors,true);mesh.material.useVertexColors=true;mesh.material.diffuseColor=new BABYLON.Color3(1,1,1);mesh.material.emissiveColor=new BABYLON.Color3(.13,.13,.13);if(d.depthDim<0&&dep-surfaceDepth>80)mesh.setEnabled(false)}}
async function renderScalar(v){const p=new URLSearchParams({file:v.file,variable:v.variable,...{}});const b=bounds();p.set('lat_min',b[2]);p.set('lat_max',b[3]);p.set('lon_min',b[0]);p.set('lon_max',b[1]);p.set('stride','3');if(S.times[S.ti]){p.set('time_start',iso(S.times[S.ti]));p.set('time_end',iso(S.times[S.ti]))}const f=await getApi('/data/region/array?'+p);const vals=finiteFlat(f.data),range=fieldRange(vals,S.active);if(!range)throw Error('Backend returned no finite numeric values');restoreWater();colorLayers(f,range);$('legend').style.display='block';$('legendTitle').textContent=`${v.label} · adaptive 0.5–99.5%`;$('legendLo').textContent=range.lo.toFixed(3);$('legendHi').textContent=range.hi.toFixed(3);const d=descriptor(f);$('depthBadge').textContent=d.depth.length?`32 depth-aware source layers`:'Surface field · top water layers';window.__SOLVX_TIMES__=S.times;status(`${v.label} · REAL DATA · 50 water layers colored from backend values`)}
async function renderCurrents(){restoreWater();const meshes=waterMeshes(),depth=meshes.length?Math.min(...meshes.map(meshDepth)):0;const r=await getApi('/ocean/current-grid?time='+encodeURIComponent(iso(S.times[S.ti]))+'&depth='+encodeURIComponent(depth)+'&stride=5'),b=bounds(),lat0=(b[2]+b[3])/2,lon0=(b[0]+b[1])/2,klat=111.32,klon=111.32*Math.cos(lat0*Math.PI/180),sc=findScene();const speed=finiteFlat([r.u,r.v]);const mags=[];for(let j=0;j<r.latitude.length;j++)for(let i=0;i<r.longitude.length;i++){const u=Number(r.u?.[j]?.[i]),v=Number(r.v?.[j]?.[i]);if(finite(u)&&finite(v))mags.push(Math.hypot(u,v))}const max=Math.max(quantile(mags.sort((a,b)=>a-b),.99)||1e-6,1e-6);for(let j=0;j<r.latitude.length;j++)for(let i=0;i<r.longitude.length;i++){const u=Number(r.u?.[j]?.[i]),v=Number(r.v?.[j]?.[i]);if(!finite(u)||!finite(v))continue;const m=Math.hypot(u,v);if(m<max*.02)continue;const x=(r.longitude[i]-lon0)*klon,z=(r.latitude[j]-lat0)*klat,scale=5+Math.min(30,m/max*30),start=new BABYLON.Vector3(x,5,z),end=new BABYLON.Vector3(x+u/m*scale,5,z+v/m*scale),line=BABYLON.MeshBuilder.CreateLines(`current-${j}-${i}`,{points:[start,end]},sc);line.color=color('sea_level',m/max);line.metadata={currentArrow:true,solvx:true};line.isPickable=false;S.arrows.push(line)}$('legend').style.display='none';$('depthBadge').textContent=`Current depth ${Number(depth).toFixed(1)} m`;status('Currents · direction + magnitude vectors · real backend data')}
async function select(id){S.active=id;vars();if(id==='abnormal'){restoreWater();$('legend').style.display='none';status('No abnormal/hazard dataset registered');return}const v=S.catalog.find(x=>x.id===id);if(!v?.available){restoreWater();status(`${LABEL[id]}: no backend dataset detected`,'error');return}status(`Loading ${v.label}…`,'busy');try{if(id==='currents')await renderCurrents();else await renderScalar(v)}catch(e){console.error(e);restoreWater();status(`${LABEL[id]} render failed: ${e.message}`,'error')}}
async function boot(){let tries=0;while(!findScene()&&tries++<240)await new Promise(r=>setTimeout(r,50));if(!findScene()){status('Babylon scene not found','error');return}try{S.geo=await get('geometry.json?'+Date.now());const cat=await getApi('/ocean/catalog');S.catalog=cat.variables||[];vars();const t=await getApi('/ocean/time');S.times=t.values||[];window.__SOLVX_TIMES__=S.times;const sl=$('timeSlider');if(sl){sl.max=Math.max(0,S.times.length-1);sl.value=0;sl.oninput=()=>{S.ti=+sl.value||0;if(S.times[S.ti]){$('timeValue').textContent=date(S.times[S.ti]);$('timeRaw').textContent=iso(S.times[S.ti]);$('timeCount').textContent=`${S.ti+1}/${S.times.length}`}select(S.active)}}if(S.times.length){$('timeValue').textContent=date(S.times[0]);$('timeRaw').textContent=iso(S.times[0]);$('timeCount').textContent=`1/${S.times.length}`}const play=$('play');if(play)play.onclick=()=>{if(play.dataset.run==='1'){play.dataset.run='0';play.textContent='PLAY';clearInterval(play._tm);return}play.dataset.run='1';play.textContent='PAUSE';play._tm=setInterval(()=>{S.ti=(S.ti+1)%S.times.length;if(sl)sl.value=S.ti;$('timeValue').textContent=date(S.times[S.ti]);$('timeRaw').textContent=iso(S.times[S.ti]);$('timeCount').textContent=`${S.ti+1}/${S.times.length}`;select(S.active)},1200)};const first=S.catalog.find(v=>v.id==='temperature'&&v.available)||S.catalog.find(v=>v.available);if(first)await select(first.id);else{restoreWater();status('No usable backend variables found','error')}}catch(e){console.error(e);vars();restoreWater();status(`Ocean data boot failed: ${e.message}`,'error')}}
window.__SOLVX_SELECT__=select;boot();
})();