(()=>{
'use strict';
const API=(location.protocol==='file:'?'http:':location.protocol)+'//'+(location.hostname||'127.0.0.1')+':8000', $=id=>document.getElementById(id), finite=v=>Number.isFinite(Number(v));
const IDS=['temperature','temperature_anomaly','salinity','currents','sea_level','abnormal','chlorophyll'];
const LABEL={temperature:'Temperature',temperature_anomaly:'Sea surface temp anomaly',salinity:'Salinity',currents:'Currents',sea_level:'Sea level',abnormal:'Abnormal / hazard',chlorophyll:'Chlorophyll'};
const PAL={temperature:[[0,.1,1],[0,.8,1],[1,1,0],[1,.2,0],[.5,0,0]],temperature_anomaly:[[.05,.25,1],[.1,.7,1],[1,1,1],[1,.35,.1],[.65,0,.02]],salinity:[[.05,.1,1],[0,.8,1],[0,1,.5],[1,.9,0],[.8,.1,0]],sea_level:[[.05,.1,1],[0,.8,1],[.2,1,.6],[1,.8,0],[.8,0,0]],chlorophyll:[[.9,1,.8],[.45,.95,.15],[0,.7,.12],[0,.28,.03]],fallback:[[.05,.1,1],[0,.8,1],[1,1,0],[1,.2,0],[.55,0,0]]};
const S={catalog:[],times:[],ti:0,active:'temperature',geo:null,mesh:null,scene:null};
const flat=(v,o=[])=>{if(Array.isArray(v))v.forEach(x=>flat(x,o));else o.push(v);return o};
const get=async p=>(await fetch(API+p,{cache:'no-store'})).json();
function scene(){if(S.scene&&!S.scene.isDisposed())return S.scene;const e=BABYLON.Engine.LastCreatedEngine;S.scene=e?.scenes?.[0]||null;return S.scene}
function status(t){if($('status'))$('status').textContent=t}
function rgb(p,q){q=Math.max(0,Math.min(1,q));const x=q*(p.length-1),i=Math.min(p.length-2,Math.floor(x)),t=x-i,a=p[i],b=p[i+1];return[a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t,a[2]+(b[2]-a[2])*t]}
function makeShader(){BABYLON.Effect.ShadersStore.oceanFieldVertex='precision highp float;attribute vec3 position;attribute vec4 color;uniform mat4 worldViewProjection;varying vec4 vColor;void main(){vColor=color;gl_Position=worldViewProjection*vec4(position,1.0);}';BABYLON.Effect.ShadersStore.oceanFieldFragment='precision highp float;varying vec4 vColor;void main(){gl_FragColor=vColor;}';return new BABYLON.ShaderMaterial('OCEAN_FIELD_SHADER',scene(),{vertex:'oceanField',fragment:'oceanField'},{attributes:['position','color'],uniforms:['worldViewProjection']})}
function clear(){if(S.mesh){S.mesh.dispose(false,true);S.mesh=null}}
function fallback(){const s=scene();if(!s)return;clear();const b=S.geo?.bounds||[84.1,93,16.07,23.52],lat0=(b[2]+b[3])/2,lon0=(b[0]+b[1])/2,klon=111.32*Math.cos(lat0*Math.PI/180),p=[],c=[],ix=[],nx=60,ny=48;for(let y=0;y<ny;y++)for(let x=0;x<nx;x++){const u=x/(nx-1),v=y/(ny-1),q=.5+.3*Math.sin(u*13)+.22*Math.cos(v*17)+.12*Math.sin((u+v)*29),cc=rgb(PAL.fallback,Math.max(0,Math.min(1,q)));p.push((u-.5)*(b[1]-b[0])*klon,4,(v-.5)*(b[3]-b[2])*111.32);c.push(cc[0],cc[1],cc[2],1)}for(let y=0;y<ny-1;y++)for(let x=0;x<nx-1;x++){const a=y*nx+x,b1=a+1,d=a+nx,e=d+1;ix.push(a,d,b1,b1,d,e)}const vd=new BABYLON.VertexData();vd.positions=p;vd.colors=c;vd.indices=ix;S.mesh=new BABYLON.Mesh('SOLVX_COLOR_FALLBACK',s);vd.applyToMesh(S.mesh,true);S.mesh.hasVertexAlpha=true;S.mesh.material=makeShader();S.mesh.isPickable=false;S.mesh.renderingGroupId=0}
function vars(){const box=$('vars');if(!box)return;box.innerHTML='';IDS.forEach((id,i)=>{const v=S.catalog.find(x=>x.id===id),b=document.createElement('button');b.className='var '+(v?.available?'':'off')+(S.active===id?' active':'');b.innerHTML='<span class="ico">'+(i+1)+'</span><span><strong>'+LABEL[id]+'</strong><span>'+(v?.units||'No matching dataset')+'</span></span><i class="dot '+(v?.available?'':'off')+'"></i>';if(v?.available)b.onclick=()=>draw();box.appendChild(b)})}
async function draw(){const v=S.catalog.find(x=>x.id===S.active);if(!v?.available){fallback();status(LABEL[S.active]+' · visual fallback');return}try{const b=S.geo.bounds,q=new URLSearchParams({file:v.file,variable:v.variable,lat_min:b[2],lat_max:b[3],lon_min:b[0],lon_max:b[1],stride:'3'});if(S.times[S.ti]){q.set('time_start',new Date(S.times[S.ti]).toISOString());q.set('time_end',new Date(S.times[S.ti]).toISOString())}const f=await get('/data/region/array?'+q),a=flat(f.data).map(Number).filter(finite).sort((x,y)=>x-y);if(!a.length)throw Error('empty data');const lo=a[Math.floor(a.length*.005)],hi=a[Math.floor(a.length*.995)],d=f,sc=scene();clear();const dims=d.dimensions||[],shape=d.shape||[],la=(d.coordinates?.latitude||[]).map(Number),loN=(d.coordinates?.longitude||[]).map(Number),li=dims.indexOf('latitude'),oi=dims.indexOf('longitude');if(li<0||oi<0)throw Error('missing latitude/longitude');const raw=flat(d.data),nx=shape[oi],ny=shape[li],vals=[];for(let y=0;y<ny;y++)for(let x=0;x<nx;x++){const ix=Array(shape.length).fill(0);ix[li]=y;ix[oi]=x;let z=0,m=1;for(let k=shape.length-1;k>=0;k--){z+=ix[k]*m;m*=shape[k]}vals.push(Number(raw[z]))}const bb=S.geo.bounds,lat0=(bb[2]+bb[3])/2,lon0=(bb[0]+bb[1])/2,klon=111.32*Math.cos(lat0*Math.PI/180),p=[],c=[],idx=[];for(let y=0;y<ny;y++)for(let x=0;x<nx;x++){p.push((loN[x]-lon0)*klon,4,(la[y]-lat0)*111.32);let z=(vals[y*nx+x]-lo)/(hi-lo||1);z=Math.pow(Math.max(0,Math.min(1,z)),.7);const cc=rgb(PAL[S.active]||PAL.fallback,z);c.push(cc[0],cc[1],cc[2],1)}for(let y=0;y<ny-1;y++)for(let x=0;x<nx-1;x++){const aa=y*nx+x,bb1=aa+1,cc1=aa+nx,dd=cc1+1;if([vals[aa],vals[bb1],vals[cc1],vals[dd]].every(finite))idx.push(aa,cc1,bb1,bb1,cc1,dd)}const vd=new BABYLON.VertexData();vd.positions=p;vd.colors=c;vd.indices=idx;S.mesh=new BABYLON.Mesh('SOLVX_MEASURED_FIELD',sc);vd.applyToMesh(S.mesh,true);S.mesh.hasVertexAlpha=true;S.mesh.material=makeShader();S.mesh.isPickable=false;S.mesh.renderingGroupId=0;if($('legendTitle'))$('legendTitle').textContent=v.label+' · adaptive 0.5–99.5%';if($('legendLo'))$('legendLo').textContent=lo.toFixed(3);if($('legendHi'))$('legendHi').textContent=hi.toFixed(3);if($('legend'))$('legend').style.display='block';status(v.label+' · real backend field')}catch(e){console.error(e);fallback();status(LABEL[S.active]+' · fallback variation (renderer recovery)')}}
async function boot(){let n=0;while(!scene()&&n++<200)await new Promise(r=>setTimeout(r,50));if(!scene())return;try{S.geo=await get('/geometry.json?'+Date.now());S.catalog=(await get('/ocean/catalog')).variables||[];S.times=(await get('/ocean/time')).values||[];vars();if(S.times.length){$('timeSlider').max=S.times.length-1;$('timeValue').textContent=new Date(S.times[0]).toLocaleDateString();$('timeRaw').textContent=new Date(S.times[0]).toISOString();$('timeCount').textContent='1/'+S.times.length}$('timeSlider').oninput=e=>{S.ti=+e.target.value||0;draw()};await draw()}catch(e){console.error(e);vars();fallback();status('Field renderer recovered with visual fallback')}}
boot();
})();